### ISSUE TITLE
Need for ENaddrule and ENaddcontrol functions

### ISSUE THREAD

**Issue by eladsal** [OpenWaterAnalytics/EPANET#104]
We already have the get\set functions for rules and controls but the ability to add (and also remove) them is still needed.

**Comment by eladsal** [comment]
Been thinking about the `ENaddcontrol` function. My idea is to have it like the `ENsetcontrol` one and to return the new control index. Any thoughts on this?

**Comment by eladsal** [comment]
@LRossman I already added the `EN_addcontrol` API, do you have the `EN_addrule` API in the work you are doing now or we are moving this to v2.3?

**Comment by LRossman** [comment]
@eladsal I can add an `EN_addrule `and associated functions (`EN_addpremise`, `EN_addthenaction`, `EN_addelseaction`) by the end of the week if that's ok.

**Comment by eladsal** [comment]
@LRossman I think that would be perfect, thanks!
