### ISSUE TITLE
Test and Document the net-builder additions

### ISSUE THREAD

**Issue by samhatchett** [OpenWaterAnalytics/EPANET#106]
we've got some great new api functions for building/modifying networks without depending on the `inp` file - these should be (dox)umented and tested in some way, and incorporated in the CI tests.

One way to really put this functionality to the test would be to refactor the `inputX.c` modules so that the `inp` parser uses these public API functions instead of directly modifying the private structs. But that sounds like a lot of work.

Any discussion?

**Comment by kobusvanzyl** [comment]
If the code was fully object oriented, I think the way to do it would be to parse the parameters from a line in the the input file and then create the object with these as arguments. The API functions are only used when modifying the object parameters after initiation. 

Based on this I suggest that we maintain the current direct initiation of private structs, but move to the api functions for other modifications.

**Comment by AbelHeinsbroek** [comment]
Agreed. The API functions do a lot of 'index shuffing' and are therefore not as efficient as the current method of parsing the input file and instantiating the structs and arrays directly

**Comment by samhatchett** [comment]
It's a tough call. If we were designing this thing over again, then no question the parser would only have access to the public API. But as it is, we are left with 2 different code paths for creating elements. This has a maintenance tradeoff. Fewer lines == fewer opportunity for bugs.

On the issue of performance, I have no doubt that individually creating elements would have an impact. But is that impact 5% or 500% ? The answer probably matters. Presuming major performance degradation and therefore deciding against making the code more readable and componentized sounds to me like premature optimization. 

On the other hand, this is v2.x - and while this code is by no means at the end of its useful life, how much time/energy should 2.x get when there's the allure of the 3.x design opportunities?
