### ISSUE TITLE
Include bindings and tools in 2.2 release package

### ISSUE THREAD

**Issue by samhatchett** [OpenWaterAnalytics/EPANET#107]
In the next release package (v2.2), it has been suggested to include some basic language bindings so that the download is a more comprehensive "download-and-go" type of tool. 

Suggest we include the latest wrappers for:
- R
- Python
- Matlab
- VB

... along with some useful extra tools like the the output file parser library and maybe some python scripts (for example, to save result binaries to HDF5 format).

any other favorite wrappers or tools to add to the list?

**Comment by bradleyjeck** [comment]
I'm working on a package with R bindings. Hopefully an initial release will happen later this summer. 

In terms of including the bindings in a future release of epanet this is ok.  However, from the R side it is much more convenient to download a package from CRAN that has functions already connected to the epanet engine.

**Comment by samhatchett** [comment]
thanks, this is really helpful feedback. perhaps we need a master plan for what package managers to support, and what that would take technically as part of a release, how to coordinate with wrappers distributed on GH. Some package managers integrate well with GH-hosted projects, others I'm not so sure. So, a list of package managers too - for discussion?

- Conda
- pip
- CRAN
- Brew
- Aptitude
- others ?

**Comment by bradleyjeck** [comment]
My sense is that there is a lot of personal preference wrapped up in which environments people are interested in calling Epanet from and in which package manager / software archive people like to use. 

With different requirements for each environment and distribution channel, the work of supporting either is best done by someone who is passionate -- or who makes the request :-) The nice part about an open approach is that no-one is blocked from doing just this.

In terms of what to include with a new release, my suggestion is to include bindings that can call the dll/so created from the build without further compilation.  This happens not to be the case with R or Matlab, but I think is possible with Python. When further compilation is needed, the resulting artifact ends up getting managed separately.

**Comment by bemcdonnell** [comment]
@samhatchett et al., just to get this info shared - on the PySWMM / SWMM side we have already created a page for OpenWaterAnalytics for Anaconda: https://anaconda.org/OpenWaterAnalytics 

We will soon have SWMM packages up there. We can add admins to the group as needed.

**Comment by eldemet** [comment]
Hi @samhatchett , we will update the `EPANET-MATLAB Toolkit` wrappers to be in-line with 2.2. Let me know if we need anything else.

**Comment by bradleyjeck** [comment]
Finally managed to get out on R package for calling Epanet v2.1.  It's not yet on CRAN but you can find it here:   https://github.com/bradleyjeck/epanet2toolkit

**Comment by sm-rana** [comment]
Paulo,

You dream finally has come true!

**Comment by eladsal** [comment]
@samhatchett how do you suggest to handle this?

**Comment by karwanali** [comment]
Pressure-driven model is included in version v2.2 ?

**Comment by samhatchett** [comment]
PDD is included in 2.2: https://github.com/OpenWaterAnalytics/EPANET/blob/dev/ReleaseNotes2_2.md#pressure-dependent-demands

**Comment by karwanali** [comment]
Thank you samhtchett, that is very good.
Before releasing I just would like to test it on various case studies, and see the performance of PDD model, and compare the results on some real monitoring data. And, then report the feedback for the developers here. So, please where are the source codes and files of this new version of  Epanet. Thanks in advance

**Comment by samhatchett** [comment]
@karwanali all latest testable code is on the `dev` branch. thanks!

**Comment by samhatchett** [comment]
Seems that since we've evolved somewhat in the intervening timeframe, the question of bindings is perhaps out-of-scope for this project repo. I vote to close. Anyone disagree?
