### ISSUE TITLE
Standardizing executable/library names across OS + FMT03 definition

### ISSUE THREAD

**Issue by eldemet** [OpenWaterAnalytics/EPANET#109]
The is a mismatch between the filename of the executable produced by the compilers provided and the text in string FMT03. Also the optional binary output file option is missing.

`#define FMT03  "\n Correct syntax is:\n epanet <input file> <output file>\n"`

- The executable `epanet.exe` is not the output of a compiler; in fact, the Windows compiler creates `epanet2.exe` whereas the Linux and OSX create `runepanet`. What's more, it was `epanet2d.exe` in the "EPANET 2.00.12 Users Manual"
- The optional binary output file is missing from FMT03, and it should be provided as an option.

Linked issue: 
- Their compiled libraries also have different names for Windows, Linux and OSX 

For consistency, I suggest we decide on a common name for all executables and libraries across OS:
- `epanet2.exe` / `epanet2` for executables
- `epanet2.dll` / `epanet2.so` for libraries

**Comment by eladsal** [comment]
I'm fine with the `epanet2` suggestion.

**Comment by samhatchett** [comment]
the changes in 728ebfc860bf53761b06ccb86ab5b70610502799 modify output to reflect whatever the executable name is, even if the user changes it. However as for setting a standard output from building, I would vote for "epanet" as the library name, and "epanet" as the command-line executable name. So:

- max/*nix: (`libepanet.so[.dylib]`  and `epanet`)
- windows (`epanet.dll` and `epanet.exe`)

**Comment by eladsal** [comment]
Since @LRossman mentioned this issue in #245 I'll add that the old win script builds the EPANET executable with the DLL linked in it while the new one, which is based on CMake doesn't. I prefer the old option but others may not. I think we can have them both.

@eldemet would you like to pursue this issue or we can close it\move it to 2.3?
