### ISSUE TITLE
Changes to curves with ENsetcurvevalue have no effect

### ISSUE THREAD

**Issue by FukunagaDouglas** [OpenWaterAnalytics/EPANET#111]
The answers before and after the changes are identical. 

Private Sub Form_Load()
Debug.Print "*************"
Debug.Print "START"
Dim myFile1, myFile2, myFile3 As String
Dim My_no_id As String * 32
Dim N_nodes As Long
myFile1 = App.Path & "\Net1.inp"
myFile2 = App.Path & "\Net1.rpt"
myFile3 = App.Path & "\Net1.out"
FileR = App.Path & "\Net1R.inp"
i = ENopen(myFile1, myFile2, myFile3)
ENgetcount EN_NODECOUNT, N_nodes 
Debug.Print "PRESSURES FOR OLD VALUES OF FLOW AND HEAD"
ENsolveH
For i2 = 1 To N_nodes 
ENgetnodevalue i2, EN_PRESSURE, pressur 
ENgetnodeid i2, My_no_id
Debug.Print "Node " & My_no_id & " p = " & pressur
Next i2
i = ENgetcurveindex("1", v) ' v=1
i = ENgetcurvelen(v, N) 'N=1
For T = 1 To N
i = ENgetcurvevalue(v, T, xx, yy) 'xx=1500 and yy=250
Debug.Print "Old value Flow -- Head "; xx; yy
i = ENsetcurvevalue(v, T, xx, yy + 50)
i = ENgetcurvevalue(v, T, xx, yy) 'xx=1501 and yy=251
Debug.Print "New Value Flow -- Head "; xx; yy
Next T
ENsolveH
ENsaveinpfile FileR 'Save file with changes Its OK
Debug.Print "PRESSURES FOR NEW VALUES OF FLOW AND HEAD"
For i2 = 1 To N_nodes 
ENgetnodevalue i2, EN_PRESSURE, pressur 'idX_nos(i2), EN_PRESSURE, pressur
ENgetnodeid i2, My_no_id
Debug.Print "Node " & My_no_id & " p = " & pressur
Next i2
ENclose
Debug.Print "*************"
Debug.Print "END"
End Sub

**Comment by eladsal** [comment]
This is not a VB6 issue. Pump curves are processed only when the INP file is opened and read. Further changes to the curves have no effect.

**Comment by FukunagaDouglas** [comment]
If using matlab will also have the same problem?

**Comment by eladsal** [comment]
Yes, same in Matlab.

Currently the only way I see to work around it is to:

1.  make the change to the curves
2. save to INP using `ENsaveinpfile`
3. close using `ENclose`
4. re-open the saved INP file

Hope this helps.

**Comment by Mariosmsk** [comment]
[Examples-Matlab](http://htmlpreview.github.io/?https://github.com/OpenWaterAnalytics/EPANET-Matlab-Toolkit/blob/dev-2.1_glnx/examples/html/changesToCurves.html)

[EPANET-Matlab-Toolkit (pre-release)](https://github.com/OpenWaterAnalytics/EPANET-Matlab-Toolkit/tree/dev-2.1_glnx)

**Comment by eladsal** [comment]
@Mariosmsk correct me if I'm wrong but doesn't the `getComputedTimeSeries` function actually saves the data to an INP file and then reloads it?

**Comment by Mariosmsk** [comment]
@eladsal yes and call ENepanet to create bin file.

**Comment by FukunagaDouglas** [comment]
Hi @Mariosmsk, I'm initiating the use of Epanet together Matlab 2014a, to run the example
  % Example 1
D = epanet ('Net1.inp'); ....
..
For example it is in the folder C: \ Users \ Douglas \ Documents \ MATLAB
In this folder are Net1.inp and Example1.m
The question is which files are necessary in this folder?
In this folder are also all downloaded github files EPANET-Matlab-Toolkit-dev-2.1_glnx.zip
Because every time I run the example gives the following error:
.
Error in Example1 (line 2)
d = epanet('Net1.inp');
.
thanks for your attention

Douglas

**Comment by Mariosmsk** [comment]
Hi @FukunagaDouglas, here you can find a video: [how to use EMT](https://www.youtube.com/watch?v=7fQTeZ0mH8Q).

Necessary files: (windows: *32bit* or *64bit*) or linux: *glnx* folder, epanet.m, input file (e.g.*Net1.inp*).
