### ISSUE TITLE
Initiate pull request to upstream remote

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/EPANET#114]
The purpose of this issue is to give the community an opportunity to comment on a proposal to ~transfer~ open a pull request between OWA/EPANET ~code to~ and the upstream USEPA remote. If any contributor has opinions, one way or the other, please consider this a solicitation for them. No code will be ~transferred~ pulled unless a consensus is reached. 

At this time, I think it is important for us to demonstrate what cooperation means. Thanks for considering my request.

**Comment by eladsal** [comment]
@michaeltryby what do you mean by "transfer"? My understanding of the word "transfer" is to move something from one place to another. Is your intention to fork the code or move it from here to another repository (thus removing it from OWA)?

**Comment by jamesuber** [comment]
"I think it is important for us to demonstrate what cooperation means." 

I probably have not been paying too much attention to the action going on here, and missed something. Whom is supposed to be demonstrating to whom, and why is this important?

**Comment by michaeltryby** [comment]
@eladsal no I am not proposing removing anything from OWA. The OWA and US EPA repositories are linked with one another. The US EPA is the "upstream" repository because OWA was originally forked from it. I am proposing a pull request between the OWA and US EPA repositories. I would then use OWA code in the EPANET release I am preparing. Does that make more sense?

**Comment by jamesuber** [comment]
Ah. You want OWA to issue a pull request so that code base can then be merged upstream. That's a lot clearer ;-)

**Comment by michaeltryby** [comment]
The title of this issue is "Initiate pull request to upstream remote".

**Comment by jamesuber** [comment]
Ok but... well I'll just have to blame Elad I guess.

**Comment by eladsal** [comment]
@jamesuber I'm always willing to take the blame...

@michaeltryby thanks for the clarification. I think that this was exactly our intention long time ago but I'll speak for myself. I'd be happy to see the new EPANET user interface use the OWA engine. Also would be great if the EPA's EPANET page would link to the OWA Toolkit release and the user forum.
