### ISSUE TITLE
"Progressive" hydraulic and water quality steps

### ISSUE THREAD

**Issue by samhatchett** [OpenWaterAnalytics/EPANET#12]
This feature enables API users to use `runH` and `runQ` in a stepwise fashion. It is mostly implemented as of 434d78c6ed8b5e4a95380e634798406188ef48e9 with modifications and fixes since then.

The feature should be tested and documented before rolling into a release, so I'm targeting this for v2.1

**Comment by samhatchett** [comment]
bumping this from 2.1 since it seems to introduce discrepancies w/r/t/ old simulation results.

**Comment by samhatchett** [comment]
perhaps this feature is fine for inclusion in 2.1 -- i ran a Net3 hyd/wq simulation and ran a diff on the hex dump of the binary results files from both the 2.00.12 and the 2.1 version at 7dfd7f748d8ff2e24163c0f7a28325667614152e and the files are exactly the same except for the version number in the header section, as expected. we should probably test this more thoroughly though.

**Comment by eladsal** [comment]
I think Net 3 is source tracing and not 'real' quality.

**Comment by samhatchett** [comment]
good point - what networks / quality settings should we use to standardize the regression testing?

**Comment by eladsal** [comment]
I think I tested with net 1.

**Comment by michaeltryby** [comment]
If we chose to include progressive stepping we should develop an example for testing and for demo/training. Also changes to toolkit API means we should update toolkit help files. Make sense?

**Comment by eladsal** [comment]
@michaeltryby Makes a lot of sense. We started a [documentation issue](https://github.com/OpenWaterAnalytics/EPANET/issues/24), maybe you know if there is an editable version of the help file?

**Comment by eladsal** [comment]
I have tested again Net1 and Ne2 with the 2.0.12 Toolkit and the latest 2.1 version. Tested with *ENepanet* function.
The report files are here:
[Net1 2.0.12](https://github.com/eladsal/MyGitHubFiles/blob/master/out1-12.txt)
[Net1 2.1](https://github.com/eladsal/MyGitHubFiles/blob/master/out1-21.txt)
[Net2 2.0.12](https://github.com/eladsal/MyGitHubFiles/blob/master/out2-12.txt)
[Net2 2.1](https://github.com/eladsal/MyGitHubFiles/blob/master/out2-21.txt)
I don't see differences in the quality results. In net 2  there are some, very small, numerical differences. Maybe it's the size of floats?

**Comment by michaeltryby** [comment]
@samhatchett and @eladsal So I guess the issue here is that progressive stepping hasn't undergone thorough testing? 

We could make it an option in the CLE and run the entire test-suite using it and then look for any differences. How does that sound?

**Comment by michaeltryby** [comment]
@samhatchett and @eladsal I dug into this a little deeper and I have discovered that while the hydraulics and water quality progress concurrently, the report and binary output file writing capabilities are not functioning.

**Comment by michaeltryby** [comment]
@samhatchett and @eladsal how are the various save flags supposed to be set for this feature to work?

**Comment by samhatchett** [comment]
I suppose the answer depends on what you mean by "work" - the toolkit produces results (accessible via the API getters) - but I don't know the status of writing report and binary results files. Really the purpose of the "Progressive" feature was to avoid those considerations altogether.

**Comment by michaeltryby** [comment]
There is discussion of this thread about comparing report and binary files. What is that about then?

**Comment by michaeltryby** [comment]
So this feature as it was envisioned breaks report and binary files.

**Comment by samhatchett** [comment]
No @michaeltryby - this feature, as envisioned, ignores them. The fact that they are produced at all is perhaps convenient for testing purposes. Using this feature in concert with save flags is an edge case that we've not really explored yet (to your question).

**Comment by michaeltryby** [comment]
Well then I guess this feature, isn't fully baked then.

**Comment by LRossman** [comment]
Since I'm re-coding the water quality module to address the mass balance error issue #160 I was plannng to include the "progressive" (needs a better name - maybe synchronous) option as part of that work. I will try to make it produce results the same as the sequential option.

One reason results might differ (very slightly) in the current code is that when the sequential option reads a flow off of the hydraulic results file for a CLOSED link that flow was saved to the file as 0 but with the synchronous method it will have some non-zero value.

**Comment by michaeltryby** [comment]
Concurrent might be a better name.
