### ISSUE TITLE
ENgetcurve is returning wrong values?

### ISSUE THREAD

**Issue by eladsal** [OpenWaterAnalytics/EPANET#124]
I have been working on the set-units branch and looking at curve related functions when I came across the ENgetcurve function and noticed that for some strange reason the returned values are multiplied by [wrong conversion factors](https://github.com/OpenWaterAnalytics/EPANET/blob/dev/src/epanet.c#L1495) 
```
    double x = curve.X[iPoint] * Ucf[LENGTH];
    double y = curve.Y[iPoint] * Ucf[VOLUME];
```
Actually, curve data is not converted at all when it is read from the INP file and should not be converted back. Since I'm not using this function (VB does not support good arrays in C APIs) can someone please confirm that this is a bug? The fix should be simple:
 ```
    double x = curve.X[iPoint];
    double y = curve.Y[iPoint];
```

I hope I'm not missing something here...

**Comment by samhatchett** [comment]
that was my commit: https://github.com/OpenWaterAnalytics/EPANET/commit/566eb53eb44a7b3458eead2d695972a154febc25

... and i think you are right. your version is consistent with the dox: 
https://github.com/OpenWaterAnalytics/EPANET/commit/2b0b2d17c3187775aa50fc33a9138d108d607609

Especially:

> PLEASE NOTE: x/y data returned will be in EPANET's native units, not the units specified by the project. This is a known issue related to the library not keeping track of the curve type (head, efficiency, volume, ...)

**Comment by eladsal** [comment]
So this was already fixed on the feature-wrapper branch and would make it's way into dev. Thanks!
