### ISSUE TITLE
Compiling EPANET as an R extension 

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/EPANET#130]
@bradleyjeck Proposes making modifications to EPANET so that it can be compiled as a C language extension to R. I am creating this issue so that we can track discussion on this topic.

**Comment by michaeltryby** [comment]
@samhatchett Brad's pull requests are currently being made against the master branch. His proposed changes are pretty minor, but as a general rule we don't develop in the master branch. Can we make a feature branch for him to develop in and pull against?

**Comment by eladsal** [comment]
@bradleyjeck just that I understand the issue. If we make these small changes would you be able to use one of the compiled dlls we currently have in our builds or you would need to recompile it differently?

**Comment by michaeltryby** [comment]
Here is a link to some information on [R-exts](https://cran.r-project.org/doc/manuals/r-release/R-exts.html)

**Comment by bradleyjeck** [comment]
Hi @michaeltryby  - 

My aim here was not to propose any new features, but rather to contribute back the modifications made to files in this repo.  The modifications already exist in the 'epanet2toolkit' package for R, available on [CRAN](https://cran.r-project.org/package=epanet2toolkit) and [github](https://github.com/bradleyjeck/epanet2toolkit).  The package includes the epanet sources so pull requests #126 #127 #128 are an effort to contribute the edits upstream. 

Regarding branches, I'm happy to send the PRs to whichever branch the maintainers prefer.

**Comment by bradleyjeck** [comment]
Hi @eladsal - The R package needs to compile from source and thus won't use any dlls from the existing builds.  I see a few reasons for considering the admittedly quite small changes in PRs #126, #127, and #128:
- improving the build by generating fewer warnings; and,
- avoiding drift between the code here and in the R package. 

For the R package to be distributed on CRAN (which it is), it has to meet the requirements set out in the link Michael posted above. Among those requirements are that the package compiles from source and that an evolving list of checks on compiled code are satisfied.  Thus the R package contains a copy of the epanet sources.  Changes to the source were minimized but some were necessary to pass the checks.  I've sent the changes required to pass R's package checks as pull requests to this upstream repo.

**Comment by michaeltryby** [comment]
@bradleyjeck Thanks for the additional information. Is this "R package check" that you speak of automated by any chance? 

My thought is that we could easily accept your changes, but in the course of future development we may inadvertently break compatibility with R. So we - the project - should agree that compatibility with R is a "feature" that we want to maintain, accept your changes, and then if possible setup a test to make sure it remains compatible.

**Comment by bradleyjeck** [comment]
yes, the checks are automated through a  routine "R CMD check". However, R CMD check operates on an R package and not a C library. So to confirm compatibility you'll need to create an R package and test it.  Probably the easiest way to do that is forking the existing package and updating the relevant source files.  Seems like a lot of work to automate, tbh.     My suggestion would be doing it manually, or asking your friendly R package maintainer to do it when a new epanet release is approaching :)     Anyway, I think it's unlikely that new well written C code will cause major issues on the R side.  One reason it was feasible to make an R package in the first place is that the number of changes to existing epanet source files was very small.

**Comment by eladsal** [comment]
@bradleyjeck I have created the R-compile branch out of dev which is our development branch. You can make PR to this new branch.

Thanks!
