### ISSUE TITLE
ENsetreport not working well on feature-wrapper

### ISSUE THREAD

**Issue by eladsal** [OpenWaterAnalytics/EPANET#137]
Some settings are not being saved using `ENsetreport` on `feature-wrapper`. For example:
```
ENsetreport("STATUS YES")
ENsetreport("NODES  ALL")
```

**Comment by michaeltryby** [comment]
@eladsal No changes were made to EPANET in the `feature-nrtest` branch. Therefore, I think a better place for this issue is its parent branch `dev-net-builder`. Thanks!

**Comment by eladsal** [comment]
@michaeltryby my mistake. I was referring to the `feature-wrapper` branch which is, to my understanding, the parent branch of `feature-nrtest`. I will update the title and original post.
