### ISSUE TITLE
document changes in 2.1

### ISSUE THREAD

**Issue by samhatchett** [OpenWaterAnalytics/EPANET#14]
need to document the bugs addressed:

- [ ] tank diameter bug ac272cfece3a383fbb10ff53348419f143fc22cc
- [ ] Lew's bug fixes (need to enumerate)
- [ ] Rulestep getter e732508b5601d98da9b4ca0d8c1d096370f9a9b2
- [ ] Pump index getter f3052ac873bf0931eb3fe399b5220134c3e31adf
- [ ] Link pattern getter 3b5feb75b272cdb7018b9d64e408d94659685995
- [ ] Time step truncation 242c03f579cad5a4b3e20d4049c542f2d25b6ce8
- [ ] get node value break/return bug: 5abc3875fa3423100345045001745594f3ad7c53
- [ ] getcurve function 566eb53eb44a7b3458eead2d695972a154febc25
- [ ] getstatistic f8e843d584021071d5230f31cc08bb2a1237d690
- [ ] save output memory leak: b09492b7e2f50a4892e93e0d5858f6f1f264089f
- [ ] get head curve, pump type: d1b02129dc42c9b143ab5f2fd19f152f0e79df09
- [ ] minor loss for pipes: 017e24be1c5745fdb5d300e921df82b60ba25551
- [ ] ENgetnumdemands
- [ ] ENgetbasedemand
- [ ] ENgetdemandpattern
- [ ] ENsetbasedemand
- [ ] ENsetqualtype
- [ ] ENgetqualinfo
- [ ] ENgetcoord (not sure it's working)
- [ ] ENgetcurve (not supported for VBA yet)
- [ ] New hash table implementation: caa794447cb4
- [ ] Ability to build toolkit for `float` or `double` precision

**Comment by eladsal** [comment]
Also:
ENgetnumdemands
ENgetbasedemand
ENgetdemandpattern
ENsetbasedemand

ENsetqualtype
ENgetqualinfo

ENgetcoord (not sure it's working)
ENgetcurve (not supported for VBA yet)

**Comment by eldemet** [comment]
Perhaps for the 2.0.13 version we should limit the number of new functions to add? In any case, according to the Semantic Versioning scheme (http://semver.org/):
Patch version Z (x.y.Z | x > 0) MUST be incremented if only backwards compatible bug fixes are introduced. A bug fix is defined as an internal change that fixes incorrect behavior. 

What do you think?

**Comment by eladsal** [comment]
I have used most of these functions and they seem to work well. Still need to make sure they have the regular checks (like fileopen and so on)

**Comment by samhatchett** [comment]
ok, so according to semver, we should be calling this 2.1 - since there are backwards-compatible API changes, in addition to bug fixes.

````Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards compatible functionality is introduced to the public API. It MUST be incremented if any public API functionality is marked as deprecated. It MAY be incremented if substantial new functionality or improvements are introduced within the private code. It MAY include patch level changes. Patch version MUST be reset to 0 when minor version is incremented.````

**Comment by eldemet** [comment]
Yes, I think you are right. @samhatchett, @eladsal  what  would make more sense to you? keep only the bug-fixes for 2.0.13 (i.e. do not include ENgetcurve,  ENgetcoord etc) and move these functions for version 2.1.0, or to skip 2.0.13 anyway and go for 2.1.0 directly (keeping the most tried&tested functions in the code)?

**Comment by samhatchett** [comment]
picking up on this thread - suggest we call it 2.1 and include the new api functions, but don't include the "stepwise" hyd/wq simulation usage mode, since that seems to be introducing discrepancies w/r/t/ old simulations.

**Comment by eladsal** [comment]
Yes, I'm for it.

**Comment by eldemet** [comment]
Ok Sam I agree as well

**Comment by samhatchett** [comment]
i think all these items are documented in basic form in the 2.1 Changes document. We can re-open this issue if anyone feels strongly otherwise.
