### ISSUE TITLE
Configure appveyor for Windows build and regression testing

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/EPANET#141]
I wanted to configure appveyor so we can have a CI building and testing on a server running Windows. We can use it to help get the build passing (see #129). Sound good? 

Do you have a preference what branch I use to do this work? Should be fairly straight forward.

**Comment by eladsal** [comment]
Two options: `dev` or `feature-wrapper`. The latest talk we had was to work on `feature-wrapper` and merge it to `dev` so I would vote `feature-wrapper`.

**Comment by michaeltryby** [comment]
@samhatchett any preferences on this?

**Comment by samhatchett** [comment]
i'd like to get `feature-wrapper` merged into `dev` (aka, #136 ) first - it's a huge PR, and likely to break stuff. any discussion about that?

**Comment by michaeltryby** [comment]
@samhatchett we can fix it before or after the merge. Makes no difference.

**Comment by samhatchett** [comment]
this is still broken?? https://ci.appveyor.com/project/OpenWaterAnalytics/epanet

**Comment by michaeltryby** [comment]
This was fixed yesterday PR #145. Thanks @bemcdonnell!
