### ISSUE TITLE
Generate test coverage metrics using Coveralls/Codecov

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/EPANET#148]
I wonder how much of EPANET actually gets tested when the regression test suite runs?  

Now that we have `nrtest` running under CI, a useful next step would be to configure Coveralls/Codecov and generate test coverage metrics.

**Comment by michaeltryby** [comment]
I propose we re-purpose the Travis worker to run tests and generate coverage. Let me know if this presents a problem for you so we can work something out. :smile:

Background: 
I am working on getting a coverage metric computed for our testing system. A branch `dev-coverage` has been created that builds the epanet library in debug configuration using gcc linked with lcov to generate coverage data when tests are run. I would like to use the Travis worker to get Coveralls up and running.

**Comment by LRossman** [comment]
Why are you asking if it would present a problem? What potential problems could it pose?

**Comment by michaeltryby** [comment]
@LRossman I am trying to be polite and communicative. Just giving a shout out in case someone is relying on the Travis build for some reason that I'm not aware of. 

I don't anticipate any problems except low test coverage numbers! :smile:

**Comment by LRossman** [comment]
OK, go for it. Regarding the engine itself, the amount of code coverage will directly depend on what's in the test problems it gets fed (duh...). We could probably get the same info as the coverage stats provide by filling in a table with network features (head loss formula, valve type, pump curve type, etc.) as columns and test problems as rows.

**Comment by michaeltryby** [comment]
@LRossman That's true, but this way the computer does the work and everyone can see the results.

**Comment by michaeltryby** [comment]
Coverage is running at 60% running only unit tests Once regression tests are running coverage is likely to go up. So we are in pretty good shape!
