### ISSUE TITLE
build files for 2.1

### ISSUE THREAD

**Issue by samhatchett** [OpenWaterAnalytics/EPANET#15]
need:

- [x] CMake file
- [x] Xcode
- [ ] MSVS solution file ?
- [x] windows compilation batch script ?

**Comment by eladsal** [comment]
win compilation script done here https://github.com/OpenWaterAnalytics/EPANET/commit/2c81796f7166bf56f12c9dd5fa7dede300f38754

**Comment by samhatchett** [comment]
really cool!

**Comment by willfurnass** [comment]
Current `CMakeLists.txt` didn't work for me on Linux so created pull request #20

**Comment by eladsal** [comment]
I think that we would need to build DLLs and EXEs for the different platforms:
* Windows
* Mac
* Linux

Also 32 and 64 bits versions. We can consider two EXE versions: standalone and\or linked to the DLL (the current EPA's version is standalone).

The long term goal is to have one script (CMake) which would build all versions. For 2.1 I think we can have the separate scripts. When we tag the version a zip file with the different versions caould be attached for download.

**Comment by samhatchett** [comment]
this is handled. anything not already existing can be built through CMake
