### ISSUE TITLE
ENopen -> ENsaveinpfile reverses per-junction categories listed in [DEMANDS]

### ISSUE THREAD

**Issue by samhatchett** [OpenWaterAnalytics/EPANET#150]
Load a model file (which has at least one junction with two demand categories). Save it using ENsaveinpfile. The demand categories for multi-category junctions will be reversed in order, compared to the original file. Repeated parsing/saving will reverse the order again.

This appears to be caused by the difference between how the categories are parsed (Demand linked-list is prepended with successive categories) and how they are written back to the inp file (list is simply traversed in sequence). 

Why is this a problem? Because like it or not, the inp file format is eminently hackable - and in so hacking, it is useful to have a method of "normalizing" the format for (i.e.) text-based version control. One would expect that an arbitrary number of open/save operations would be essentially a no-op.

Possible fixes:
- reverse the order of serialization by functional recursion of the linked-list traversal
- modify how the linked-list is constructed (change to appending instead of prepending)

**Comment by eladsal** [comment]
Any of these fixes can just be done upon writing the INP file?

**Comment by jamesuber** [comment]
Certainly the first could be, yes.

**Comment by eladsal** [comment]
Please test b85aff9. Thank you!
