### ISSUE TITLE
Post EPANET build instructions

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/EPANET#168]
PR #166 changes the procedure to run reg testing locally. I have updated the instructions I wrote for building EPANET on Windows and would like to post them. Where should they be posted? Preferences?

**Comment by samhatchett** [comment]
!! I've been meaning to post about this

We need a very basic "getting started" section near the top of README - with blocks of text one could essentially copy-paste to get the build tools, clone the code, build it, and run the tests and executable. Probably need two sections separated by platform.

more in-depth instructions could be another page, linked in the README in a friendly way that will be picked up in Doxygen.

how does this sound?

**Comment by eladsal** [comment]
For a long time we have been using the instructions by @eldemet [here](https://eldemet.wordpress.com/2014/07/04/how-to-compile-epanet-on-64-bit-windows-matlab/). Actually what is needed is just the Microsoft Windows SDK 7.1 and then the [batch](https://github.com/OpenWaterAnalytics/EPANET/blob/dev/win_build/WinSDK/Makefile.bat) file we have in the repo will create the DLLs and EXEs (32 and 64 bits) with a single click. I understand that we want to move to a single make file but it should be made simple.

**Comment by michaeltryby** [comment]
So what you like about the existing batch file is that it has one dependency (win sdk 7) and you can build with one click? And my instructions were too complicated?

**Comment by eladsal** [comment]
Basically yes. However, I do understand the request for a single build script for all platforms (as CMake) even if it means a more complex set of instructions.

**Comment by michaeltryby** [comment]
Thanks Elad! That is good feed back. I will see what I can do about simplifying the number of dependencies and reducing the number of steps in the build process.
