### ISSUE TITLE
Version number is hard coded in output messages

### ISSUE THREAD

**Issue by eladsal** [OpenWaterAnalytics/EPANET#17]
Need to be handled before release.
https://github.com/OpenWaterAnalytics/EPANET/blob/master/src/text.h#L335

**Comment by eldemet** [comment]
at the 0.13 milestone perhaps we can change it manually, but at a later stage i suppose we can make it update automatically. Would that be ok at this stage?

**Comment by samhatchett** [comment]
probably related to #27

**Comment by eladsal** [comment]
We may also update the versions of changed file like [epanet.c](https://github.com/OpenWaterAnalytics/EPANET/blob/87a8aaaef8d8a78c4e8beaf510a6a36950fdf61a/src/epanet.c#L14)

**Comment by samhatchett** [comment]
i would vote to eventually remove "date and version" information from the code files, and consolidate important info like that, along with a summary of new features and fixes in a CHANGELOG. information about what files have changed, when, by whom, and to what extent is all handled by git versioning so we no longer need to use comments to track modifications.

**Comment by eladsal** [comment]
Good idea!
