### ISSUE TITLE
New pipes are added with initial status set to CLOSED

### ISSUE THREAD

**Issue by eladsal** [OpenWaterAnalytics/EPANET#173]
In [`EN_addlink`](https://github.com/OpenWaterAnalytics/EPANET/blob/dev/src/epanet.c#L4349) new pipes are added with initial status set to CLOSED and CVs set to OPEN.

I think both are should be OPEN as this is the most common case.

Thoughts?

**Comment by samhatchett** [comment]
👍 agree. What is the default status on pumps? I remember having some discussion about what the expectation is - like when you create a steady-state model, you would expect adding a pump to mean "adding a pump that is turned on"?

**Comment by eladsal** [comment]
Currently, apart from CV all new links are assigned a CLOSED initial status
https://github.com/OpenWaterAnalytics/EPANET/blob/dev/src/epanet.c#L4345

**Comment by eladsal** [comment]
Long overdue... so the change would be to mimic the logic of the EPANET GUI when adding links. Status is `OPEN` for pumps\pipes\CV and `ACTIVE` for valves.
