### ISSUE TITLE
Not save zero demands and reference to the default pattern for each junction?

### ISSUE THREAD

**Issue by eladsal** [OpenWaterAnalytics/EPANET#174]
Currently junctions with zero demand values are also saved into the `[DEMANDS]` section. This does not add any new information and makes the INP file larger. The GUI does not do that. I suggest not to save these zero demands.

All junctions without a demand pattern are set to follow the default pattern (if exists). When saved, all these junctions are saved with the default pattern which makes this setting redundant. I suggest not to save the pattern ID for junctions which follow the default one.

Thoughts?

**Comment by eladsal** [comment]
OK, plan to move on this one...

**Comment by eladsal** [comment]
Moving this to v2.3

**Comment by LRossman** [comment]
This issue has been addressed by PR #702 and can be closed.
