### ISSUE TITLE
epanet-matlab linking

### ISSUE THREAD

**Issue by jnaaaaaaaaa** [OpenWaterAnalytics/EPANET#175]
I want to link epanetto matlab. I use epanet-matlab toolkit.  but i cant.
when i use matlab2010 64 bit...it says "Microsoft Visual C++ 2005 or 2008 is
required to use this feature." while various version of them are installed in my laptop.
when I use matlab 2010 32 bit. the epanet can be loaded successfully, but my matlab software will be stopped to work and it will be closed.
Also, epanet version 2.0.1 is installed in my laptop.
please help me

**Comment by shenh** [comment]
If you are using the dll installed by the EPANET installer, it is 32 bit (version 2.00.12). You can only use 32 bit EPANET dll with 32 bit matlab, or 64 bit EPANET dll with 64 bit matlab. When you use 32 bit matlab, can you provide more details when matlab is closed, simply after loading the dll? Is there any error message in the matlab command window?

**Comment by jnaaaaaaaaa** [comment]
I used both matlab and EPANET 32 bit. after the message "EPANET loaded successfully" matlab stopped to work and closed.

**Comment by eldemet** [comment]
This can happen when the previous version was not unloaded. Also, it is not clear what version of the EPANET-MATLAB toolkit you are using. Could you please provide some more information?
