### ISSUE TITLE
EPANET Engine Architecture Discussion - PLEASE RSVP IN ISSUE

### ISSUE THREAD

**Issue by jamesuber** [OpenWaterAnalytics/EPANET#180]
**When**: Monday, June 4, 9:00-Noon US Central Daylight Time
**Location**: Minneapolis Central Library; 300 Nicollet Mall, Minneapolis, MN 55401; Mark E. Johnson Conference Room N-202
**Remote Attendance**: 
https://global.gotomeeting.com/join/520915069 
You can also dial in using your phone. United States: +1 (786) 535-3211 
Access Code: 520-915-069 
**RSVP**: Yes, please indicate your plan to attend by either liking this or posting a response.

This is being held during the EWRI congress because some folks will be in attendance, but remote attendance would be great. The time is during the EWRI keynote Panel Discussion on "Learning and Planning for Resiliency in the Aftermath of the 2017 Extreme Weather Events". No disrespect to the panel (Morris Maslia among them), but this looks to be the best time for folks at the conference as well as in other time zones.

Just getting this on everyone's calendar. We will jointly formulate an agenda and goals, etc, over the next 1.5 weeks - here. But - this is a first meeting. Hopefully, this leads to some degree of consensus or clarity on software architecture goals, and maybe even software architecture, but it's also possible it just leads to an open and honest airing of wishes and desires. That would be OK too. We'll just have to continue the process.

**Comment by jamesuber** [comment]
Lew Rossman, who authored the current "Epanet 3" C++ code, has recently put together notes on design of that code base. I'm attaching his document titled "A Proposed Design for EPANET 3." I'm assuming that it is acceptable to do so, as this document was recently distributed to folks on the EWRI "EPANET Visioning Task Committee". 

The reason for distributing this here is that it can serve as a reaction point for our software architecture discussions at EWRI. 

I want to emphasize that these are Lew's thoughts alone, and we should thank him for putting in this effort! But, being Lew's thoughts, they do not reflect the community needs or wishes, until fully vetted, modified, thrown out and rewritten, etc... and then approved. And I am sure there will be (and should be) a variety of opinions, and that Lew will be good natured enough to encourage and participate in a useful critical debate.

[Proposed Design for EPANET 3 - 1st Draft-LAR.docx](https://github.com/OpenWaterAnalytics/EPANET/files/2035664/Proposed.Design.for.EPANET.3.-.1st.Draft-LAR.docx)

**Comment by jamesuber** [comment]
Note to those who read this already - time has been shifted forward 1.5 hours due to meeting room availability.

**Comment by michaeltryby** [comment]
Unfortunately, I'm not arriving in Minneapolis until Tuesday. As such I send my regrets. 

@LRossman your proposed design looks good!

**Comment by michaeltryby** [comment]
@jamesuber BTW Thanks for organizing this!

**Comment by eladsal** [comment]
Will not be in Minneapolis but will try to connect. Thanks.

**Comment by wgrayman** [comment]
Lew's document are his thoughts on EPANET 3.0 and was initially distributed to current members of the EWRI EPANET Visioning task committee. It is certainly fine and beneficial to distribute it via this GITHUB site.  If you would like to join this task committee please feel free to email me at wgrayman@gmail.com. EWRI task committees are open to both EWRI members and non members though we would certainly encourage you to become members of EWRI and to join the WDSA committee which is the parent committee to the task committee. Lew's document was meant to be a straw-man descriptor for EPANET 3 and was produced to elicit responses under the general philosophy that it provides a possible framework and focus and that it is sometimes easier to comment on an existing document.

**Comment by shenh** [comment]
Thanks Jim for organizing this. I will connect. 

Hailiang

**Comment by shenh** [comment]
Jim, just to confirm whether your original post has the updated time (1.5 hrs forward). When will it end? We may have more attendee here. Thanks

**Comment by jamesuber** [comment]
@shenh Yes I've updated the time in the original post - 9:00 AM US Central Daylight Time. Thanks for asking! We are allocating 3 hours of time till Noon. But if you can only join for part of that, it's OK.

**Comment by jamesuber** [comment]
For those who will be attending in person -- we've reserved a conference room at the Minneapolis Central Library, 300 Nicollet Mall, Minneapolis, MN 55401; Mark E. Johnson Conference Room N-202.

This location is an 8 minute bus ride straight down Nicollete Ave from the Hyatt conference center at 12th and Nicollete, to 3rd and Nicollete. Looks like there are several buses - for example #10, 17, and 18. Or, you can of course just walk the 9 blocks in about 15 minutes.

**Comment by samhatchett** [comment]
For those attending in person, I plan on getting something to eat at the nearby coffee shop (Dunn Bros Coffee) around 8am, so please feel free to join me and we can all walk over together. It’s the same address and apparently connected via a walkway. Hope to see you all there!

**Comment by dbhart** [comment]
I will also call in, I'll be flying to EWRI that afternoon

**Comment by samhatchett** [comment]
Thanks everyone for your participation and enthusiasm. I've created a new repo for our deliberations over here: https://github.com/OpenWaterAnalytics/next-net

... please "star" and "watch" that space, and let's have some good discussions. Just start typing! It will be fun.
