### ISSUE TITLE
Create a repository level project board for EPANET

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/EPANET#182]
I don't have permission to create the project board within the EPANET repo. I would like to set one up for the v2.2 Milestone as I suggested in #179.  

@samhatchett I think if you go into repo settings you can make projects visible within the EPANET repo.

**Comment by michaeltryby** [comment]
BTW @samhatchett while you are in settings can you please make "dev" the default branch as opposed to master. Sound good?

**Comment by samhatchett** [comment]
done done 👍
