### ISSUE TITLE
Porting EPANET to Windows 64 bit

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/EPANET#183]
The migration of EPANET from 32 to 64 bit on Windows is long overdue. This issue involves getting EPANET building on Visual Studio 64 bit and establishing a Windows 64 bit reg testing benchmark.  

PR #177 contains changes to EPANET to get it running on Visual Studio 15 2017. This seems like as good a choice as any. Thoughts?

**Comment by eladsal** [comment]
Just want to point out that there is still a need to maintain support for 32 bits, at least for the 2.x branch.
