### ISSUE TITLE
Build a better CMake strategy

### ISSUE THREAD

**Issue by samhatchett** [OpenWaterAnalytics/EPANET#186]
features of a better cmake strategy:

- [ ] define build type (debug/release)
- [x] choose whether to build tests
- [ ] define shared / static library
- [x] make sure we don't needlessly require boost
- [ ] v3.7.2 or higher to make it work with Visual Studio 2017
- [ ] build script (`.bat / .sh`) for single-command "simple" build

others?

**Comment by LRossman** [comment]
For static linking to the MS runtime library and to ignore warnings about unsecure library functions I think you include the following in CMakeLists:
```
if (MSVC)
    set (CMAKE_C_FLAGS "/MT")
    set (CMAKE_C_FLAGS "/D _CRT_SECURE_NO_WARNINGS")
endif (MSVC)
```
The other most important compiler switches are the optimization level and the floating point model. The defaults are Fastest Code (/O2) and Precise (/fp:precise), respectively, which is what we want for a Release build.

**Comment by bemcdonnell** [comment]
@LRossman, are these warnings coming from using `strcpy`?  I wonder if it would be worthwhile to update these functions to use `strcpy_s`.  Could provide backward support to older compilers with a macro.  I think we plan to update these in SWMM soon (although this implementation in SWMM is secure the way you implemented it, AFAIK).

**Comment by LRossman** [comment]
@bemcdonnell yes, for `strcpy`, `sscanf`, `fscanf`, `sprintf`, `fprintf`, and related functions. The safe versions of these (`strcpy_s`, etc.) were originally just available for MSVC and therefore not portable. However it appears that they have now been incorporated into the C11 standard (see [http://en.cppreference.com/w/c/string/byte/strcpy](url) , [http://en.cppreference.com/w/c/io/fscanf](url) and [http://en.cppreference.com/w/c/io/fprintf](url). Updating these functions in EPANET wouldn't be very high on my TO DO list, but others may have a different view.

**Comment by samhatchett** [comment]
@bemcdonnell and @LRossman regarding bounds checking and null termination, there is #135 for that!
