### ISSUE TITLE
Eliminate the need for two sets of API functions

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#196]
Version 2.2 has introduced a duplicate set of 96 API funtions to those in 2.1 whose only difference is a reference to a `EN_Project` struct in its argument list. This allows one to use the API in a thread safe manner when building an app with parallelization. As an example, the two forms of the function used to get a link's type are:
```
int DLLEXPORT ENgetlinktype(int index, EN_LinkType *code);
int DLLEXPORT EN_getlinktype(EN_Project *p, int index, EN_LinkType *code);
```
where the first (legacy) function was re-written to call the second function using a globally defined default project named `_defaultModel`.

However, by re-defining the first function as:
```
int  DLLEXPORT ENgetlinktype(int index, EN_LinkType *code, EN_Project *p = &_defaultModel);
```
we can eliminate the need for the extra set of EN_xxx functions (as long as we compile the code as C++ (which we currently do) and not strictly as C). Thus we can call `ENgetlinktype` by either of the following:
```
result = ENgetlinktype(myLinkIndex, &myLinkType);
result = ENgetlinktype(myLinkIndex, &myLinkType, myProject);
```
The first call uses `_defaultProject` as the project it is querying while the second uses a dynamically created project named  `myProject`.

Does anyone see an issue with this proposal and is it worth doing?

**Comment by eladsal** [comment]
I haven't tried it but would the first option work with VB\VBA calls? `EN_Project` is not something easy to pass from VBA.

**Comment by LRossman** [comment]
I'm not sure. Would adding an additional argument to the declarations in your epanet2.bas file with the keyword `OPTIONAL `in front, using a type `As Any` work?
```
Declare Function ENgetlinktype Lib "epanet2.dll" (ByVal Index As Long, Code As Long, Optional ByVal As Any) As Long
```
Another possibility would be:
```
Declare Function ENgetlinktype Lib "epanet2.dll" (ByVal Index As Long, Code As Long, Optional ByVal As Long = 0) As Long
```

**Comment by eladsal** [comment]
Both declares are missing the name of the argument for the optional argument but maybe just not using the last argument would work (without any change):
`Declare Function ENgetlinktype Lib "epanet2.dll" (ByVal Index As Long, Code As Long) As Long`
Need to check that

**Comment by michaeltryby** [comment]
Two sets of APIs are provided for backwards compatibility. We did not want to break application that rely on the old API. 

If you are bothered by duplication, I propose we deprecate the old API. 

Compiling in C++ is another issue.

**Comment by michaeltryby** [comment]
These are C style APIs. Stylistically it gets confusing to start using C++ language features in C API. Making the change you are proposing confusing to a developer trying to use it.

**Comment by michaeltryby** [comment]
@LRossman I agree that 200 API functions is a lot. How about this idea. We only provide backward compatibility for the canonical Toolkit API functions and mark them as deprecated. Then in a subsequent release we can remove them. So rather than a technical solution we simply communicate with developers using the library. I prefer this approach.

**Comment by samhatchett** [comment]
I'm not seeing how the number of API functions is a problem. Backwards compatibility is important, and then we want more methods on top. I suppose you could break the header up into more granular units (`controls.h`,`io.h`, etc...) to make it more manageable, but the toolkit really does a lot - so we need a lot of functions.

For comparison, look at [GDAL](http://gdal.org/annotated.html) - somewhere around 120 classes, each with a dozen or more specialized methods. And that library is _just_ spatial data and transformations.

**Comment by jamesuber** [comment]
I agree with @samhatchett on this. I'd prefer a complete and well designed/organized/described  first, and really don't care how about the size of the API.

**Comment by michaeltryby** [comment]
I agree. Setting backward compatibility aside, the existing API is verbose and predicated on the idea of getting/setting one value at a time. It is possible to get same functionality out of a smaller number of functions.
