### ISSUE TITLE
Fix incomplete calculation of Darcy-Weisbach head loss derivative

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#199]
As pointed out by Simpson and Elhay (J. Hyd. Engrg, 137(6), 2011), EPANET does not consider the dependence of the Darcy-Weisbach friction factor on flow rate when computing the derivative of head loss with respect to flow for the aformentioned head loss formula. This needs to be corrected.

**Comment by eladsal** [comment]
I think this is the paper @LRossman refers to:
[Simpson, Elhay - 2011 - Jacobian Matrix for Solving Water Distribution System Equations with the Darcy-Weisbach Head-Loss Model](https://github.com/OpenWaterAnalytics/EPANET/files/2124137/Simpson.Elhay.-.2011.-.Jacobian.Matrix.for.Solving.Water.Distribution.System.Equations.with.the.Darcy-Weisbach.Head-Loss.Model.pdf)

**Comment by jamesuber** [comment]
Lew,
You and I had actually worked on this in 1991. I'm posting this FORTRAN subroutine mainly because doing this correctly ended up being a pain in the _ss. It's a fairly complicated expression to start with, and then you've got absolute values of flows, with flows changing sign. At least it was hard for me to get it right the first time, so maybe this helps to avoid so much pain in the next go-round.
[dhe.txt](https://github.com/OpenWaterAnalytics/EPANET/files/2124437/dhe.txt)

**Comment by LRossman** [comment]
Thanks @jamesuber for the "blast from the past". Actually the current EPANET 2.x code does compute `df/dq `(where f = friction factor and q = flow) but it's commented out. When I first wrote it sometime in the 1990's (I can't remember exactly when) I realized it wasn't quite right and decided to ignore it. The corrrect way to do it, for both the Colebrook formula and the transition zone polynomial approximation for `f(q)` is described in the Simpson and Elhay paper. The resulting formulas are long winded but easy to implement. I have already done so in the code that's been posted to [epanet-dev](https://github.com/OpenWaterAnalytics/epanet-dev). Now it's just a mechanical matter of including them in the 2.2 code. This will break the automated testing since slightly different numerical results will be found (compared to  2.00.12) for test files that use D-W. I see this being an ongoing issue to get commits approved for any improvements or bug fixes to the code's numerical engine.

**Comment by jamesuber** [comment]
I was going to suggest refactoring in Fortran, but thought better about it. 

@samhatchett had just commented to me exactly the issue you raised regarding passing the tests.

Maybe we need to enable a super secret "but this is really the correct result, I promise" key and base our testing on that. 

It's a difficult issue that deserves discussion.

**Comment by michaeltryby** [comment]
Just to be clear, when there is justification and it is clearly understood why its being done, it is fine to update the benchmark. Like when you are fixing a bug.
