### ISSUE TITLE
Problems with the EN_NEXTEVENT Time Parameter

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#201]
When the API function `EN_gettimeparam()` is called with the _EN_NEXTEVENT_ parameter it returns the smaller of the hydraulic time step and the shortest time to drain or fill a tank. This, however, does not determine when the true next hydraulic event will occur as it ignores points in time where demands might change or when controls are activated. The companion time parameter _EN_NEXTEVENTIDX_ is used to identify which tank is the controlling one. So if the intent is to simply determine the next time interval for a tank to be full or empty then the parameters should be re-named to something like _EN_NEXTTANKEVENT_ and _EN_NEXTTANKEVENTIDX_, and not include the possibility of returning the hydraulic time step.

On the other hand, if the intent is to truly identify when the next hydraulic event occurs, then the `timestep()` function in HYDRAUL.C should be used instead of the `tanktimestep()` function. However, `timestep()` and `ruletimestep()` would have to be modified so as not to actually update tank levels when rule-based controls are evaluated since we don't want a call to` EN_gettimeparam()` to alter the state of the network.

**Comment by samhatchett** [comment]
i would vote for renaming `EN_NEXTEVENT` to `EN_NEXTTANKEVENT` as you suggest - it's less invasive and better expresses what is actually being requested.
