### ISSUE TITLE
Welcome To the OWA Dev Community

### ISSUE THREAD

**Issue by bemcdonnell** [OpenWaterAnalytics/EPANET#206]
#### ... Welcome to the OWA dev community! We're happy you're here.  

![os apps](https://user-images.githubusercontent.com/6105134/43102958-76a0135e-8e81-11e8-825a-06993d92395d.png)

**Comment by milad-ghiami** [comment]
when is it?

**Comment by milad-ghiami** [comment]
I liked to attend  :)
