### ISSUE TITLE
Add a function to get the curve type

### ISSUE THREAD

**Issue by eladsal** [OpenWaterAnalytics/EPANET#209]
Originated from a [forum discussion](http://community.wateranalytics.org/t/how-to-get-epanet-curve-type/680).

**Comment by milad-ghiami** [comment]
@eladsal  I think  must to do 

1. when we read inp file   in function [newline ](https://github.com/OpenWaterAnalytics/EPANET/blob/dev/src/input2.c#L278)  in function curvedata after add a curve check whick element use it and set curve type
2. when set curve to element too

**Comment by michaeltryby** [comment]
@eladsal Can this issue be closed?
