### ISSUE TITLE
Compile Epanet with higher accuracy in energy

### ISSUE THREAD

**Issue by rasbae** [OpenWaterAnalytics/EPANET#212]
Im am not sure that I have placed my question in the right place, but I try it here. I have created a program in VB that finds the best combination of pumps of different pumps and pumpspeed to give a certain flow in one or more pipe. I was really happy about the correction on energy calculation in Epanet for using different pumpspeeds - it helps in my calculations - so your work is much appreciated😊 
In my calculations I can see that the accuracy of the energy needs 3 digits to be able to point out a more specific best energy use. Or else I will get several similar solutions. Of course it depends on the pump curve and the energy curve, but in theory I think I will need 3 digits in energy instead of only two in the present Epanet solution. I have looked into the Epanet code and I think I have found the place to correct it, but I really have a problem compiling the C-code. I must admit that I am not much familiar with coding and compiling C-code, but I have tried 3 different ways to compile it from the “build”-directory: Cmake, MinGw and WinSDK. In all three solutions it seems like that I had to work with a lot of different settings in the programs and the WinSDK I never made to work because it crashed some of my other programs and I had to reinstall my hole computer. I have come further with Cmake in combination with Visual Studion but after changing a lot of settings In Visual Studio I ended with an error saying “Cannot open M.lib” that I cannot find a solution to (maybe my lack of experience in coding). I was hoping to look more into the code of Epanet instead of errors in compiling the code. So I was hoping that someone could point out a safe way to compile Epanet and I could work on the Epanet code instead. I can se that the Issue on compiling have been discussed earlier and I hope that someone has a brilliant idea how to solve it😊
Best Regards,
Rasmus

**Comment by michaeltryby** [comment]
@rasbae So I guess your program gets the energy usage numbers from the report file. Is that correct?  You can get them from the binary output file instead using the output API library. This would give you the same numbers as a 32 bit reals (6 to 7 decimal places or precision). You wouldn't have to recompile EPANET but you would need to figure out how to use the output API library.

**Comment by rasbae** [comment]
Thank you for a quick answer. I will have to take a closer look at the API library. I have not been using it before, but it seems like there are features in it that can be used for solving my problem and maybe make better solutions for me. So once again thank you for your help
Rasmus

Fra: Michael Tryby <notifications@github.com>
Sendt: 15. august 2018 19:39
Til: OpenWaterAnalytics/EPANET <EPANET@noreply.github.com>
Cc: rasbae <rasmus_baerentzen@hotmail.com>; Mention <mention@noreply.github.com>
Emne: Re: [OpenWaterAnalytics/EPANET] Compile Epanet with higher accuracy in energy (#212)


@rasbae<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frasbae&data=02%7C01%7C%7C2a2990698c2b4b79116c08d602d600be%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636699515486552535&sdata=q5tJ6FwFj4ZNZDt6jhYKlTkIUOyeRU6L%2FeCp9DXqFUs%3D&reserved=0> So I guess your program gets the energy usage numbers from the report file. Is that correct? You can get them from the binary output file instead using the output API library. This would give you the same numbers as a 32 bit reals (6 to 7 decimal places or precision). You wouldn't have to recompile EPANET but you would need to figure out how to use the output API library.

**Comment by rasbae** [comment]
Thanks for your extra help – it always helps with some more details. I will look more into the usage of the DLL´s.
Rasmus

Fra: Elad Salomons <notifications@github.com>
Sendt: 19. august 2018 12:24
Til: OpenWaterAnalytics/EPANET <EPANET@noreply.github.com>
Cc: rasbae <rasmus_baerentzen@hotmail.com>; Mention <mention@noreply.github.com>
Emne: Re: [OpenWaterAnalytics/EPANET] Compile Epanet with higher accuracy in energy (#212)


@rasbae<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frasbae&data=02%7C01%7C%7C35483126f4914735427208d605bddbc1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636702710316455662&sdata=FkThi%2BW6ds5ryGzfv%2FHRGZ588E77hz5NZ38XaIvsmFk%3D&reserved=0> if you are using VB you can call the EN_getlinkvalue API with the EN_ENERGY option to retrieve the energy value at each time
