### ISSUE TITLE
Add a new flag variable that indicates if a simulation is currently running or not

### ISSUE THREAD

**Issue by eladsal** [OpenWaterAnalytics/EPANET#213]
Originated from https://github.com/OpenWaterAnalytics/EPANET/issues/208.

Add a new flag variable (like `RunFlag`) to the `EN_Project` structure that indicates if a simulation is currently running or not. This flag will be used in some functions like `EN_setflowunits` to prevent changes during a simulation.

The `RunFlag` would be set in `EN_openH`, `EN_closeH`, `EN_openQ` and `EN_closeQ`. It would require careful thought to identify which API functions, especially those that modify parameters, would be affected by it, since for some parameters it makes sense to allow a change during an extended period analysis but for others it doesn't.

**Comment by michaeltryby** [comment]
There are three phases or modes when using the Toolkit. Before simulation, during simulation, and after simulation.
