### ISSUE TITLE
problem in get or set pump speed and pump power at getlinkvalue

### ISSUE THREAD

**Issue by milad-ghiami** [OpenWaterAnalytics/EPANET#215]
Following the pull request on [this ](https://github.com/OpenWaterAnalytics/EPANET/pull/214) , we have problem in get or set pump speed and pump power. 
i think we need two enum  like EN_POWER and EN_SPEED for solve get and set .

1. for power  of pump can set enum like EN_POWER

2. when  pump type is EN_CONST_HP  power of pump is set while when  pump type is  	EN_POWER_FUNC or  EN_CUSTOM power of pump not use and it is zero 

3. for speed of pump can set enum like EN_SPEED

4. EN_POWER is unit and EN_SPEED is unitless

5. in getlinkvalue  function add new case by EN_SPEED and EN_POWER to return values

6. in setlinkvalue like item 5
thanks of @eladsal

**Comment by milad-ghiami** [comment]
@eladsal  can help me to solve this

**Comment by eladsal** [comment]
@michaeltryby Attached is a modified Net1 network which includes a fixed power pump with a speed setting. I used this network for testing my last commit. Would you like to add this network to the testing repo?

[Net1_hp_speed.txt](https://github.com/OpenWaterAnalytics/EPANET/files/2300087/Net1_hp_speed.txt)

**Comment by milad-ghiami** [comment]
@eladsal 
i think you must add two pump
first pump has power
second pump has curved
because when set curve for a pump then power become zero

**Comment by eladsal** [comment]
Not sure I understand. If a pump has a curve it is no longer a `CONST_HP`. However, you can have a fixed power value and a curve but in this case the power setting is ignored so maybe we should return the value for all pump types?

**Comment by milad-ghiami** [comment]
That's exactly the same
When set to power and set  curve in GUI, then only the value that is set for the curve is priority and power become zero 
Anyway  If a pump has a curve  and call function to get power  of it  we must return an error or zero.

**Comment by eladsal** [comment]
So @milad-ghiami , do you suggest we keep this commit the way it is or return the power setting value as it is even if it is not used? Remember that this is a setting the user entered even if it is not used. It is like curves\patterns that exists in the INP and are not being used. We want to report the settings, right?

**Comment by eladsal** [comment]
@milad-ghiami on the other hand, if you look at the EPANET GUI, a pump may have both a curve and a power setting which is not used. I think that the INP also supports that so it might be better to be consistent with them. We can add an option to get the pump's type if it helps.

**Comment by milad-ghiami** [comment]
its great,
yes, im checked,  INP  supports power and curve together, but when load inp in  GUI  we  loss power
