### ISSUE TITLE
Get status of PRVs with EPANET-Matlab toolkit

### ISSUE THREAD

**Issue by alireza2032** [OpenWaterAnalytics/EPANET#218]
Hello all,

When I use d.getLinkStatus for status of PRVs, I get 0 (closed) or 1 (open) for PRVs while in EPANET software we can get three status for PRVs after hydraulic solving. These status are Open (means Inactive or fully open), Active and Closed.
How I distinguish the status of Open with Active in PRVs with EPANET-Matlab toolkit?

Thank you all,
Alireza

**Comment by eladsal** [comment]
Thanks @alireza2032 for posting this. The `STATUS` reported by the function is basically `OPEN` or `CLOSED`. There are more `STATES` for links and nodes. Form the [code](https://github.com/OpenWaterAnalytics/EPANET/blob/dev/src/types.h#L179):
```
typedef enum {
  XHEAD,        /*   pump cannot deliver head (closed) */
  TEMPCLOSED,   /*   temporarily closed                */
  CLOSED,       /*   closed                            */
  OPEN,         /*   open                              */
  ACTIVE,       /*   valve active (partially open)     */
  XFLOW,        /*   pump exceeds maximum flow         */
  XFCV,         /*   FCV cannot supply flow            */
  XPRESSURE,    /*   valve cannot supply pressure      */
  FILLING,      /*   tank filling                      */
  EMPTYING
} StatType;     /*   tank emptying                     */
```

So we can add an `EN_STATE` option to `ENgetlinkvalue` and `ENgetnodevalue` and return the exact state. This was also suggested to me by Fernando Martínez.

Thoughts anyone?

**Comment by alireza2032** [comment]
Thanks a lot Dear eladsal, 
I consider your guide.

**Comment by eladsal** [comment]
Committed 99e7151. It turned out that a special check for pumps was needed.

Please test!

**Comment by Mariosmsk** [comment]
@eladsal , I have tested this now and it's ok! Also the `status` in the binary file it's the same with `state` (without events). fyi

![image](https://user-images.githubusercontent.com/2945956/44727493-d48ad800-aae2-11e8-9070-8407c8560c35.png)

**Comment by alireza2032** [comment]
Thanks @Mariosmsk , 
Is it possible to set the initial status of PRVs with EMT in states Open, Close and None (means active)?

**Comment by Mariosmsk** [comment]
You can use the function `d.setLinkInitialStatus(LinkIndex, status) ` where status is `Initial link status (0 = closed, 1 = open)`

**Comment by alireza2032** [comment]
Dear @Mariosmsk , 
Thanks, but, 1=fully open and I want to define the initial link status on None (=active or partially open). Is it possible?

**Comment by alireza2032** [comment]
Dear @Mariosmsk ,
Thanks, but, 1=fully open and I want to define the initial link status for PRV valve on None (=active or partially open). Is it possible?

**Comment by lbutler** [comment]
Hi @eladsal ,

Sorry for bringing up an old closed issue, but I was wondering if there was any reason why we never got `EN_STATE` in v2.2 on EPANET, did this commit just miss getting merged in or was there further reasons for it not being included?

cc @neslerel

**Comment by samhatchett** [comment]
@lbutler after some investigation, I believe that this enum got refactored as `EN_PUMP_STATE` - even though you can use it to get non-pump information. It takes some serious browsing of the git-blame, but it does look like Elad's contribution was modified a few times by Lew and that's where it ended up. We should probably have a documentation issue to track that weirdness.

Thanks for bringing this up!

**Comment by lbutler** [comment]
Thanks @samhatchett for tracking what happened, I gave it a try and it worked perfectly.

It would be good if there was an enum for the rest of the states and potentially a more descriptive method name, but we can discuss that in a new issue.
