### ISSUE TITLE
Update epanet output api chemical name functionality 

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/EPANET#220]
Add capability to epanet output api to return a string with the chemical name.

**Comment by eladsal** [comment]
Would that be different from `EN_getqualinfo`?
```
EN_getqualinfo(EN_Project *p, int *qualcode, char *chemname, char *chemunits, int *tracenode)
```

**Comment by michaeltryby** [comment]
@eladsal I am proposing a function that reads the chem name out of the binary output file header.  `EN_getqualinfo()` is a toolkit function that access the chem name from the epanet data model at runtime.  They are the same variable that reside in different places at different times.

**Comment by eladsal** [comment]
Got it, thanks.
