### ISSUE TITLE
Set multiple base demand and multiple pattern in EPANET-Matlab toolkit 

### ISSUE THREAD

**Issue by alireza2032** [OpenWaterAnalytics/EPANET#221]
Hello all,

Is it possible to define a example for setting multiple base demand and multiple pattern in EPANET-Matlab toolkit.

Thanks,
Alireza

**Comment by Mariosmsk** [comment]
I have replied to the [community](http://community.wateranalytics.org/t/set-multiple-base-demand-and-multiple-pattern-in-epanet-matlab-toolkit/691). Maybe someone closes this.
