### ISSUE TITLE
Branch cleanup

### ISSUE THREAD

**Issue by eladsal** [OpenWaterAnalytics/EPANET#223]
We have a long list of old and inactive branched. We should consider deleting the unneeded ones.

I'm going to delete the old `set-units` branch. It was used to develop the `ENsetflowunits` API and not needed anymore.

**Comment by milad-ghiami** [comment]
i think some of code can be useful for documentation,
but use branch for documentation its not good way .
we must create a procedure that can documents all my events to it , for example why we  create this branch and why delete it , 
you answered to this question   

> It was used to develop the ENsetflowunits API and not needed anymore

.
if delete this branch we can document this event ,
Of course , github log  lot of things

**Comment by samhatchett** [comment]
as far as I can tell, we can safely delete the "active + merged" and "stale" branches here:
https://github.com/OpenWaterAnalytics/EPANET/branches

... with the possible exception of `release` - anyone know what the purpose of that is?

**Comment by samhatchett** [comment]
quick update - I deleted many old branches that were already merged (most came from me), which helps things a bit. any other candidates?

**Comment by samhatchett** [comment]
branches are looking WAY cleaner. good job all.
