### ISSUE TITLE
Epanet build folder

### ISSUE THREAD

**Issue by milad-ghiami** [OpenWaterAnalytics/EPANET#224]
Hi, following [this](http://community.wateranalytics.org/t/how-to-compile-epanet-on-linux/694) issue on from,  if Epanet had a  build folder  . it maybe  benefit for users

**Comment by bemcdonnell** [comment]
@milad-ghiami, this project has `cmake` support which is a x-platform x-compiler x-architecture tool to provide make instructions for whatever target the developer has in mind.  I think most of the OWA projects aspire to be agnostic to specific build workflows so we can let the developer run the build to their specs.  The fewer build files we have around means the less maintenance we have to do as we evolve the projects.  If we incorporate more and more build files to target specific cases, we might lose "tidiness".  I propose that a better approach might be to have a simple file store somewhere where people can share their build scripts.  Then it need not be maintained directly in this project.

**Comment by samhatchett** [comment]
Not sure i'm understanding the issue. The release tag does have a build folder, and building is rather straightforward in Linux:

```
curl -JLO https://github.com/OpenWaterAnalytics/EPANET/archive/v2.1.tar.gz
tar -xzf EPANET-2.1.tar.gz
cd EPANET-2.1/build/CMake
cmake . && make
```

**Comment by michaeltryby** [comment]
@milad-ghiami we already have a multi-platform build system in place called [cmake](https://cmake.org/). You can use it to build on any platform and any compiler.  Build instructions for `epanet` are located [here](https://github.com/OpenWaterAnalytics/EPANET/blob/dev/.github/BuildAndTest.md).

**Comment by milad-ghiami** [comment]
![screenshot from 2018-08-22 00-33-26](https://user-images.githubusercontent.com/10231350/44426102-02cc5d00-a5a3-11e8-90af-f185fe7b0027.png)
thanks, cmake is very good , i just think , this way can be good too

**Comment by michaeltryby** [comment]
@milad-ghiami you can read up and get some background on why we chose cmake in Issue #38.
