### ISSUE TITLE
Syntax for the epanet executable does not include binary files (also duplicate definition)

### ISSUE THREAD

**Issue by eldemet** [OpenWaterAnalytics/EPANET#228]
https://github.com/OpenWaterAnalytics/EPANET/blob/761199b08e8b885d14a8800256d80890d901af96/src/text.h#L343

This does not mention the optional capability of creating a binary file.

I suggest we modify it as follows:

` #define FMT03  "\n Correct syntax is:\n %s <input file> <output file> <(optional) output binary file>\n"`

**Comment by eladsal** [comment]
@eldemet teh second file should actually read `<report file>`, right?

While you at it, `FMT03` is also declared in `main.c`.

**Comment by eldemet** [comment]
Well @eladsal, it said "output" in the original. However I agree that it should be renamed to <report> to be consisted with the vocabulary of epanet. 

Hm, now we are at it, we could also follow this standard: http://docopt.org/

In that case we could use

`#define FMT03 "\nEPANET\n\nUsage:\n  %s <input_filename> <report_filename> [<binary_filename>]\n"`

instead of the first suggestion

**Comment by eladsal** [comment]
Fixed in 13011ae71c4682cdca08ff6b136b673f512014d2.

**Comment by michaeltryby** [comment]
You can see from the discussion above that there is already a link in the thread to PR #229 that closes the issue.

**Comment by eladsal** [comment]
Well, the issue was still open and I find it easier that the last comment has that meaning (not anymore...).
