### ISSUE TITLE
Convert Travis CI from Linux to Mac OS

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/EPANET#233]
Proposal to setup Travis to use Mac OS instead of Linux.

**Comment by michaeltryby** [comment]
A CI running Mac OS would be more relavent to the Mac using developers among us and therefore more likely to be actively maintained.

**Comment by samhatchett** [comment]
we can consider adding mac CI, but I'm more interested in getting Linux CI working.

**Comment by michaeltryby** [comment]
@samhatchett Really? I created this issue just for you!

**Comment by samhatchett** [comment]
I like developing on the mac, but my staging/production work is all dockerized linux - and so going forward it's important to make sure that CI works in linux.
