### ISSUE TITLE
MEMPOOL.C is not thread-safe

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#234]
The memory allocation module `mempool.c` which is used to manage the creation and deletion of water quality segments in `quality.c` is not thread safe. This will cause problems when the new thread-safe API of v. 2.2 is used to run water quality analyses on two or more projects concurrently.

**Comment by michaeltryby** [comment]
This is fixed here: https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/blob/feature-reentrancy/src/mempool.c

**Comment by LRossman** [comment]
Thanks @michaeltryby . To avoid introducing threading library code into the basic EPANET engine I think it might be better to just revise the mempool functions so that they take a pointer to a specific memory pool as an input argument.  I was thinking of simplifying the entire mempool.c routine using a C-version of the C++ class I wrote here:  https://github.com/OpenWaterAnalytics/epanet-dev/blob/master/src/Utilities/mempool.cpp.

**Comment by michaeltryby** [comment]
It’s not thread library code. It’s a compiler directive.

**Comment by michaeltryby** [comment]
@LRossman It’s new storage class specifie that is part of the language specification. It does not impose any library dependencies on the code.

**Comment by michaeltryby** [comment]
I wrote a unit test for thread safety. I thought it was working, but apparently it's not. It produces intermittent segfaults that have been showing up in the CI logs and I am able to reproduce locally.

**Comment by michaeltryby** [comment]
If I build in Debug config this test runs reliably. If I build in Release config this test fails intermittently.
