### ISSUE TITLE
update Tracenode in add/remove node api fn

### ISSUE THREAD

**Issue by samhatchett** [OpenWaterAnalytics/EPANET#239]
from https://github.com/OpenWaterAnalytics/EPANET/issues/172#issuecomment-382266217

**Comment by eladsal** [comment]
When deleting a node we should check if that node is the `Tracenode`. If so, we have to raise an error "Can't delete the trace node" since there may be an attempt to run a trace simulation which will fail.

**Comment by michaeltryby** [comment]
@eladsal so what would the procedure for deleting the node be. Undefine as tracenode then delete? 

Or you could allow them to delete the node and provide a warning that a new tracenode needs to be defined.

**Comment by eladsal** [comment]
Yes, undefine as tracenode and then delete. I'd give an error, not a warning since currently there is no other mechanism to check it afterwards.

**Comment by eladsal** [comment]
This is already fixed in the `EN_deletenode` function:
```
    // Can't delete a water quality trace node
    if (index == p->quality.TraceNode) return 260;
```
