### ISSUE TITLE
what to do when removing a node/link referenced in rule/control

### ISSUE THREAD

**Issue by samhatchett** [OpenWaterAnalytics/EPANET#240]
error? or auto-delete the rule/control?

reference: https://github.com/OpenWaterAnalytics/EPANET/pull/238/files#diff-38a911bd86983e691fa46711d21ba3b6R4962

**Comment by eladsal** [comment]
One can't add a rule which reference a non existing element so why would it be possible to remove an element that is referenced?

**Comment by eladsal** [comment]
+1
Definitely an error.

**Comment by eladsal** [comment]
I think we can close this issue, right?
