### ISSUE TITLE
Network data

### ISSUE THREAD

**Issue by kenwaka** [OpenWaterAnalytics/EPANET#253]
Hi

I need several epanet files in the water network , I searched the internet and found two networks(."Bwsn 1,2")

If someone has a network file,  can be shared it with me?
Where can I find epanet files of different networks?

Thanks

Best,
Ken

**Comment by michaeltryby** [comment]
There are a bunch of networks here: 
https://github.com/OpenWaterAnalytics/epanet-example-networks

and here: 
http://emps.exeter.ac.uk/engineering/research/cws/research/distribution/benchmarks/

**Comment by kenwaka** [comment]
@Mariosmsk  , @michaeltryby thank a lot, 
I can't thank you enough

**Comment by kenwaka** [comment]
@Mariosmsk  Hi, i can't open any file in @kenwaka, and here
https://github.com/eldemet/draft-code/tree/master/benchmarks ,  i have error . how can i open these file?
![eror](https://user-images.githubusercontent.com/42710063/45250776-c5602180-b34f-11e8-9848-c8df6585ec7f.PNG)

thanks
best,
ken

**Comment by Mariosmsk** [comment]
It's ok for me! 
![image](https://user-images.githubusercontent.com/2945956/45253694-16820c80-b374-11e8-8b81-0fa4d0cfcd8f.png)

Maybe reinstall the EPANET exe https://www.epa.gov/sites/production/files/2014-06/en2setup_0.exe

**Comment by michaeltryby** [comment]
@kenwaka How did you move the files from GitHub to your computer?

**Comment by kenwaka** [comment]
Hi @michaeltryby  .
 right click on the link> save link as.
How should I move these files to my computer?
Please tell me if you have time.
Thanks & Best
Ken

**Comment by michaeltryby** [comment]
You need to select the text in the web browser window and copy then paste into text editor on your computer.

**Comment by kenwaka** [comment]
Hi , @michaeltryby . thanks alot  :-)
