### ISSUE TITLE
Fix memory leaks in epanet output library 

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/EPANET#254]
Unit testing has identified memory leaks that need to be fixed.

**Comment by LRossman** [comment]
@michaeltryby could you be more specific about which files you are talking about. Thanks.

**Comment by michaeltryby** [comment]
https://github.com/OpenWaterAnalytics/EPANET/blob/dev/tools/epanet-output/src/epanet_output.c
