### ISSUE TITLE
Master branch shows the build failing badge

### ISSUE THREAD

**Issue by eladsal** [OpenWaterAnalytics/EPANET#259]
I think that the badge on`master` is linked to the wrong test. Each branch\PR should have its own badge. Is this doable?

**Comment by michaeltryby** [comment]
Already fixed it.

**Comment by eladsal** [comment]
For me it shows as failing. This is the link in the `master` readme:
https://travis-ci.org/OpenWaterAnalytics/EPANET.svg?branch=master
[![Build Status](https://travis-ci.org/OpenWaterAnalytics/EPANET.svg?branch=master)](https://travis-ci.org/OpenWaterAnalytics/EPANET)

**Comment by eladsal** [comment]
And the test it is linking to is not for the `master` code but the `dev`s. Don't think you can fix it without changing the `master` readme file.

**Comment by michaeltryby** [comment]
https://github.com/OpenWaterAnalytics/EPANET/commit/f7d54810ea9402ccb266a3541535dd9c8a6341e9

**Comment by eladsal** [comment]
Hint again. This change was on `dev`. Do you see a different badge for `master`?

![screenshot 491](https://user-images.githubusercontent.com/1942312/44929117-7cfa9f80-ad62-11e8-8317-ca293aca4cd4.png)

**Comment by michaeltryby** [comment]
The master branch is way out of date. It won't get updated until we make our next release.

**Comment by michaeltryby** [comment]
Also, there is no way for each branch to have its own badge. That's not doable.

**Comment by eladsal** [comment]
OK, We will probably have to live with it until 2.2.
The thing is it was showing the green badge yesterday and now it is red. And that is our 2.1 release code.

**Comment by michaeltryby** [comment]
The reg testing and unit testing came online significantly after the 2.1 release.

**Comment by eladsal** [comment]
It does not matter, the `master` is checked with its own `yml` file. Tests are fixed for a release.
