### ISSUE TITLE
Should we keep the sample networks?

### ISSUE THREAD

**Issue by eladsal** [OpenWaterAnalytics/EPANET#26]
Not sure what are the [sample networks[(https://github.com/OpenWaterAnalytics/EPANET/tree/dev-2.1/example-networks). What are they supposed to show? Should we keep them on the branch?

**Comment by samhatchett** [comment]
i think the sample networks are handy -- if not these in particular, then just a simple set of net-1/2/3. I could see these being used for an automated build-run-test workflow to ensure that results are consistent.

**Comment by eladsal** [comment]
I think we can start with Nets 1,2 and 3 and then add more if/when needed. BTW, this would be a good time to fix that missing coordinate for Net 3.

**Comment by eladsal** [comment]
Done in [a31e4242f3](https://github.com/OpenWaterAnalytics/EPANET/commit/a31e4242f36ca6bb7de0211835fc54f283e21abc)
