### ISSUE TITLE
where is  epanet_export.h

### ISSUE THREAD

**Issue by milad-ghiami** [OpenWaterAnalytics/EPANET#260]
Hi, where is  [epanet_export.h](https://github.com/OpenWaterAnalytics/EPANET/blob/dev/include/epanet2.h#L64)

**Comment by eladsal** [comment]
/tools/epanet-output/include/

**Comment by milad-ghiami** [comment]
and this [epanet_output_export.h](https://github.com/OpenWaterAnalytics/EPANET/blob/dev/tools/epanet-output/include/epanet_output.h#L95)

**Comment by Mariosmsk** [comment]
These files auto-create when building the project.
EPANET\include\epanet_export.h
EPANET\tools\epanet-output\include\epanet_output_export.h

**Comment by milad-ghiami** [comment]
Unfortunately, I was working mostly on Linux  , I have problem with cmake on Windows

**Comment by michaeltryby** [comment]
When you compile on Linux define the pre processor variable “NO_GENX” then the compiler should ignore the missing header files.

**Comment by michaeltryby** [comment]
Or you can use cmake on Linux.

**Comment by milad-ghiami** [comment]
a moon age, i cmake  in linux

**Comment by michaeltryby** [comment]
Nice! Usually, what I do is use cmake from the command line to generate the solution and project files and then open the solution in Visual Studio.
