### ISSUE TITLE
Why is epanet_export.h now #included in epanet2.h in the latest merge of dev

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#262]
It seems like one is now required to `#define NO_GENX` in their calling program to avoid having to link in the epanet-output library. Was this an oversight?

**Comment by michaeltryby** [comment]
No it’s not an oversight. And it has nothing to do with linking to the output library. It is how cmake generates an export library. It’s a replacement for the antiquated def file approach we have been using. The export library is used to link with the EPANET.dll. Anyone who wants to link with the dll will find it useful. I use to build the python wrappers. 

Define NO_GENX in your build script and the export headers will be ignored.

**Comment by LRossman** [comment]
What build script are you talking about? This type of change without informing developers of what you are doing is very frustrating. 😥

**Comment by michaeltryby** [comment]
The changes were made in a public repo and contributed in a reviewed PR that other developers were welcome to comment on at any point in the process. If you don’t like it just Define NO_GENX in your build setup.

**Comment by LRossman** [comment]
Is the build script you refer to `CMakeLists.txt`? If so, how does one define NO_GENX in it? If someone is going to use the API in their 3rd party app it would fail to compile because they don't know they have to define NO_GENX somewhere. Why are you making the API header file dependent on what's in a build script. I just don't get it.

**Comment by michaeltryby** [comment]
How do you build EPANET?

**Comment by michaeltryby** [comment]
I understand there are shortcomings to this approach. Why don’t you do something constructive and open an issue and offer workable solutions. Be aware that building the python packages puts constraints on the build process that you aren’t taking into consideration.

**Comment by eladsal** [comment]
What do you mean by it is a replacement for the antiquated def file approach? If I don't use NO_GENX I can ignore the def file?

**Comment by milad-ghiami** [comment]
i always  can compile epanet in windows by visual studio, but now i cant compile with it :(

**Comment by michaeltryby** [comment]
The project made the decision to standardize on CMake three years ago in Issue #38. 

I’m willing to bet that the developers posting here don’t use it.

**Comment by milad-ghiami** [comment]
always compile a code on different platforms requires a bit of additional configuration. This is not a worry.
 :)

**Comment by eladsal** [comment]
@michaeltryby regarding the DEF file you mentioned. Is the new build equivalent to the one built by the win script with the DEF file?

Maybe it was better to have the NO_GENX by default and not the other way around. This would help with backward compatibility.

**Comment by michaeltryby** [comment]
@eladsel there are three different approaches for linking in Visual Studio. Def files, export libraries, and another I can’t recall. It’s a technical subject best left to the Visual Studio documentation.

**Comment by milad-ghiami** [comment]
how to #define NO_GENX ? im use fedora but cant compile by cmake

**Comment by michaeltryby** [comment]
You can see from the badge that cmake is building on Travis running Ubuntu Linux. So what exactly are you doing?

**Comment by milad-ghiami** [comment]
ok i can do it 

`
git clone https://github.com/OpenWaterAnalytics/EPANET.git
cd EPANET/
cmake CMakeLists.txt 
 make
cd bin/
./runepanet
`

:)

**Comment by milad-ghiami** [comment]
how to clean after cmake and  again run cmake

**Comment by michaeltryby** [comment]
You can see from the Travis build script that it creates a folder to contain the files that cmake generates. Then If you want to regenerate the build system you can just delete the folder. This is the recommended approach.

**Comment by LRossman** [comment]
I finally figured out what the deal is with `epanet_export.h`. It allows the `DLLEXPORT` modifer on the API functions to define either an export library, as when the DLL is being built, or as an import library when the DLL is used by an app. In the latter case it eliminates the need to use a `DEF` file (which with almost 200 API functions would be a pain to create). The `CMakeLists.txt` file tells `epanet_export.h` to use the DLLEXPORT symbol in export mode while the default is to define it for import mode. When you want to reference `epanet.dll` functions in your own app, you need to `#include epanet2.h` in your file as usual, but also make sure that `epanet_export.h` is in the same folder with `epanet2.h`. I found this to be a useful reference on [ linking and using DLL's.](https://msdn.microsoft.com/en-us/library/ms235636.aspx)

**Comment by michaeltryby** [comment]
Yes that is what it does, however, your original criticism is still valid especially for developers not using cmake.

**Comment by LRossman** [comment]
Can we eliminate the need for `epanet_export.h` by modifying the top of `epanet2.h` to look as follows:
```
  // --- define EPANET_API
  #ifndef EPANET_API
    #ifdef WINDOWS
      #ifdef EPANET_EXPORTS
        #ifdef __cplusplus
        #define EPANET_API __declspec(dllexport)
        #else
        #define EPANET_API __declspec(dllexport) __stdcall
        #endif // __cplusplus
      #else
        #ifdef __cplusplus
        #define EPANET_API __declspec(dllimport)
        #else
        #define EPANET_API __declspec(dllimport) __stdcall
        #endif // __cplusplus
      #endif  //EPANET_EXPORTS
    #elif defined(CYGWIN)
      #define EPANET_API __stdcall
    #else
      #define EPANET_API
    #endif  //WINDOWS
  #endif  //EPANET_API
```
and in `CMakeLists.txt` add the following under `IF (MSVC)`:
  `add_definitions(-D EPANET_EXPORTS)`
and delete the `include(GenerateExportHeader)` section.

People not using `cmake` will have to add the `EPANET_EXPORTS` preprocessor definition either to their command line or through the Project Properties dialog if using Visual Studio. Developers using the DLL as an import library don't have to do anything special other than `#include epanet2.h `and link with `epanet.lib`.

Note that I replaced the DLLEXPORT symbol with EPANET_API which I think is more descriptive (since it serves for both export and import). Of course this means that one would have to do a global Find and Replace on DLLEXPORT in both epanet2.h and epanet2.c (or not -- replacing DLLEXPORT is just a suggestion).

**Comment by eladsal** [comment]
@LRossman I use the `DEF` which need to be updated only when new functions are added (the `DEF` file is in the `\win_build\WinSDK\` directory). However, I would be happy to give it up if there was a simple way to do so. I have tried compiling with the `epanet_export.h` file but that didn't work with VB and VBA. Any additional flag needed in `cl.exe` command line?

**Comment by LRossman** [comment]
@eladsal I think (not sure) that the `epanet_export.h` file is missing the `__stdcall` qualifier when it defines DLLEXPORT and therefore the compiled DLL won't work with VB. So, with no guarantees, here's what I suggest:

1. Add `-DNO_GENX` to your cl.exe command line. That should (I think) force the compiler to use the old #defines in epanet2.h to define DLLEXPORT with `__stdcall`.

2. To avoid having to use a DEF file, include the decorated name of the DLL functions in your epanet2.bas and epanet2.vb files, using an alias clause in the function declaration like so:

`Declare Function ENgetversion Lib "epanet2.dll" Alias "_ENgetversion@4" (ByRef Value As Int32) As Int32`

So you're essentially just embedding the DEF file information directly into the VB declaration modules.

3. If you need to see what the decorated alias names are for the DLL functions you can add a `/MAP `option to your `cl` command that will generate an epanet2.map file where the names will be listed.

**Comment by michaeltryby** [comment]
@LRossman CMake generates epanet-exports differently depending on what system the code is being built on. What you are suggesting will work on Windows but may not work on Linux.

**Comment by LRossman** [comment]
@michaeltryby I assume you are referring to my comment about eliminating `epanet_export.h`. I believe that my suggestions for modifying the `cmake` script only apply to those portions that are Windows-specific. I will try to test my alternative on both a Windows and Linux build and report back.

Plus, as noted in my response to @eladsal, I think that the #defines in `epanet_export.h` don't distinguish between a C and C++ build, and for the former case fail to add on the `__stdcall` qualifier to the defintion of DLLEXPORT.

**Comment by eladsal** [comment]
@LRossman thanks!
The win script is [here](https://github.com/OpenWaterAnalytics/EPANET/blob/dev/win_build/WinSDK/Makefile.bat). I already use the `/D NO_GENX`  and `/MAP` flags. Will try the VB declare option but it is not elegant :)

**Comment by michaeltryby** [comment]
@LRossman I think I've got a better solution.  With `NO_GENX` as it stands now `epanet_export.h` is opt out. You have to tell the compiler you don't want to use it. I have an alternate setup working where it is opt in rather than opt out. So the compiler will include `epanet_exports.h` only when `WITH_GENX` is defined. Thus `epanet-export.h` is not required unless you want it, and backwards compatibility is preserved. 
 
I think this is simpler than what you are proposing.

**Comment by michaeltryby** [comment]
The goal of my PR was to get the python packages to build while providing backward compatibility for VB.

**Comment by michaeltryby** [comment]
@LRossman another thing to consider is that we don’t need a single dll to be all things to all people. It is ok for there to be different EPANET library builds for different purposes. It’s not essential to moving things forward.

**Comment by milad-ghiami** [comment]
@michaeltryby  i work in the web with RestFullAPI  but in win  we need same standard ,
i think we can create Multi Dll with spatial Category such as Quality, Hydraulic, ....
it is possible?

**Comment by michaeltryby** [comment]
@milad-ghiami reorganizing EPANET into several dlls is a different idea. I was talking about building the dll one way to link with an export library and another way to link using a def file.

**Comment by LRossman** [comment]
If the new default is to use the old macros at the top of `epanet2.h `to define DLLEXPORT then they need to be modified so that a VB (or C#, Pascal, etc.) - compatible DLL can be created without the need to deploy a DEF file. Here is what it should look like:
```
 // --- define DLLEXPORT
  #ifndef DLLEXPORT
    #ifdef WINDOWS
      #ifdef EPANET_EXPORTS
      #define DLLEXPORT __declspec(dllexport) __stdcall
      #else
      #define DLLEXPORT __declspec(dllimport) __stdcall
      #endif
    #elif defined(CYGWIN)
      #define DLLEXPORT __stdcall
    #else
      #define DLLEXPORT
    #endif
  #endif 
```
And in addition, as mentioned previously, the following needs to be added to `CMakeLists.txt` under the  `IF (MSVC)` section: `add_definitions(-D EPANET_EXPORTS)`.

I tested the DLL resulting from this mod on both a C and a C# custom app **without referencing a DEF file** and both worked just fine. (I assume that since it worked for C# it would also work for VB.net). If I can get an OK to proceed I'd like to commit these changes.

**Comment by michaeltryby** [comment]
But then wouldn't -D EPANET_EXPORTS and -D WITH_GENX duplicate eachother and conflict?

**Comment by michaeltryby** [comment]
@LRossman Yes it is. I merged it yesterday. See PR #274.

**Comment by michaeltryby** [comment]
It seems like generate exports would do everything you want to do, if there was a way to add `__stdcall` to the macro definition.

**Comment by michaeltryby** [comment]
Looks like we can add `/Gz` compiler flag to add __stdcall to all declared functions. 

https://msdn.microsoft.com/en-us/library/zxk0tw93.aspx

**Comment by LRossman** [comment]
Wouldn't using /Gz make all functions in the entire DLL stdcall -- that's not needed.

Also I'm now totally confused about how you want to treat the #include epanet_export.h in epanet2.h. I thought you agreed to skip over it by default.

Since we seem to be going around in circles on this I'm opting out of this discussion.

**Comment by michaeltryby** [comment]
@LRossman I agreed to ignore `epanet_export.h` by default so that it wouldn't interfere with other build systems. Why would I generate it and then ignore it in a cmake build? How does that make sense?   

I have stated clearly what my objectives where - To get the python wrappers to build while providing backwards compatibility for Elad's VB build. That is what PR #274 accomplishes. Done. 

If you want to eliminate the def file open an issue.
