### ISSUE TITLE
value of  error function  is not in error list

### ISSUE THREAD

**Issue by milad-ghiami** [OpenWaterAnalytics/EPANET#264]
Hi every one ,  after compile successfully , now i  say my idea:

when run Epanet  for One inp file that have warning, for example  if you change MinLevel  for tank in Net1.inp from 100 to 120  
```
[TANKS]
;ID              	Elevation   	InitLevel   	MinLevel    	MaxLevel    	Diameter    	MinVol      	VolCurve
 2               	850         	120         	120         	150         	50.5  
```
and  write this code :

```
do {
	errcode = ENrunH(&t);
	if(errcode>0)  	
		printf("error ENrunH is %d \n",errcode);
	errcode = ENnextH(&tstep);
	if(errcode>0)  	
		printf("error ENnextH is %d \n ",errcode);		
} while (tstep > 0);

```
after run  we get this 

```
error ENrunH is 6 
error ENrunH is 6 
error ENrunH is 6 
error ENrunH is 6 
error ENrunH is 6 
error ENrunH is 6 
```

but we don't have 6 in error list , and we told we return error ,  while  we have only warning 
 
in this part we must set warning list for 4,6,....

im add Net1.inp by changes
[Net1.txt](https://github.com/OpenWaterAnalytics/EPANET/files/2343575/Net1.txt)

[out2_1.txt](https://github.com/OpenWaterAnalytics/EPANET/files/2343566/out2_1.txt)

if all contributes allow add warning codes 
 
@LRossman @eladsal  @michaeltryby

**Comment by milad-ghiami** [comment]
i think we must return Message of  warning   in During solving

**Comment by michaeltryby** [comment]
EN_checkError() returns the message.
