### ISSUE TITLE
CODEVERSION and VERSION are redundant

### ISSUE THREAD

**Issue by samhatchett** [OpenWaterAnalytics/EPANET#27]
... or at least the difference is not clear and documented.

**Comment by eladsal** [comment]
It seems that CODEVERSION is not used by the engine but only written in the report and the binary output file. The VERSION number is used only written to the hydraulic binary file in `openhydfile`. and when this file is read there is check that the hydraulic file version is the same as the current Toolkit - [line 2917](https://github.com/OpenWaterAnalytics/EPANET/blob/dev-2.1/src/epanet.c#L2917). This is probably to make sure that the file is used by the same version of the engine which wrote it.

If that is the case maybe there is a need for two version numbers. One as a general version of the Toolkit and the second is the engines version. I think we should currently keep them both and bump VERSION from 200 to 201.

**Comment by samhatchett** [comment]
ok, so one is for the engine and the other for the bin file format - i can see the comment lines now. Would it be annoying to change the names to be a little more self documenting? like `ENGINE_VERSION` and `BINFILE_VERSION` 

but also in the future, the bin file should probably contain both of these version numbers - one to record the binary format revision and the other to record the engine that produced the results.

**Comment by eladsal** [comment]
Not only the bin version, `CODEVERSION` is also written to the ASCII report file and this is the value which `ENgetversion` returns. I would say its the `BUILD_VERSION` or just the `CODE_VERSION`. I'm fine with `ENGINE_VERSION`. No problem to change the names.

Yes, in the future we can consolidate them.

**Comment by eladsal** [comment]
So we are changing `VERSION` to `ENGINE_VERSION` for now.

**Comment by eladsal** [comment]
BTW, the change in the value of `VERSION` (now `ENGINE_VERSION`) is compatible with the EPANET GUI while the change to `CODEVERSION` is not.

**Comment by samhatchett** [comment]
:+1: thanks @eladsal
