### ISSUE TITLE
How to include a long test file?

### ISSUE THREAD

**Issue by eladsal** [OpenWaterAnalytics/EPANET#273]
How can I include a test in a separate file in the `test_toolkit.cpp` tests file. This file is getting longer and I was thinking of splitting.

**Comment by michaeltryby** [comment]
What is the test for?

**Comment by eladsal** [comment]
Net builder.

**Comment by michaeltryby** [comment]
Just call is test_<something>.cpp where something is what the test if for. So like if it is for netbuilder functions you could call is test_netbuilder.cpp. The tests get added automatically by the cmake script.

**Comment by eladsal** [comment]
OK, will try. Thanks!
