### ISSUE TITLE
Understanding tests

### ISSUE THREAD

**Issue by eladsal** [OpenWaterAnalytics/EPANET#277]
I'm writing a test for the net building function and trying to understand how exactly the tests work. Looking at the latest test by @LRossman for the threadsafe issue - `test_reent.cpp` ([here](https://github.com/OpenWaterAnalytics/EPANET/blob/dev/tests/test_reent.cpp)), when does this test pass,? If it builds and execute without an error? I don't see in the code any condition for fail\pass. Even if one of the `EN_runproject` runs returns an error, it seems that the test will pass, I don't see the mechanism for the validation.

What am I missing?

**Comment by michaeltryby** [comment]
@eladsal I wrote that test. It’s not a good example. Look at the other tests and that might help clear up your confusion.

**Comment by eladsal** [comment]
@michaeltryby my mistake, it is your test. The other tests I understand, this one got me thinking....

Thanks.
