### ISSUE TITLE
Duplicate entries in the AUTHORS file

### ISSUE THREAD

**Issue by eladsal** [OpenWaterAnalytics/EPANET#28]
There are duplicate entries in the [Authors](https://github.com/OpenWaterAnalytics/EPANET/commit/c9839c0eb33b2446ac0c6413d23c70b57d027f55) file. For example:
James Uber
jamesuber
and:
eldemet
Demetrios Eliades
Same emails but different user\names.

Also, I think Lew's name should be added on the top of the list.

**Comment by samhatchett** [comment]
Good thoughts. I just borrowed the generator script from another project. We can customize to de-duplicate and add Lew.
