### ISSUE TITLE
Deprecate linking to epanet.dll with a DEF file

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/EPANET#281]
@LRossman proposes changing `epanet2.h` to deprecate linking to the dll with a DEF file.

> If the new default is to use the old macros at the top of epanet2.hto define DLLEXPORT then they need to be modified so that a VB (or C#, Pascal, etc.) - compatible DLL can be created without the need to deploy a DEF file. Here is what it should look like:

``` 
// --- define DLLEXPORT
  #ifndef DLLEXPORT
    #ifdef WINDOWS
      #ifdef EPANET_EXPORTS
      #define DLLEXPORT __declspec(dllexport) __stdcall
      #else
      #define DLLEXPORT __declspec(dllimport) __stdcall
      #endif
    #elif defined(CYGWIN)
      #define DLLEXPORT __stdcall
    #else
      #define DLLEXPORT
    #endif
  #endif 
```
> And in addition, as mentioned previously, the following needs to be added to CMakeLists.txt under the IF (MSVC) section: add_definitions(-D EPANET_EXPORTS).

> I tested the DLL resulting from this mod on both a C and a C# custom app without referencing a DEF file and both worked just fine. (I assume that since it worked for C# it would also work for VB.net). If I can get an OK to proceed I'd like to commit these changes.

Alternately, cmake `generate_exports()` can be combined with the /Gz flag in Visual Studio to the same effect. 
 
For more background see Issue #262.

**Comment by michaeltryby** [comment]
@eladsal Did you try doing [this](https://github.com/OpenWaterAnalytics/EPANET/issues/262#issuecomment-418375786)?

**Comment by eladsal** [comment]
No, I used a DLL @LRossman sent me.
