### ISSUE TITLE
DLL built from dev branch doesn't work with the legacy EPANET 2.0 GUI

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#283]
The current DLL built from `dev` doesn't work with the legacy EPANET 2 Windows GUI, even after re-naming it to epanet2.dll (which is what the GUI requires). It gets to the point where it displays "Saving hydraulics ..." in the progress window and then crashes and closes the GUI.

**Comment by eladsal** [comment]
I have just compiled the DLL with the win script and the GUI runs fine for Net1.

**Comment by eladsal** [comment]
I'm a bit confused since I didn't change the version number of the DLL back to 2.0.12 so not sure how the old GUI runs.

I also noticed that the EPA's web site has a new version of the GUI dated 09/05/2018 which seems to be with a bit different feel...

**Comment by LRossman** [comment]
@eladsal excellent! I just confirmed your finding. But I suppose it raises the questions:

1. Why are there two build systems (cmake and win script) producing two differently named DLL's (epanet.dll and epanet2.dll) from the same source code?
2. What is it about the cmake build that is causing its DLL to fail to run properly in the legacy GUI?

Concerning the "new" legacy GUI, it's just a re-compilation of the old GUI under the latest free version of Delphi that also includes a working Help file but otherwise with no new features.

**Comment by eladsal** [comment]
I can only say that the win script creates the `epanet2.dll` from the start. Don't know about the cmake one.

The "new" exe file is ~5MB (!)

**Comment by michaeltryby** [comment]
Could it be because the cmake build does not use `__stdcall` when it creates the dll but that is what the legacy Delphi UI expects?

**Comment by michaeltryby** [comment]
Cmake is setup such that the cle  dynamically links with the dll rather than static linking in all the object code.

**Comment by LRossman** [comment]
@michaeltryby  Yes, it's partly that and also that it needs to be linked with the `epanet2.def` file when built (but not when deployed). Does this require modifying the cmake script, so that the same DLL can be produced from either it or the win script batch file. Logic would say yes, but I'll let the community decide.

@eladsal the increase in size of the GUI executable is due to 20 or so years worth of new Delphi versions where I guess the size of the libraries it bundles into the executable keeps growing.

**Comment by michaeltryby** [comment]
Here is an [article](https://stackoverflow.com/questions/10405991/calling-functions-from-a-c-dll-in-delphi) about it.

**Comment by michaeltryby** [comment]
The article above demonstrates that it’s possible to use ‘__cdecl’ when calling a C dll from Delphi. That is how the cmake dll is currently set up. I would be surprised if there isn’t a way to link with Delphi using the import lib cmake generates.

**Comment by michaeltryby** [comment]
Lastly, what about the new UI? The import lib and dll generated using the cmake build are used to produce python packages for the new UI. 

IMO, it’s fine for there to be two dll builds to serve the different applications in which epanet is being used.

**Comment by LRossman** [comment]
In the Delphi GUI source code I simply replaced each occurrence of `stdcall ` in the _epanet2.pas_ file (it declares the signature of each DLL function that the GUI uses) with `cdecl` and re-compiled the GUI. The resulting _epanet4w.exe_ now works with the cmake DLL. Maybe this issue can be resolved by just providing documentation on which build system works best with which types of applications.
