### ISSUE TITLE
Problems with `test_net_builder()`

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/EPANET#286]
Intermittent problems with `test_net_builder()` present in CI server [logs](https://ci.appveyor.com/project/OpenWaterAnalytics/epanet/build/2.0.209/job/7e80vuqsnv4flals).

Could be a problem with the test or with net_builder API.

**Comment by eladsal** [comment]
@michaeltryby very strange. These fails come and go. The two last commits gives different errors ([here](https://ci.appveyor.com/project/OpenWaterAnalytics/epanet/build/2.0.210/job/56ar1trg4ir7yih5#L382) and [here](https://ci.appveyor.com/project/OpenWaterAnalytics/epanet/build/2.0.209/job/7e80vuqsnv4flals#L381)) while in the [third](https://ci.appveyor.com/project/OpenWaterAnalytics/epanet/build/2.0.208/job/jhqsit3g8bfjcwhf#L365) there is no problem with this test.

I just [forked](https://github.com/eladsal/EPANET-ES) the project and this test [passes](https://ci.appveyor.com/project/eladsal/epanet-es/build/2.0.1/job/80s8nk5cp6d74w2g#L363).

**Comment by michaeltryby** [comment]
I have been working on cleaning up the unit tests. Today I have been focusing on the net builder tests. I wrote the following simple test case:

```
BOOST_AUTO_TEST_CASE(test_init_close)
{
	std::string path_rpt(DATA_PATH_RPT);
	std::string path_out(DATA_PATH_OUT);

	EN_Project ph = NULL;
	EN_createproject(&ph);

	int error = EN_init(ph, path_rpt.c_str(), path_out.c_str(), EN_GPM, EN_HW);
	BOOST_REQUIRE(error == 0);

	error = EN_close(ph);
	BOOST_REQUIRE(error == 0);

	EN_deleteproject(&ph);
}
```

When I build and run this test case in debug configuration I get a memory leak. This means that all the memory being allocated isn't being cleaned up. I believe this problem is related to the Issue I noted earlier about memory leaks when saving and reopening an input file. 

Does anyone want to take a stab at fixing this?

**Comment by LRossman** [comment]
@michaeltryby I will take a look at it, but without using the BOOST library. I ran debug leak detection tests on the dynamic comment string commit I just made (which helped me fix some things along the way).

**Comment by michaeltryby** [comment]
@LRossman I am doing the same. So far the `curvedata()` and `addpattern()` are getting flagged.

**Comment by LRossman** [comment]
Adding the following lines to `EN_init()` in epanet.c will fix the leaks you mentioned:
```
    // Initialize the default demand pattern
    p->parser.MaxPats = 0;
    getpatterns(p);

    freeTmplist(p->parser.Patlist);      //new line
    freeTmplist(p->parser.Curvelist);    //new line
```
There's a remaining 3 leaks of 8 bytes each which are listed but without file names and line numbers which is very frustrating :angry:.

**Comment by LRossman** [comment]
I found the source of the remaining leaks. It's in the lines that are marked below:
```
        std::string path_rpt(DATA_PATH_RPT);  //*****
	std::string path_out(DATA_PATH_OUT);  //*****

	EN_Project ph = NULL;
	EN_createproject(&ph);

	int error = EN_init(ph, path_rpt.c_str(), path_out.c_str(), EN_GPM, EN_HW);
```
If you replace them with the following then there are no more leaks:
```
	EN_Project ph = NULL;
	EN_createproject(&ph);

	int error = EN_init(ph, DATA_PATH_RPT, DATA_PATH_OUT, EN_GPM, EN_HW); 
```

**Comment by michaeltryby** [comment]
Great work!  Looks like there are still more leaks though. I identified one in `getcurves()` while running `test_demand_categories.cpp`.

**Comment by michaeltryby** [comment]
Getting periodic segfaults when running `test_demand_categories()`

**Comment by LRossman** [comment]
The contributing factor to this leak and the previous one found for Patterns is the use of the `Tmplist `structure to temporarily store pattern factors and curve data points as they are read from an input file. After the file reading is done the values in the `Tmplists  `are transferred to the permanent `Spattern `and `Scurve `data structures in the `getpatterns `and `getcurves `routines. The code for doing all this is unnecessarily convoluted. I'd like to rewrite the input file reader to eliminate the use of `Tmplist `and just use `realloc `to expand the size of the pattern and curve data arrays in their respective `Spattern `and `Scurve `structures as their values are read from a line of input. Sound good?.

**Comment by michaeltryby** [comment]
Identified a memory leak at `EN_addnode()` line 1679.

**Comment by michaeltryby** [comment]
> BTW, to eliminate the memory leaks from EN_addnode() do the following:

> After line 1796 add the line: node->D = NULL;
> After line 1822 add the line p->parser.MaxNodes = net->Nnodes;
> At line 404 of project.c, replace j = 0 with j = 1.
