### ISSUE TITLE
Updating Draft Release Notes after Each Merge

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#289]
I suggest that the Draft Release Notes for whatever the current `dev` version is (currently [here](https://github.com/OpenWaterAnalytics/EPANET/blob/dev/ReleaseNotes2_2.md)  here for v. 2.2) be updated after each merge by the person contributing the PR if it involves adding/changing a feature or a major bug fix. This will provide an easier way to keep track of what significant changes have been made to the project all in one place. Since the "Notes" is just a working draft one need not be too concerned about its format which can be edited and "cleaned up" as need be for final release.

**Comment by LRossman** [comment]
I use [StackEdit](https://chrome.google.com/webstore/detail/stackedit/iiooodelglhkcpgbajoejffhijaclcdg?hl=en) running in my Chrome web browser. When I make code changes I also edit the Release Notes file accordingly and include it with my commit.

**Comment by dickinsonre** [comment]
This may not be the right place for this link but I saw a good article on Medium which combined Python and Travis so I thought I would mention here if you want to add Travis documentation
https://towardsdatascience.com/10-steps-to-set-up-your-python-project-for-success-14ff88b5d13
