### ISSUE TITLE
 'TmpDir' undeclared

### ISSUE THREAD

**Issue by mauriziocingi** [OpenWaterAnalytics/EPANET#3]
function getTmpName (line 1710 of epanet.c) refers to TmpDir.
TmpDir was once declared in vars.h (line 30) but now is  part of struct OW_Project
(line 603 of types.h)

epanet.c:1710:23: error: 'TmpDir' undeclared (first use in this function)

function getTmpName needs some rewriting (i.e. add pointer to OW_Project in calls)

**Comment by mauriziocingi** [comment]
It is about owa_obj branch

**Comment by mauriziocingi** [comment]
A (maybe) better solution:
- TmpDir is not really in use, it is padded with an empty string and never modified.
- tmpnam function  already prepends dir name (as defined in TMP and TMPDIR environment variables, on linux platforms, if TMPDIR is not set, a default temporary directory, usually /tmp or /var/tmp, is used.)
- TmpDir may be discarded from OW_Project struct and lines used for prepending TmpDir deleted (TmpDir is not Project-related value, it is an environment variable)

**Comment by samhatchett** [comment]
good catch. I have not attempted to compile this on windows, so this never showed up. 

i agree with the assessment that TmpDir is never used. we should probably remove it from the project struct and this particular block.

**Comment by samhatchett** [comment]
this issue refers to deprecated code, so i'm closing.
