### ISSUE TITLE
How do we calculate Time of water from node i get to node j

### ISSUE THREAD

**Issue by linkhochon** [OpenWaterAnalytics/EPANET#301]
Hi everyone , 

I'm a beginner in epanet,  I have a water network in epanet ,I want to have this:

How long does it take to get water from a pipe and get out of it?
Or 
How long does it take to get water from node i to node j?

I don't know which command I should use, can I calculate this time in epanet?

Can anyone tell me what to do?

Thanks

**Comment by michaeltryby** [comment]
@linkhochon issues on github aren't meant for user support. Send me an email and I would be happy to help you with your question.  :smile:
