### ISSUE TITLE
Possible bug in EN_setlinktype

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#305]
There seems to be a bug in `EN_setlinktype` in the following code where `i` is the index of the link whose type is being changed:
```
  if (toType <= EN_PIPE) {
    net->Npipes++;
  } else if (toType == EN_PUMP) {
    net->Npumps++;
    net->Pump[net->Npumps].Link = i;
  } else {
    net->Nvalves++;
    net->Valve[net->Nvalves].Link = i;
  }
```
It seems that while the number of pumps or valves is increased by 1, the `Pump` and `Valve` arrays are not re-sized to accommodate the new entry. Also, if a pump or valve is changed to another type, the corresponding entry in these arrays is not deleted.

**Comment by milad-ghiami** [comment]
why we increase pump and valve number  but do not increase valve number

`
 if (fromType <= EN_PIPE) {
    net->Npipes--;
  } else if (fromType == EN_PUMP) {
    net->Npumps--;
  }
`
