### ISSUE TITLE
ENgetheadcurve should be changed to ENgetheadcurveindex

### ISSUE THREAD

**Issue by eladsal** [OpenWaterAnalytics/EPANET#31]
I think that `ENgetheadcurve` should be changed to `ENgetheadcurveindex`. Now the function returns the curve ID and not the index. Users needs to know the head curve if they want to read or write it's values. In both cases they need the index of curve, not the ID.

Also, this is how other functions work. As this being a new function we don't have backward compatibility issues yet.

See function [here](https://github.com/OpenWaterAnalytics/EPANET/blob/dev-2.1/src/epanet.c#L2767)

**Comment by eladsal** [comment]
I'll take this as a silent vote and make the change.

**Comment by samhatchett** [comment]
+1
