### ISSUE TITLE
Bug in adding multiple pumps using the net builder functions

### ISSUE THREAD

**Issue by AbelHeinsbroek** [OpenWaterAnalytics/EPANET#314]
When adding multiple pumps with different pumping curves **using alternative units (EN_CMH)** the pumps are not initialized correctly, leading to wrong results.

When saving and reloading the input file the model runs correctly.

Attached a test file to illustrate the problem, which gives the following output:

```
Running 1 test case...
Generated Network has Error 4 
Flow from pump1: 0.000000 
Flow from pump2: 319.220642 

  o Retrieving network data
Flow from pump1: 173.619370 
Flow from pump2: 253.737518 
```

[test_multiple_pumps_cmh.cpp](https://github.com/OpenWaterAnalytics/EPANET/files/2505888/test_multiple_pumps_cmh.txt)

**Comment by LRossman** [comment]
This has been fixed in PR #320 and passed the unit test prepared by @AbelHeinsbroek .
