### ISSUE TITLE
VB.NET (and other languages) support and documentation

### ISSUE THREAD

**Issue by samhatchett** [OpenWaterAnalytics/EPANET#32]
I'd like to get some discussion about VB.NET support - which apparently is a popular way to access the toolkit. Is there conceptually any difference between what we do with regards to VB.NET declarations and other interface wrappers like Python and MatLab?

Because if the difference is thin, I would propose detangling the project a bit and gathering these language bindings into a subunit of this repository (or move to another repo) to create a better logical division between these concerns. From earlier discussions, it seems like VB.NET users won't really be comfortable with all the C language specifics --- same for Python users etc...

A related question would be if the C API reference docs to be generated for the core library will be sufficient for users of language bindings. And I suppose the answer depends on the specifics; if the language binding layer is really just a straight-through function-for-function translation unit, then the added documentation needs will be minimal. However for something like an object-oriented abstraction library in Python, there's not necessarily a one-to-one mapping and that might need its own doc set.

Thoughts and comments?

**Comment by eladsal** [comment]
I would not say VB.NET is a popular in using EPANET. From the .NET family C# is the most common one. VB.NET does not need a real wrapper just a header file which we have in the include folder.
