### ISSUE TITLE
CI regression tests prevent making any improvements to progress/error/warning reporting

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#323]
The CI regression tests seem to fail when they detect a difference in the way error and warning messages are displayed both in the Status Report file and, evidently, on the console. Having just removed the anachronistic `writecon `function I would like to replace the main program stub for the runnable version of the API with one that displays progress messages using a `pviewprog `function passed into either `ENepanet `or `EN_runproject`. However under the current CI it will never pass. Likewise, the error and warning messages written to the Status Report through `geterrmsg `should display the corresponding error number. Making this change will also cause CI tests that produce warnings to fail.

**Comment by michaeltryby** [comment]
@LRossman Make the changes are we can update the benchmark.
