### ISSUE TITLE
initial doxygen markup, doc set generation

### ISSUE THREAD

**Issue by samhatchett** [OpenWaterAnalytics/EPANET#33]
tracking doxygen markup in `doxy-trial` branch. I will volunteer for this issue - it really just involves copy/paste/format work.

related to #14 / follow-on to #24

**Comment by eladsal** [comment]
Thanks. If you can get the help file text into the docs it would be great.

**Comment by samhatchett** [comment]
API docs are implemented as of 90c2dfa0c4fb3f1d71cc8ce0199209e41234635c -- still need to copy over overview, input/output file specs, and example code.

**Comment by eladsal** [comment]
Just noticed that Marios Kyriakou updated the [Wiki](https://github.com/OpenWaterAnalytics/EPANET/wiki/Toolkit-Functions-by-Task) with all the APIs docs from the Toolkit help file, thanks.

**Comment by samhatchett** [comment]
done in  0c08bf9
