### ISSUE TITLE
Is ENclose missing a call to EN_deleteproject?

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#330]
When the legacy API functions are used, a default project is created with a call to `EN_createproject `in either `ENopen `or `ENinit`. This allocates both memory and an error manager to the project. When an analysis is completed the API client would call `ENclose`, which simply calls `EN_close`, to reclaim all memory allocated to the network objects created for the default project. However, there is no call after that to `EN_deleteproject ` to free the memory allocated to the project and close the error manager.

Can someone please check that this is indeed a bug. If it is, then the fix is simply to add `EN_deleteproject(_defaultModel)` to `ENclose `.

**Comment by Mariosmsk** [comment]
`EN_createproject` & `EN_deleteproject` does not exist in DLL file. Maybe we need to include these functions in `epanet2.c` ?

**Comment by LRossman** [comment]
@Mariosmsk I think you mean to say the creation and deletion functions don't appear in the legacy version of the toolkit, that is the functions defined in _epanet2.h_ that all begin with `EN` and not `EN_`. The reason is that the single threaded legacy-type functions use a predefined global Project Handle (`_defaultProject`) declared at the top of `epanet2.c`. Thus there is no need to use functions to create or delete it.

The original issue raised here is no longer relevant so this issue can remain closed.
