### ISSUE TITLE
Notion of Toolkit API versioning

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/EPANET#333]
I have been thinking about how we can structure the Toolkit API to manage it a little better. It has grown significantly in size and contains duplication of functions to provide backward compatibility. Backward compatibility is a good thing. We also want to be able to move forward and create new API without inadvertently breaking things. There is a structured solution to these problems and that solution is called versioning. 

I would argue that the main reasons the Toolkit API has become so large and disorganized is because several generations of the API are all jumbled together. Let's call the original API version 2.0. OWA added functionality and created version 2.1. The toolkit API was heavily refactored to provide thread reentrancy and still more functionality was added creating version 2.2. The needs of integrating the UI with the engine will necessitate changes and will culminate in API version 2.3. 

I think if we incorporate the idea of versioning into the organization of the Toolkit API we can get a handle on these issues and move forward. Thoughts?

**Comment by LRossman** [comment]
As I've noted many times before, building next versions of the API on the old and crumbling foundation of the EPANET 2.0 C code is counter-productive. It's time to move on to a complete modernization and re-design of the engine. Please [click here](https://github.com/OpenWaterAnalytics/next-net/files/2128973/EPANET.3.White.Paper.pdf) for one possible approach.

**Comment by michaeltryby** [comment]
@LRossman I guess I should have been more clear, I am talking about the EPANET v 2.2 release currently being finalized.  

It would be great to more forward on the next version of EPANET. When ever you are ready feel free to update OWA/epanet-dev with your latest work. We are all looking forward to seeing it.

**Comment by michaeltryby** [comment]
The scope of this task is to refactor the EN* and EN_* API's into separate header and implementation files.

**Comment by michaeltryby** [comment]
@eladsal I'm going to put together a PR on this today. I would be happy to appoint you as a reviewer if you are interested / have time. Thanks.

**Comment by eladsal** [comment]
I'm not sure yet what this issue is really about but will take a look. As far as I know we kept backward compatibility so do we really need versioning now? Are we going to break it, is that the plan?

**Comment by michaeltryby** [comment]
@LRossman and @eladsal It's easy enough to change the name of the library in the cmake build and the header files have already been set up to include `epanet_exports.h` only when `WITH_GENX` is defined. So what exactly is the issue here?

**Comment by LRossman** [comment]
The first issue is that DLL and LIB names have to be compatible between builds. Another is that having to re-edit the source code of legacy C toolkit apps to add the `#include epanet_exports.h` is an added (and unnecessary) burden, as opposed to just recompiling the original source code without having to make any changes to it.

**Comment by michaeltryby** [comment]
@LRossman Look I'm confused. I made `epanet_exports.h` opt in. It gets ignored by default, therefore, legacy C toolkit apps don't have to be edited and they don't have to add anything. Do you understand? 

Please explain how this is a burden?

**Comment by LRossman** [comment]
@michaeltryby have you tested this on legacy C code? Can one just leave the old code alone, with its use of the old `epanet2.h` header, and just re-compile with the new epanet2.lib file?

**Comment by michaeltryby** [comment]
@LRossman have you tested it and shown that its a burden?

**Comment by michaeltryby** [comment]
@LRossman Since when are legacy epanet apps linking with `epanet2.lib`? Legacy apps use the def file. 

I figure if @eladsal winsdk build script can build the library without `epanet_exports.h` then any code written against said library certainly isn't going to require it.

**Comment by LRossman** [comment]
@michaeltryby you're dead wrong. Any client app written for MS Visual C/C++ needs to include a `lib` file in its Linker Input Dependencies in order to use a DLL. The WinSDK build doesn't generate a `lib` file and therefore can't be used as-is in a Visual C/C++ project.

The only way I can build a client app in Visual C/C++ (like the unit tests) right now is to use the files generated by the `cmake` build (`epanet.dll `and `epanet.lib`) along with adding the `WITH_GENX` preprocessor directive which requires that `epanet_export.h` be available (no `DEF` file is needed however). It appears then that for legacy apps no code editing is required - just that some existing files be replaced or added to the app's project directory after which the app gets rebuilt.

**Comment by michaeltryby** [comment]
@LRossman Visual Studio provides a lib tool that can be used to convert a `def` file into an import `lib` file. So a dll built using the WinSDK script or cmake are functionally equivalent or can be made so. Like I said `def` / `lib' six and one half dozen of the other.
