### ISSUE TITLE
Existing EPANET GUI help is broken on Windows 10

### ISSUE THREAD

**Issue by samhatchett** [OpenWaterAnalytics/EPANET#34]
I'm hearing some reports that the .chm help file is broken in Win10. Can anyone confirm / share a screenshot or error message?

This issue might elevate our document generation urgency if true. It would be nice to support these folks.

**Comment by eldemet** [comment]
If I'm not mistaken this was an issue with Windows 7 and possibly with
Vista. Here's a link describing how to fix this:
http://www.water-simulation.com/wsp/2011/11/28/how-to-open-epanets-help-file-in-windows-7/

**Comment by michaeltryby** [comment]
This is helpful but only covers up to Windows 8. Currently, there isn't a win help viewer application available for Windows 10. The rumor is that Microsoft wishes to discontinue the old help format. 

This is emblematic of our fragile support situation on EPANET right now. The current UI application was last built in 2008 using an old version of Delphi. We are very lucky that the only thing broken on Windows 10 is the help viewer. We could very easily find ourselves in a situation where there is a lapse in EPANET availability for newer versions of Windows.

**Comment by eladsal** [comment]
I'm optimistic regarding EPANET's compatibility on new versions of Microsoft Windows. I have learned that there is a large difference between Microsoft's statements and reality. Delphi builds almost don't relay on Windows system and run-time files, they are stand alone. You can just copy-paste EPANET on Windows, no need for running the setup.

Same goes for the help file. I got my hands on two Windows 10 machines, downloaded the Toolkit files from the EPA's website and opened the CHM help file with no real issues. I should note that this is on machines which were upgraded from Windows 7 or 8, not a clean Win 10 install but it runs well.

Can anyone provide more information about the problems people are facing with the help file?

This is on Hebrew locale machine:
![epanet-toolkit-help-file- on-win-10_1](https://cloud.githubusercontent.com/assets/1942312/10189062/b6f7fb68-676c-11e5-96db-2348f14e76fc.png)

and this is on an English one:
![epanet-toolkit-help-file- on-win-10_2](https://cloud.githubusercontent.com/assets/1942312/10189063/b6f86710-676c-11e5-9bc5-a1baddab4007.png)

**Comment by michaeltryby** [comment]
@eladsal I have received two reports from users unable to launch help from the EPANET UI application. I am NOT talking about toolkit help.chm. I believe the EPANET UI help is an older format .hlp that is now unsupported, but I have no way to test this. Can you do me a favor? Run the EPANET UI on Windows 10 and try to launch the help application from the help menu and report what you find. I would really appreciate it. Thanks.

**Comment by eladsal** [comment]
@michaeltryby will do.

**Comment by samhatchett** [comment]
i misunderstood initially, so i updated the issue title to reflect this info. thanks @michaeltryby

**Comment by eladsal** [comment]
@michaeltryby I can confirm that Windows 10 does not support viewing older help files (hlp). However there is solution. I have posted it [here](http://www.water-simulation.com/wsp/2015/10/01/how-to-open-epanets-help-file-in-windows-10/).

If users face any issues you can ask them to post it there as a comment and I will try to help.

![epanet-help-file-on-windows-10](https://cloud.githubusercontent.com/assets/1942312/10219150/19502c44-6845-11e5-9bae-41367ed84deb.png)

**Comment by eladsal** [comment]
I have some users confirm the workaround with no users reporting a problem so I'm closing this issue.
