### ISSUE TITLE
Decide where to perform code cleanup?

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/EPANET#342]
Code housekeeping has the potential to be disruptive to ongoing development activities in the dev branch. Would it make more sense to perform cleanup activities in a different branch to avoid disrupting other peoples work?  

As I wade into this, it immediately seems like some issues have the potential to be more disruptive than others.

**Comment by michaeltryby** [comment]
Please weigh in if you have any objections to code cleanup occurring in the `dev` branch.

**Comment by LRossman** [comment]
@michaeltryby my dev commit from two weeks ago, whose PR I cancelled at your request, essentially does everything you proposed in Issues #343 to #346. I'm ready to submit it again if given the go-ahead.

**Comment by michaeltryby** [comment]
@LRossman Yes, your PR was fine., We just need to coordinate better so we aren't working at cross purposes.

**Comment by michaeltryby** [comment]
Let's give our fellow developers a chance to weigh in. If they don't care enough to respond, that is considered tacit approval to move forward.

**Comment by michaeltryby** [comment]
@LRossman I don't believe your previous PR rolled back the error manager. Unless you have an objection, I will go ahead and create a PR that covers #344.

**Comment by LRossman** [comment]
@michaeltryby OK roll it back. I will wailt for a new dev to appear before merging my previous commit into it and creating a new PR.

**Comment by eladsal** [comment]
I'd rather have everything on the `dev` branch. If we are approaching a release time we should limit the somewhat "dramatic" changes to the code. It's hard keeping up with all these structure changes, declaration movements, file breaks and so on....

**Comment by LRossman** [comment]
@eladsal I appreciate your concern about making major code cleanup at point in time. However, I strongly believe that v.2.2 should be the end of the line for the 2.x versions of EPANET. And even if this were not the case, I believe that the code should be made as consistent (such as in naming conventions) and readable as possible for outsiders who will be seeing it for the first time when it gets released. This may not seem too important to you since you have been working with it for so long now, but when I first looked at the code closely in May I was taken aback by the lack of consistent naming and coding style conventions (which got me in trouble when I raised an issue about it). All I know is that if this were my own personal project I would not want to release the code as it stands now (even though it works perfectly well) without making the cleanups being proposed.

**Comment by michaeltryby** [comment]
@eladsal we are approaching release, and "dramatic" changes are being proposed. Thus, we are proposing doing the work in another branch.

**Comment by michaeltryby** [comment]
@LRossman I respectfully disagree. The state of the code is not ideal but it is acceptable. This is what projects are like when more than one person works them. It comes with the territory of collaborating with other developers.

**Comment by LRossman** [comment]
What we're arguing about seems so trivial. The cleanups have already been made on a local copy of dev. They make the code appear more consistent and easier to digest. They don't affect the numerical results (thanks to @michaeltryby 's reg tests). Aside from replacing the void project pointer (which everyone agreed to) they simply add a uniform header to each code module, remove outdated comments, and apply a more consistent naming to the sub-struct aliases that appear in almost every function. There's also the breakup of the API module (epanet.c) into two modules, but again, this seems pretty innocuous.

**Comment by michaeltryby** [comment]
@LRossman Do you understand that I don't want the sub-structs rolled back? I can't speak for @samhatchett, but I don't suppose he does either. 

That said, I don't have a problem with the other changes you are proposing.

**Comment by eladsal** [comment]
@LRossman I don't appose, it was more of a suggestion or remark.

@michaeltryby because we are approaching a release I rather have everything in `dev`.

**Comment by LRossman** [comment]
Just to clarify, I have two cleanup updates waiting in the wings, one with the project sub-structs left intact and one with them removed. I suggest leaving the sub-struct decision to a vote under #347.

Otherwise it sounds like we all agree to implement the other cleanup changes in dev, once @michaeltryby merges his rollback of the error manager into it.

**Comment by michaeltryby** [comment]
@LRossman The PR rolling back the error manager has been merged.

**Comment by LRossman** [comment]
Thanks @michaeltryby . I will begin to locally merge my cleanups with the new dev, waiting to see what the outcome of the vote on #347 will be before committing anything.

**Comment by LRossman** [comment]
@michaeltryby I am ready to work on updating the `dev` branch with my code cleanup changes but am confused on what to do about the commits you made to _OpenWaterAnalytics:release_. Where is this branch (it doesn't show up on the Branches dropdown list)? From the PR info for #334 I can see the updates you made, like breaking _epanet.c_ into two files, removing the void project handle, etc. but these haven't been merged into `dev`. I'm stuck as how to proceed. Please advise.

**Comment by michaeltryby** [comment]
@LRossman Don't worry about my release branch it's dead now. I am preparing a commit for the API versioning stuff once your code cleanup PR gets merged. Does that get you unstuck?

**Comment by LRossman** [comment]
@michaeltryby yes, I'm good to go now 🙂. Thanks and enjoy your holiday.

**Comment by michaeltryby** [comment]
Thanks @LRossman you too!

**Comment by LRossman** [comment]
Will submit the cleaned up code tomorrow. I am adding headers to all of the EN_xxx functions (a few already have one) to make the code more readable. With about 100 functions this takes a bit of time.

**Comment by michaeltryby** [comment]
@LRossman just a suggestion, but you could update documentation in a separate PR.

**Comment by LRossman** [comment]
In-code documentation has been completed as has the code cleanup. I just need to run my local tests to make sure that I didn't break anything. Should have a PR ready by this afternoon.
