### ISSUE TITLE
Remove sub-structs from the EN_Project declaration in TYPES.H

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#347]
`EN_Project `is formed from a number of sub-structs  (like `hydraulics_t, time_options_t, parser_data_t,` etc.) that make the ensuing code more verbose and more difficult to work with. I propose to eliminate these sub-structs and just place all of their contents directly into `EN_Project`. This would allow these variables to be addressed as simply pr->xxx throughout the various code modules. As an example, instead of using the following :
```
    time_options_t *time = &pr->time_options;
    ...
    time->Htime
```
one would simply use `pr->Htime`, thus eliminating the need to define a host of aliases for the sub-structs in almost every function. And in this example, my proposal also eliminates the need to remember if `Htime `belongs to` time_options_t` or to `hydraulics_t` (strictly speaking, `Htime `isn't really an option).

**Comment by michaeltryby** [comment]
The proposal seems like the C equivalent of having one "God object" that holds everything. As you know in object oriented design this is poor practice. If anything, I can see these structs being refactored and broken down more to improve run time software performance. The current memory layout does not effectively utilize processor cache and as a result a lot of the wall time is actually being spent fetching variables from memory for each computation.

**Comment by samhatchett** [comment]
agree with @michaeltryby - I originally broke the god-obj apart to make the internal function calls more OO, so that instead of passing the entire project pointer around, you just give the function what it needs to operate on (like time functions would just need `time_options`). There ends up being more dependencies within many of the functions that make this trajectory not very easy. But there it is, that was the intention.

**Comment by LRossman** [comment]
@michaeltryby the sub-structs contained in EN_Project should not be confused with objects. They only serve to break up the `EN_Project `struct into a bunch of smaller ones that add an additional level of indirection when having to address their contents. I submit that accessing `Htime `through `pr->Htime` is faster that `pr->time_options.Htime` since there is one less memory offset to compute. In reality, the `EN_Project `struct is nothing more than a replacement for the global variables that used to appear in the `vars `header of EPANET 2. Adding the sub-structs to it just obfuscates the code and makes it less efficient.

@samhatchett I appreciate your intent, but the fact remains that we should call `EN_Project `what it is -- a thread-safe replacement for a collection of global variables. Your idea to just pass functions only the sub-structs they need to access was never really implemented in the code since (with just a few exceptions) all of  the functions have the full `EN_Project `pointer passed into them. Thus your argument for breaking up `EN_Project `into a bunch of sub-structs sort of falls apart and we're left with having to define a bunch of aliases in each function to make it syntactically easier to address our "global" variables.

**Comment by michaeltryby** [comment]
@LRossman the overhead of a pointer deref is practically negligible. On the otherhand, there is a large overhead associated with having one large struct sitting in memory. We should push forward and continue to target memory access to only what is needed for the computation occurring in each function.

**Comment by samhatchett** [comment]
I should also add that the current state of the code does not reflect every opportunity to restrict what is passed into each internal function. The breaking-apart was a first cut and there was a brutal process of find-and-replace to get the project pointer stuffed into each function. From there, there is great potential to investigate function-by-function to determine what each one actually uses, and refactor it to only receive what is necessary. That is most certainly an OO paradigm.

**Comment by LRossman** [comment]
I don't understand why the overhead of the one large struct in memory is relevant. I believe that almost every piece of `EN_Project` needs to be in memory for the program to function. 

Pushing towards breaking up the dependencies of functions on the variables in `EN_Project` is a fine idea for the next generation (3.0 OO) re-write. I am looking at things from the standpoint that v.2.2 is the last of the 2.x versions so the code should be made as readable and efficient as we can make it within its current overall design. So ask yourself this question - what do the sub-structs of `EN_Project` really add to the code **in its present design**?

**Comment by samhatchett** [comment]
I think it improves readability, even in its current form.

**Comment by LRossman** [comment]
So

    time_options_t *time = &pr->time_options;
    ...
    time->Htime

is more readable than
```
    pr->Htime
```
? There's also the issue that the aliases used for the sub-structs are not consistent between functions. E.g. both` time`, and` ti` are used for `pr->time_options` in various places. Aliases for `EN_Network `appear in 186 functions, for `hydraulics_t` in 112 functions, and so on. They can all be eliminated by simply using the passed in project pointer `pr` to de-reference the variable in question. Why make the code any more bloated than it needs to be.

**Comment by michaeltryby** [comment]
@LRossman if this is the end of the line for v2.2 then why bother? Rolling this back is more trouble than it is worth if all we are talking about is readability and design style.

[Here](https://en.wikipedia.org/wiki/CPU_cache) is an introductory article that explains cache. I have been examining the code and memory latency is one of the issues that the performance tools have flagged.

**Comment by LRossman** [comment]
@michaeltryby I still don't understand your point. The sub-structs are all included in EN_Project, making it in effect one big struct. They are not treated as separate independent structs each occupying its own separate memory. Regarding the effort to eliminate the sub-structs, I've already done it on a local copy of dev and its ready to go.

**Comment by michaeltryby** [comment]
@LRossman I am against rolling the sub-structs back. However, there are plenty of code cleanup Issues we do agree on, so why don't we focus on those?

**Comment by LRossman** [comment]
I would like to see a vote on this since I still believe that removing the sub-structs makes for cleaner code and has no downside whatsoever. If there's a tie then I win because I'm older than everyone else. Votes must be cast by EOD tomorrow.

**Comment by LRossman** [comment]
I vote in favor of removing the sub-structs. 👍

**Comment by michaeltryby** [comment]
Very funny @LRossman! 😆 @samhatchett do you care to chime in with the OWA procedure on voting?

**Comment by michaeltryby** [comment]
> We should push forward and continue to target memory access to only what is needed for the computation occurring in each function.  

I vote against removing the sub-structs. :-1:

**Comment by samhatchett** [comment]
@michaeltryby haha, we have some discussion about voting in another issue. not sure it ever got fully decided. majority-rule is generally accepted, and I think 24h is not way too aggressive (as long as we are talking _business days_ instead of weekends), but I might suggest 48h instead. I know that there are days where I don't check my GH emails, so I could imagine somebody missing this thread.

that said, I vote no 👎  on flattening the god-object.

**Comment by michaeltryby** [comment]
I'm fine with leaving this open for 48 hours. We should agree how a tie be decided?

**Comment by LRossman** [comment]
At the halfway mark of voting to remove the sub-structs from the `EN_Project` struct and instead place their contents directly into the structure the count stands at one for and two against. For those who haven't voted yet (or those who have and want to give the matter more thought) let me reiterate the case for removing the sub-structs: its saves hundreds of lines of code with absolutely no impact on how the project's data structure is either used or stored in memory (the layout of `EN_Project` in memory is the same whether it is organized with or without sub-structs).

**Comment by michaeltryby** [comment]
As you may recall, EPANET v2 was released with the entire data model in global memory space. It was a significant effort on @samhatchett  part to encapsulate and structure the data in its current form. Further work is required to better manage memory layout for improved performance. The sub-structs as they exist now, are a first step that can be built upon in future releases. Eliminating what has been accomplished thus far, will not make the code any faster or more efficient. Although I do agree with @LRossman that it will marginally improve readability. 

The premise of @LRossman argument for rolling back Sam's work is that this is the end of the line for the EPANET v2 code base -- since this is the end, we might as well tidy up. If you agree that EPANET v2 code development has reached an end this is a logical conclusion. If you believe the EPANET2 code base remains viable, however, then it makes little sense to roll back any of the work we have accomplished as a community. 

Regardless, of whether you are for or against this proposal, the time you take to consider it and vote is appreciated. Thank you.

**Comment by eladsal** [comment]
@samhatchett good point about the last vote...

I agree that in the current state, the use of sub-structs is not very good. There is no documentation for the different types (what goes where), almost all functions use the project handle and not receive only one of the types, usage is not consistent (look at `EN_init` for example).  On the other hand, I'm not old as @LRossman, and many times use a plain text editor for coding, but find it difficult to remember the names of the variables so breaking them into groups should help. If one uses these "modern" IDEs the benefit seems clear even if you just write `pr->save_options.SaveHflag = FALSE;`.

![unnamed](https://user-images.githubusercontent.com/1942312/48822611-58610300-ed66-11e8-98ef-3558bd68bc32.png)

I don't see the 2.x branch ending just yet so we may have a chance to improve the use of the sub-structs. **I'll vote to keep them**.

I don't know why but with these discussions i feel that I'm holding the project somewhat from progressing. Sorry about that @LRossman .

**Comment by michaeltryby** [comment]
Voting is now closed on the proposal to remove sub_structs from EN_Project. The final tally was 1 vote for and 3 votes against. 

Thanks to everyone who took the time to participate. Let's move forward.
