### ISSUE TITLE
Calculation of tank flows when tank is at maximum (and likely minimum) level may not make sense

### ISSUE THREAD

**Issue by jamesuber** [OpenWaterAnalytics/EPANET#35]
Under "certain uses" of the toolkit, it has been possible to calculate adjacent tank flows when the tank is at its min/max level, that do not make sense. I've seen results where the tank is at the minimum level, and we are computing large outflows. In this case Epanet should be closing that link and thus the flow should at least be "small." Similarly I've seen tanks at their maximum level where it is actually closed, and the flows are "small", but they are small in a direction out of the tank. The tank update then sets the new tank level slightly below the maximum, resulting in a time step that is cut short. The behavior in this case should be to identify that a tank is really "closed" when updating its level, and just not update it.

**Comment by eladsal** [comment]
Is this with the OS version of the toolkit or version 2.0.12 (or both)?

Can you post a sample network to demonstrate this issue?

**Comment by eldemet** [comment]
I think I have witness this bug on network of a real system. I remember
having the same thoughts as Jim. It was with the 2.0.12 version. I'll try
to find it and see if I can replicate it.

d

**Comment by jamesuber** [comment]
Yeah that’s the thing - I was caveating my statement because this is based on a branch (samhatchett/OWA_netbuilder) that has some experimental features built in that will “probably” make their way to a milestone at some point. And I’d also say that it involves using the toolkit in a non-standard way. Actually it’s how Epanet-RTX uses Epanet.

But anyway, despite all of that, it is still using the standard Epanet netsolve and tank updating routines, and I’ve no explanation for why it shouldn’t “figure this out.” Just something to look into while in the midst of a future re-routing of algorithms. It would be interesting if you could demonstrate using the standard toolkit usage or even in the UI with a simple system.

-Jim

JIM UBER <mailto:jim@citilogics.com>  •  513.368.6303 <tel:513-368-6303>  •  CITILOGICS.COM <http://www.citilogics.com/>

**Comment by accumodel** [comment]
When it comes to Tanks, I always make sure that I have a control in place that shuts off the source to a Tank before it fills to 100% and turns the source on before it is completely empty.  In many cases this is a pump station that fills the tank.  

I suppose that in an actual system, the only 'normal' situation where the tank would go completely full (i.e. overflow) would be in the case that it is fed by a spring.

The only situation I can think of where you would allow a tank to reach its minimum level would be when you are stressing the system to see where it breaks or if you are sizing a tank in the model.

Either way @jamesuber, I suppose that the issue are seeing needs to be fully investigated.  If you want another pair of eyes, I would be happy to look at the model and give you some feedback.

**Comment by jamesuber** [comment]
@accumodel with regards to implementing those controls I think that's a good idea but it also sounds like additional overhead on the user that shouldn't be required? 

Actually I've never been a fan of the way Epanet removes the tank from the system when it is overflowing. I think it's more physically correct if that tank is overflowing then just let it, and simply set the head to the overflow elevation when doing the level update. This will probably ease the hydraulic calculations somewhat, since it's not nearly so abrupt a hydraulic change compared to shutting off the tank, plus it's an easy thing to do in comparison to examining the flows with and without the tank connected, and having to make determinations of what constitutes a "small" flow (this is what leads to the very small time EPS time steps in my original post). As for what happens when the tank drops below a minimum, I'd actually advocate having the simulation just stop at that point with a clear error message about the offending tank. Again, it is physically realistic (i.e. we haven't *specified* that the tank is to be shut off in that case), and it simplifies the EPS tank updating logic. 

This sort of behavior would also encourage people to use controls of the type that Mark uses and is advocating for to stop the tanks from overfilling or underfilling, and more importantly it would make those controls explicit to the user. 

This could also be presented as a sort of global or tank-specific option, to automatically place the controls on tank max and/or min. 

All this would be tantamount to moving all the logic associated with tank max and min levels, and placing that with the controls logic. Which I think makes sense.

**Comment by accumodel** [comment]
@jamesuber +1 on Tank overflow option.  Innovyze's InfoWater has this option now.  I think you can set the behavior individually per Tank on its properties.  It is set to not overflow by default.  I think it will also track volume of spillage I believe.  I never played around with it while I worked there and don't have access to it now to verify.

I will have to think about your suggestion in regards to stopping the simulation when a Tank is under-filled.

**Comment by eladsal** [comment]
We are going to keep this issue open so I'm going to mark it for 2.3.
