### ISSUE TITLE
Make the re-entrant API function arguments double precision

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#365]
Is there any merit to declaring the floating point arguments in the re-entrant version of the 2.2 API (i.e., the `EN_xxx` functions) as `double` instead of `EN_API_FLOAT_TYPE`? Since these functions now reside in a separate header it would eliminate the need for clients to `#define EN_API_FLOAT_TYPE` in their code when they want to use double precision throughout. Also, the library wouldn't have to be re-complied to support double precision. Some minor modifications to the legacy API functions that serve as "getters" would be needed to re-cast the value they return to EN_API_FLOAT_TYPE.

If the re-entrant version of the API is the preferred one to use moving forward then I think this proposal produces a cleaner interface for clients to work with and eliminates the need to create separate versions of it. Do others agree with this? Have I missed some unintended consequence?

**Comment by eladsal** [comment]
@LRossman sould that effect VB\VBA Single type variables?

**Comment by michaeltryby** [comment]
@LRossman coming at the question from a different direction, what is it about the Toolkit API that demands double precision real numbers? The quantities EPANET simulates - pressure, flow, concentration - are only measurable to 2 or 3 decimal places of precision in the real world. As you well know, more decimal places does not mean more precision, although it is often taken as such. 

I'm all for a clean interface. Let's make them all floats.

**Comment by LRossman** [comment]
@michaeltryby since EPANET uses `double `in its internal data model and for all of the computations made with it, it seems logical to provide an interface that uses `double `as well. The default `float `used in the current interface results in a layer of casting which, IMHO, makes things less cleaner. Also, modern FPU's are optimized for doubles and I think most developers choose to use double precision math in their numerical apps (I know I do).

Put another way, if the toolkit didn't exist and we were starting over from scratch wouldn't we use doubles in the interface? The `EN_xxx` family of functions gives us the opportunity to do that while not affecting backward compatibility with the `ENxxx` functions.

**Comment by michaeltryby** [comment]
@LRossman I mostly agree with you. One thing to consider are vector instructions that we don’t currently use. Modern processors can perform floating point operations on two doubles or four floats per cycle. Therefore there is a trade off between precision and speed. Given the precision requirements of our application, EPANET might be a good candidate for vectorization.
