### ISSUE TITLE
standardize build files

### ISSUE THREAD

**Issue by samhatchett** [OpenWaterAnalytics/EPANET#38]
a question: how many (and which) build environments should we support within this project? so far, we have various build files for MSVS, CMake, MingW, Xcode, and Make. should this be simplified for easier maintenance? or are there enough interested parties that can maintain all these configurations? I understand that CMake was invented to try to handle this situation exactly...

**Comment by samhatchett** [comment]
related to #15

**Comment by eladsal** [comment]
I'm going to support the Windows build files [here](https://github.com/OpenWaterAnalytics/EPANET/tree/dev-2.1/build/WinSDK). I think this is what you refer to as `Make`.

**Comment by samhatchett** [comment]
Make is a Linux tool. I did forget to post the bat files you set up though. Have you looked at cmake? It will auto-generate build files for almost any tool chain.

**Comment by michaeltryby** [comment]
@samhatchett  I'll second CMake. It seems like the right tool to help maintain native build workflows on multiple platforms.

**Comment by samhatchett** [comment]
CMake might be considered "yet another dependency" or hurdle since you have to download the tool to generate build files for your platform -- this sort of thing tends to be somewhat controversial with the epanet project. Of course, a simple user who downloads the pre-built command-line / library package of epanet for their platform will (as always) have no external deps.

Still, if you are *actually* compiling software, is this too much to ask? You would have to already have some sort of build environment set up at minimum, which means you sort of know how to use a computer... 

We don't have to have this fight right now, but I would support the idea of eventually moving all build configurations to a single master CMake file, and perhaps keep an archive of the auto-generated build files for multiple platforms as a convenience.

**Comment by eladsal** [comment]
I agree that we should aim for a one build script. If CMake is the best option then we should go for it. 

Let us mark this for 2.2 and work on #15 for 2.1 with separate scripts. The ones @eldemet and me worked on is used on Windows machines with VBA\VB6\C#\VB.NET\Matlab (these I know of).

**Comment by goanpeca** [comment]
>CMake might be considered "yet another dependency" or hurdle since you have to download the tool to generate build files for your platform -- this sort of thing tends to be somewhat controversial with the epanet project. Of course, a simple user who downloads the pre-built command-line / library package of epanet for their platform will (as always) have no external deps.

When using conda conda will take care of this, as CMake is defined as a build dependency and the corresponding conda package is downloaded. Installing conda is as easy as downloading (anaconda from [here](https://www.continuum.io/downloads)) or miniconda from here, and then running the build command

>Still, if you are actually compiling software, is this too much to ask? You would have to already have some sort of build environment set up at minimum, which means you sort of know how to use a computer...
We don't have to have this fight right now, but I would support the idea of eventually moving all build configurations to a single master CMake file, and perhaps keep an archive of the auto-generated build files for multiple platforms as a convenience.

I will be using CMake only for creating conda packages (as part of #78), I think CMake is the best choice also for cross-platform build.

**Comment by michaeltryby** [comment]
This issue was opened almost three years ago. Within the EPANET and SWMM projects CMake is now used to automate the build and unit tests on CI. Personally, I use it to build locally from the command prompt and to generate solution files for Visual Studio when I want to use the IDE. Learning CMake was a total PITA, once configured, however, it works great!  Overall it was a good choice for the project. 

If I'm not mistaken the original intent of this Issue was to standardize the project on a build system. I would argue that OWA EPANET has become a CMake centric project. Coercing our fellow developers to adopt CMake would do more harm than good. Those developers maintaining their own build script are welcome to come out of the cold whenever they are ready! :smile:
