### ISSUE TITLE
Additional API functions needed

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#383]
In order to allow the API to build a complete EPANET project from code and make multiple interactive analyses of it (as from a graphical user interface) the following additional API functions are needed:

1. `EN_gettitle` and `EN_settitle` to get and set the three strings that comprise a project's title.
2. `EN_clearreport` that clears the contents of the report file (optionally called before each new analysis is made for a project).

The latter function is needed when only the status report from the latest run neeeds to appear in the report file, such as in a graphical user interface where user's only need to see the report from the latest network analysis (as happens with the current EPANET GUI). Without this function the report file will fill up with status report's from every run made on a given project.

**Comment by eladsal** [comment]
Great idea, especially the clear report one. Do you think the title functions can just have the three strings as variables?

**Comment by LRossman** [comment]
@eladsal yes, the title functions can just use the three strings as arguments. Would you like to add those functions?

I've already coded the `EN_clearreport` and `ENclearreport` functions, which simply call the following new function added into` report.c`:
```
int clearreport(Project *pr)
/*
**------------------------------------------------------
**   Input:   none
**   Output:  returns error code
**   Purpose: clears contents of a project's report file
**------------------------------------------------------
*/
{
    Report *rpt = &pr->report;
    if (rpt->RptFile == NULL) return 0;
    rpt->RptFile = freopen(NULL, "w", rpt->RptFile);
    if (rpt->RptFile == NULL) return 303;
    writelogo(pr);
    return 0;
}
```
I just need to test it.

**Comment by eladsal** [comment]
@LRossman sure, I can write in the coming days. I remember that there is a `MAXTITLE` constant which is now set to 3. Should be consider the option that this value might change in the future? If so, we might have  a function that uses the title index and a string to set\get. Not sure I like it...

**Comment by eladsal** [comment]
I now see that 3 is hard coded in several places.

**Comment by LRossman** [comment]
I found some additional functions that are needed to make the API complete:

- `EN_setpatternid `- changes the name of an existing time pattern
- `EN_deletepattern `- deletes an existing time pattern
- `EN_setcurveid `- changes the name of an existing data curve
- `EN_deletecurve `- deletes an existing data curve

These will support the pattern and curve editing features that are already present in the existing EPANET 2.0.12 GUI.

**Comment by LRossman** [comment]
I think we should keep this issue open until the 4 new functions mentioned above are added to the API. I am in the process of doing so now.

**Comment by michaeltryby** [comment]
Oops sorry! Just trying to tidy the issues list up.

**Comment by LRossman** [comment]
The new functions suggested here have been incorporated into the code.
