### ISSUE TITLE
Issues using API with a user interface

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#393]
I've discovered two issues when trying to use the v.2.2 API to manage network data directly within a user interface (UI) app (as opposed to having the UI keep a separate copy of the data).

First the following sequence of function calls, which simulates a _File | Open_ command followed by a _File | New_ command,  will crash the program:
```
EN_open(...);
EN_close();
EN_init(...);
```
Initializing the various element counts (`Nnodes, Ntanks, Nlinks`, etc.) to 0 in` initpointers()` of `project.c` seems to fix the problem.

Second, there appears to be no way for the UI to access the Report file after an analysis has been made (to display a Status Report) without first using` EN_close` to release the file handle and thereby cause all network data to be lost. One possible solution is to add a `EN_copyreport` function that copies the current contents of the Report file to another file, keeping the original Report file opened afterwards. Other ideas are welcome.

**Comment by michaeltryby** [comment]
@LRossman so the issue is that the UI code needs to open the report file but can't because the engine still has it open? 

Runs can happen any number of times after the project is open. Each time the project is run the solver generates a report and binary file. So why not open/close the report/binary files independent from the rest of the project?

**Comment by LRossman** [comment]
Thanks @michaeltryby . If I understand correctly, you suggest keeping the report file closed until it needs to be re-opened for `EN_writeline`, `EN_report`, and the start of a hydraulic/quality analysis (to capture status messages). Then it gets closed again when the aforementioned actions are completed so that toolkit apps can gain access to it. This sounds better than  an `EN_copyreport` function. I will try to implement it.

**Comment by LRossman** [comment]
After looking over what is involved to keep opening and closing the report file before and after various toolkit operations, I've concluded that it's simpler (and safer) to go with a `EN_copyreport` function. It adds just a single self-contained function that doesn't change any existing code and keeps the ground rules simpler for API clients to understand. Namely, the contents of the report file can't be accessed by clients while a project is open. If access is required, they can use `EN_copyreport` to copy its current contents to another file and `EN_clearreport` to clear its contents.

**Comment by LRossman** [comment]
The issues identified have been resolved in the latest version of `dev`.
