### ISSUE TITLE
Improving unit test coverage for Toolkit API

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/EPANET#394]
Unit tests and regression tests currently cover 68% of the EPANET code base. I would like to get to 80% coverage for our upcoming release. Writing unit tests for untested API will help get us there. 

If you developed Toolkit API before unit testing came on line, please consider adding a unit test for it now.  

Untested API:
 - [x] get/set title
 - [x] saveH
 - [x] save/use Hydfile
 - [x] stepQ
 - [ ] writeline
 - [ ] clear/reset/set report
 - [x] get statistics
 - [x] get option
 - [ ] get/set flow units
 - [x] get time parameter
 - [ ] get qual info
 - [ ] get/set qual type
 - [ ] get coord
 - [ ] get/set demand model
 - [ ] get/set base demand
 - [ ] get pump type
 - [ ] get head curve index
 - [ ] get pattern length
 - [ ] get/set pattern value
 - [ ] get avg pattern value
 - [ ] get curve id/len/type/value
 - [ ] get/set curve
 - [ ] delete control
 - [ ] get control
 - [ ] delete rule
 - [ ] get rule id
 - [ ] get premise
 - [ ] set premise index/status/value
 - [ ] get/set then action
 - [ ] get/set else action
 - [ ] set rule priority

**Comment by michaeltryby** [comment]
I have been working diligently on testing for some time now and have barely made a dent in the tech debt incurred here. It turns out to be rather difficult to move the needle on coverage writing unit tests. 

As they say, "Many hands make light work!" It would be great if the authors of these functions stepped up and wrote tests for their work. Thanks in advance :smile:

**Comment by dickinsonre** [comment]
It has been a big hill of catchup you have been climbing, Michael  https://www.wikiwand.com/en/Technical_debt  Thanks for all of your efforts.
