### ISSUE TITLE
Windows 64-bit build is broken  

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/EPANET#397]
Appveyor logs indicate that the 64-bit build has been broken for some time.

**Comment by michaeltryby** [comment]
The problem started with the `epanet2.def` file was added to the library build.

**Comment by LRossman** [comment]
I'm confused. Isn't a 64-bit build part of the automated CI tests which all of the recent updates have passed? If not, then where can one find the script used for the cmake 64-bit build so that it can be debugged.

**Comment by michaeltryby** [comment]
@LRossman the 64 bit build is set to “experimental”. The badge is green cause it’s tied to the 32-bit build. If you build EPANET 64-bit locally you should be able to reproduce the problem.

**Comment by michaeltryby** [comment]
When you generate the build system just add Win64 and it will compile 64-bit.

**Comment by LRossman** [comment]
The problem may be the size difference of longs that appear in some of the function signatures in the `def` file. E.g., for 32-bit `ENrunH(long *currentTime)` the entry in the `def` file is
`ENrunH = _ENrunH@4`
but maybe it should be 
`ENrunH = _ENrunH@8`
which means we may need 2 `def` files, one for 32 bit and another for 64 bit. I will check it out.

**Comment by michaeltryby** [comment]
@LRossman Thanks!

**Comment by LRossman** [comment]
Since at this stage of the game we are only using a `def `file to allow the legacy API to be used in 32-bit apps, the immediate fix is to have cmake exclude the `def `file for an x64 build. To do this I modified the `ELSE (BUILD_PY_LIB)` section of the CMakeLists file as follows:
```
  # the shared library
  if(NOT WIN32)
    add_library(epanet2 SHARED ${EPANET_LIB_ALL})
  else(NOT WIN32)
    # 32-bit build uses a def file
    if(CMAKE_SIZEOF_VOID_P EQUAL 4)
      add_library(epanet2 SHARED ${EPANET_LIB_ALL} ${PROJECT_SOURCE_DIR}/include/epanet2.def)
      set_source_files_properties(${PROJECT_SOURCE_DIR}/include/epanet2.def PROPERTIES_HEADER_FILE_ONLY TRUE)
    else(CMAKE_SIZEOF_VOID_P EQUAL 4)
      add_library(epanet2 SHARED ${EPANET_LIB_ALL})
    endif(CMAKE_SIZEOF_VOID_P EQUAL 4)
  endif(NOT WIN32)
```
I tested the new script within the Visual Studio Cmake environment by successfully building both a 32-bit and 64-bit target. The resulting `runepanet.exe` executables ran `net1.inp` OK and the 32-bit DLL worked with the existing v2.0.12 Delphi GUI.

**Comment by michaeltryby** [comment]
I did it this way. 
'''
  # the shared library
  IF("${CMAKE_GENERATOR}" MATCHES "(Win64|IA64)" OR NOT MSVC)
    add_library(epanet2 SHARED ${EPANET_LIB_ALL})
  ELSE(TRUE)
    add_library(epanet2 SHARED ${EPANET_LIB_ALL} ${PROJECT_SOURCE_DIR}/include/epanet2.def)
    set_source_files_properties(${PROJECT_SOURCE_DIR}/include/epanet2.def PROPERTIES_HEADER_FILE_ONLY TRUE)
  ENDIF("${CMAKE_GENERATOR}" MATCHES "(Win64|IA64)" OR NOT MSVC)
'''
