### ISSUE TITLE
Use of single precision floats in ENgetcoord and ENsetcoord 

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#398]
The legacy-type API functions `ENgetcoord` and `ENsetcoord` introduced in v.2.1 use single precision floats for a node's coordinates by default. This provides an insufficient level of precision for geo-referenced coordinates, such as latitude and longitude. This can cause problems for client apps that try to display these nodes on a map. One solution is to re-declare the coordinate arguments in both functions as `double`, instead of the `EN_API_FLOAT_TYPE` which defaults to `single` (unless the API is re-compiled). This will break compatibility with any v.2.1 apps that currently make use of these functions. However, if this change is considered a "bug fix" then going ahead with it can be justified. Is this departure from maintaining backward compatibility with v.2.1 warranted?

**Comment by eladsal** [comment]
@LRossman I think I added these functions and what you described it definitely a bug which should be fixed. Thanks.

**Comment by LRossman** [comment]
This issue has been resolved in PR #406.
