### ISSUE TITLE
Support for model element string names

### ISSUE THREAD

**Issue by jamesuber** [OpenWaterAnalytics/EPANET#41]
We should have them. need space in the input file somewhere, plus API to get/set them.

**Comment by samhatchett** [comment]
seems a good place for this in the `inp` file is as a "comment" on the same line as the element definition, preceded by a semicolon `;`

**Comment by eladsal** [comment]
What do you mean by name? Another string apart from the ID?

**Comment by samhatchett** [comment]
i think that's right. usually we are dealing with epanet `inp` files that have been exported from some master workflow and the "ID" field is actually some obfuscated GIS identifier. We also need a human-readable version.

**Comment by jamesuber** [comment]
@eladsal Yes. @samhatchett Ideally it should be more formal, though I recognize this could get into territory of non-backward-compatibility. The reason is that the comment field ends up being a place to store all your junk. Need a place that is dedicated, I think.

**Comment by jamesuber** [comment]
I'm going to put this up on the forum, both because it has a strong 'user orientation' and also to add to the linkages between issues/forum posts.

**Comment by eladsal** [comment]
The proper way is to add it as a property of the elements but then we have the backward-compatibility issue which we should discuss soon. There are ways to partially overcome this.

There are two "non-formal" ways to do this. One would be, as @samhatchett suggested, to put it after the semicolon. This string is read by the EPANET GUI and placed in the `Description` field. The second way is to put it in the `Tags` section of the INP file which is shown in the GUI too. Both strings are not currently read by the Toolkit since they are not used by the solver (but should be read when asked like the coordinates).

**Comment by samhatchett** [comment]
wow, i did not remember the `[Tags]` section! that seems like the better choice, since it's a separate section that is already recognized by the old GUI

**Comment by eladsal** [comment]
Just remember that no spaces are allowed in the `Tag` field.

**Comment by samhatchett** [comment]
url encoding is an option...

**Comment by eladsal** [comment]
yes

**Comment by jamesuber** [comment]
There is also [LABELS]. The format of that section could probably be adapted for backward compatibility so long as we only need node element labels. This section is:
X  Y  "string label" <node id>
Where the quotes are part of the format and node id is optional. So if there's only two fields it could be assumed to be the label and the node id.

**Comment by jamesuber** [comment]
That was supposed to be 

X  Y  "label" <node id>

**Comment by jamesuber** [comment]
Crap! I guess when you use angle brackets that's interpreted as a type of markdown.

**Comment by eladsal** [comment]
Some housekeeping...

@jamesuber would you like to close this issue and maybe open a new one for new APIs for the `[TAGS]` section? Or something else?

**Comment by jamesuber** [comment]
@eladsal I think I'd prefer to leave this as an open issue with the more generic understanding that model elements often have to use a GIS ID, but there are applications that want to refer to model elements by a meaningful name. Supporting this somehow within the next generation code base would then support those applications. But especially given the discussion I'm less inclined to specifically request that it be the [TAGS] section, or the comment string... but if the devcom wants to close this then that's Ok also. But then it could get lost.

**Comment by samhatchett** [comment]
how about we split into three issues:

- short term: parse the comments on the same lines as the element definition, save as "description" field in network data
- mid term: parse the [tags] section, store that data somewhere  (parity with the GUI)
- longer term: general key-value capability for element relational data

**Comment by jamesuber** [comment]
Sure. I like that.

**Comment by samhatchett** [comment]
split to #47 #48 #49
