### ISSUE TITLE
Tank volume returned by EN_getnodevalue is invalid at time zero

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/EPANET#418]
Before start of the simulation the tank volume is computed incorrectly.

**Comment by LRossman** [comment]
`EN_TANKVOLUME `is a computed variable, like `EN_HEAD `or `EN_FLOW`, which are not initialized prior to the start of a new simulation. Therefore any value returned by an `EN_get `function before an analysis has begun will be meaningless (for the first simulation it will be 0 and for subsequent ones it will be whatever the value was at the last time period for the prior run). The parameter `EN_INITVOLUME `can be used to obtain the initial volume in a tank (based on the user-supplied initial depth) prior to the start of a new simulation. So bottom line, if we classify this as a bug for `EN_TANKVOLUME `then bugs exist for all of the other computed variables as well. The only fix I can think of (assuming one is required) is to return an error code if one uses an `EN_get `function for a computed variable before a simulation has begun.

**Comment by michaeltryby** [comment]
@LRossman Yeah makes sense. Perhaps, it would be helpful to make it more clear what properties are computed and which aren't.
