### ISSUE TITLE
Bug in EN_getcurve

### ISSUE THREAD

**Issue by Mariosmsk** [OpenWaterAnalytics/EPANET#438]
When `nPoints>3` then crash
example test inp: `BWSN_Network_1.inp`
`EN_getcurve`

**Comment by LRossman** [comment]
Nice catch! The declaration of `EN_get curve` should use `( ... double *xValues, double *yValues)` and not `(... double **xValues, double **yValues)`. I will fix it (requires updating a number of header files as well) and add a unit test for it.

**Comment by Mariosmsk** [comment]
#442
