### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by mauriziocingi** [OpenWaterAnalytics/EPANET#44]
at lines 3114-3117 of epanet.c function allocdata() allocates memory for node coordinates
```
      if (Coordflag == TRUE)
      {
        Coord   = (Scoord *) calloc(MaxNodes+1,  sizeof(Scoord));
      }
```

while freedata() does not deallocate.

We need to add something like:
```
      if (Coordflag == TRUE)  free(Coord   );
```

**Comment by eladsal** [comment]
Good catch, my bad. Your fix should go after line [3264](https://github.com/OpenWaterAnalytics/EPANET/blob/dev-2.1/src/epanet.c#L3265)

Would you like to push a patch or you want me to commit the fix?

**Comment by mauriziocingi** [comment]
I can do it.
