### ISSUE TITLE
Incorrect results obtained for some  types of tank mixing models

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#448]
The 2-compartment and Last In - First Out tank mixing models give incorrect water quality results when compared to those obtained using v.2.0.012 on the example1.inp file. This issue is no doubt related to the re-write that the water quality engine underwent to eliminate mass balance errors.

**Comment by michaeltryby** [comment]
@LRossman Would creating some reg test cases for mixing models be helpful?

**Comment by LRossman** [comment]
Since versions of example1.inp with a 2COMP and LIFO mixing model were used to identify the bug it makes sense to add these to the reg test suite.

**Comment by michaeltryby** [comment]
Attach them here and I can add them if you would like.

**Comment by LRossman** [comment]
The files are attached, but don't add them to the suite until this issue has been resolved (or we'll never get another PR to pass - LOL).
[TankMixingTests.zip](https://github.com/OpenWaterAnalytics/EPANET/files/3044108/TankMixingTests.zip)
