### ISSUE TITLE
make list management easier with a generic reusable list

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/EPANET#452]
Working on the memory leaks in the `netbuilder API` it occurred to me that many are occurring in lists. The lists in EPANET are raw data structures linked together. This makes working with them problematic. 

One solution would be a generic reusable linked list with an API that makes managing lists easier. I found one [here](https://pseudomuto.com/2013/05/implementing-a-generic-linked-list-in-c/) that I think will do nicely.

**Comment by michaeltryby** [comment]
https://github.com/michaeltryby/EPANET/blob/dev/src/util/list.c

https://github.com/michaeltryby/EPANET/blob/dev/tests/util/test_list.cpp

**Comment by michaeltryby** [comment]
Any thoughts or opinions on this before I proceed?

**Comment by LRossman** [comment]
@michaeltryby I vote no on this. After the latest merge there are only two data structures that use lists - the demands at each node and the quality segments in each pipe and tank . The latter uses custom memory allocation/reuse (from a memory pool) that is not compatible with the linked list code you provided. I don't think that using generic linked list code just for the demand lists is worth the effort and the additional layer of abstraction it adds to the code.

P.S. I don't recall seeing any memory leaks with the remaining two types of lists.

**Comment by michaeltryby** [comment]
@LRossman By my count there are 5 lists this can apply to `Sdemand`, `Sadjlist`, `Spermise`, `Saction`, and `S_actionList`. 

This list implementation provides a clean API for creating and deleting lists and for adding nodes to a list. This is a lot easier than futzing around with raw structs the way we have been and is no different than your use `hash` and `mempool`.  

There are still lots of memory leaks.

**Comment by LRossman** [comment]
Ok, I forgot about the rule lists and the node adjacency lists. I suppose it would be ok to sandbox the generic linked list routine so we can see how it affects the code's readability and performance. Then we can vote again.

BTW, to eliminate the memory leaks from `EN_addnode() `do the following:

- After line 1796 add the line:  `node->D = NULL;`
- After line 1822 add the line ` p->parser.MaxNodes = net->Nnodes;`

**Comment by michaeltryby** [comment]
@LRossman Do you have any network models in your collection that cover controls and rules? If you do could you share them? I would like to improve reg test coverage on these features prior to refactoring the lists. Make sense?
