### ISSUE TITLE
Toolkit API open / close function pair for model element creation

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/EPANET#456]
The Toolkit is organized around an `open / close` concept. Where pairs of function calls are used to designate different modes of operation. For example we have `EN_open()` and `EN_close()`, `EN_openH` and `EN_closeH`, and `EN_openQ` and `EN_closeQ`.  It would be useful if we had an `open / close` pair of functions for building a network. We have `EN_init()` but we don't have any function to signal that the data model is "closed" to model element creation. I think we should have such a function because it would make the new functionality more intuitive and consistent with existing Toolkit functions. 

It would also allow us to streamline some of the memory allocation going on. For example, each time a node is added using `EN_addnode()` the arrays `NodeDemand`, `NodeHead`, and `NodeQual` all get reallocated when it would make more sense to defer that allocation until the network size was set. A function for closure of the Toolkit to model element creation could be used to establish the size of network and to perform memory allocations that make more sense to defer until such time. 

Thoughts?

**Comment by LRossman** [comment]
@michaeltryby if you are only worried about the overhead in reallocating those additional node result arrays you could always include their variables (demand, head, and quality) in the `Snode` struct which has to be re-allocated with each node addition. The same can be done for the link result arrays `LinkFlow` and `LinkSetting` with regard to `Slink`.

I can't tell whether you are proposing this as something to add into v.2.2 or as a future enhancement. I think we need to get v.2.2 out ASAP, so I hope you meant it as a future enhancement. If so then I go back to my oft-stated opinion that future enhancements should be viewed from the perspective of re-architecting the entire code base, not just glomming onto the existing 2.x code.

**Comment by LRossman** [comment]
To elaborate further on how re-architecting can result in much simpler code, consider how adding a node element to the network might look using an object-oriented C++ approach:
```
int NetBuilder::addElement(ElementType element, int subType, string name, Network* nw)
{
    if ( nw->indexOf(element, name) >= 0 ) return NetBuilderError::DUPLICATE_ID;
    if ( nw->addElement(element, subType, name) ) return 0;
    return NetBuilderError::CANNOT_CREATE_OBJECT;
}

bool Network::addElement(ElementType element, int subType, string name)
{
    if ( element == NODE )
    {
        Node* node = Node::factory(subType, name, memPool);
        node->index = nodes.size();
        nodeTable[node->name] = node;    // add node ID to hash table
        nodes.push_back(node);           // add node to Node collection
    }
    else if ( element == LINK )  ...
}

Node* Node::factory(int nodeType, string name_, MemPool& memPool)
{
    switch (nodeType)
    {
    case JUNCTION:
        return new(memPool.alloc(sizeof(Junction))) Junction(name_);
        break;
    case RESERVOIR:
        return new(memPool.alloc(sizeof(Reservoir))) Reservoir(name_);
        break;
    case TANK:
        return new(memPool.alloc(sizeof(Tank))) Tank(name_);
        break;
    default:
        return nullptr;
    }
}
```

**Comment by michaeltryby** [comment]
@LRossman Great! Check in your work.

**Comment by michaeltryby** [comment]
@LRossman What are you waiting for? It's been finished for over a year now.

**Comment by michaeltryby** [comment]
@LRossman Well?

**Comment by michaeltryby** [comment]
@LRossman Refactoring EPANET 2 is on the table until you decide to share your work.

**Comment by michaeltryby** [comment]
@LRossman Guess I will continue refactoring ...

**Comment by LRossman** [comment]
@michaeltryby my C++ work has been shared in [epanet-dev](https://github.com/OpenWaterAnalytics/epanet-dev). I welcome you to become a contributor.

I personally have no interest in further development of the 2.x code base beyond v.2.2. If you want to keep working on it that's fine -- but please agree to release v.2.2 in the immediate future so we can share its significant computational and API features with the entire EPANET user community without further delay (it's been in development for more than a year now).

**Comment by michaeltryby** [comment]
@LRossman The work on epanet-dev was never completed. The code there is 3 years old except for some more recent bug fixes.

**Comment by LRossman** [comment]
@michaeltryby and it looks like you will never allow v.2.2 to be completed either.

**Comment by michaeltryby** [comment]
@LRossman The last time we discussed EPANET 3 face to face was June 2016. Yesterday, I was under the mistaken impression that you had stopped sharing your work on it prior to its completion and was unnecessarily rude about it. Please accept my apology.

**Comment by eladsal** [comment]
@michaeltryby  thank you.

Would this be a good time to ask what is still keeping 2.2 from being released?

**Comment by LRossman** [comment]
@eladsal yes this is a good time to do so. But I suggest raising the question in either a new issue or add it to issue #245 so it becomes more visible (since this one is closed and kind of off-topic).
