### ISSUE TITLE
Coordflag 

### ISSUE THREAD

**Issue by mauriziocingi** [OpenWaterAnalytics/EPANET#46]
In epanet.c line 213 Coordflag is set TRUE, and nodal coordinates structure is always allocated and section [COOR loaded even if ENepanet() is called,
If there's no need to load coordinates we have to
- change  line 213 to `Coordflag = FALSE;` 
- rebuild library

Maybe It would be better if
- remove epanet.c line 213
- add a function that can switch  Coordflag 

```
int DLLEXPORT ENsetcoordflag(char flag)
/*------------------------------------------------------------------------
**    Input: flag
**   Output: none
**  Returns: error code (always 0)
**  Purpose: set Coordflag to FALSE = do not read [COORDINATE] section
**                         or TRUE  = do read [COORDINATE] section
**           default status is FALSE, has effect if called before ENopen()
**-------------------------------------------------------------------------
*/
{
  if (flag) Coordflag=TRUE;
  else Coordflag=FALSE;
  return (0);
}

```

Test if coordinates are loaded becomes  `if (Coord!=NULL)` instead of `if (Coordflag)`

In this way code behaves as usual (no coord loading) as default and calling `ENsetcoordflag(1)` before ENopen coord get loaded.

Another improvement could be change `ENsetcoord` and  `ENgetcoord` to `ENsetnodecoord` and  `ENgetnodecoord`

**Comment by samhatchett** [comment]
The decision to allow the user to tell epanet whether to load coordinates is perhaps debatable. However, the toolkit currently does mass allocation within `ENopen` so it's a bit hard to justify creating a different usage model by calling a function prior to this.

Other ideas:

- second parallel version of `ENopen` like `ENopenWithCoords`
- standalone API function for parsing coordinate data after `ENopen` returns

i'm promoting this to 2.1 milestone since it's closely related to those items.

**Comment by eladsal** [comment]
@mauriziocingi this was done [knowingly](https://github.com/OpenWaterAnalytics/EPANET/issues/10). However you are right, there should be a way to load coordinates only when needed. This goes for all the sections which are not needed by the engine (Tags, Vertices, Labels, Backdrop, Title...). As @samhatchett suggested there a few ways to go. In my opinion we can support the old `ENopen` function with just the engine data and something like `ENopenAll` which would load all data.

**Comment by samhatchett** [comment]
building on that: we could leave `ENopen` alone, and provide another ... `ENparseData` that takes an enumerated type argument specifying which part of the .inp file to parse. Alternatively could use a 32-bit mask to read multiple sections in a single call.

**Comment by michaeltryby** [comment]
Simple is better. Just read in the coords data. We aren't taking about a lot of runtime overhead or memory usage and it allows the toolkit API to remain simple.

**Comment by samhatchett** [comment]
Hi @michaeltryby ! This is a valid approach, but well, it does take substantially longer with large systems - I have tested some code with Cincinnati's model and it gets frustrating waiting for the thing to load over and over again as I try to find bugs... I could go either way. I love simplicity ;)

**Comment by eladsal** [comment]
@michaeltryby that is why we left the flag set to TRUE but I tend to agree with @samhatchett. Once we also read the `[VERTICES]` section it will take a more time. Large network usually have many vertices.

**Comment by mauriziocingi** [comment]
I completely agree with  @samhatchett moreover I would like go little further.
Main question is: why to load nodal coordinates (but also vertices, labels, backdrop and tags)?
They are unusued by epanet toolkit, their sole use is rendering, editing and imitate (*absit iniura verbis*) GIS functions.

Epanet data structure is tailored to needs of hydraulic equations and it is too rigid for editing networks.
You know how hard is to add function for insert a new node or link, delete ecc.
For these reasons there are two distinct programs: epanet2w and epanet2d&toolkit.
Toolkit tolerates presence of these sections but even saveinpfile() is quite rude with them.

We can also think there are two distinct INP formats
* barebone INP (without  coordinates, vertices, labels, backdrop and tags)
* enhanced INP (with all sections)
(maybe even a third that is .NET binary file used by epanet2w)

A nice solution could be have two libraries:
- epanet toolkit as we know it  (simple and no-frills)
- epanet_editor: a specialized library with his own data structures (maybe object oriented?) capable of reading and writing "enhanced INP" (but also import/export to GIS), write "barebone INP", run epanet, read epanet binary output files

**Comment by eladsal** [comment]
I suggest we keep this issue open but remove it from 2.1.

**Comment by samhatchett** [comment]
agreed - so v2.1 will load coordinates no matter what, correct? we can revisit this a little further down the road.

**Comment by Alexandroz** [comment]
Hi 
I am trying to load Coordinates in epanet/matlab but i get this error:

Error using fopen
File identifier must be an integer-valued scalar of type
double.

Error in epanet>readAllFile (line 8194)
    fid = fopen(inpname, 'rt');%or msxname

Error in epanet/readInpFile (line 5683)
                [info,tline,allines] =
                readAllFile(obj.Bintempfile);

Error in epanet/getNodeCoordinates (line 6041)
            [~,info] = obj.readInpFile;
Thank you

**Comment by samhatchett** [comment]
@Alexandroz - this looks like it's not an epanet issue, but rather a matlab or library issue. your error is being generated from this line: https://github.com/KIOS-Research/EPANET-Matlab-Class/blob/master/epanet.m#L8194 so I would suggest you ask someone on that repository about this error.

**Comment by eldemet** [comment]
@Alexandroz Hi, as @samhatchett pointed out, this is not an EPANET issue, and  we can look into it in the EPANET-Matlab-Class repository, so please, create an issue and we will look further into it.

**Comment by eladsal** [comment]
Do we want to deal with this issue in 2.2 or roll it further down the road? I can wait with it.
