### ISSUE TITLE
API needs EN_adddemand and EN_deletedemand functions

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#460]
To allow the API to completely build a full EPANET model just using function calls requires that two new functions be added that will create and delete demand categories at junction nodes. Without these networks built with the API will be limited to using just a single demand catgeory at each junction.

**Comment by michaeltryby** [comment]
Since I am refactoring demand lists at the moment I can take this one.

**Comment by michaeltryby** [comment]
Or not.

**Comment by michaeltryby** [comment]
Be advised when I merge my demand list work, it's likely to conflict with the work you are performing here.

**Comment by eladsal** [comment]
Thank you @Mariosmsk for reminding us of #251

**Comment by LRossman** [comment]
@michaeltryby could you please look at lines 753 - 757 in _input3.c_. This is where new demand categories read from the `[DEMANDS]` input file section are added to a junction's demand list. It seems this code:
```
	else if (size_list(demand_list) == 1) {
		list_node_t *lnode = head_list(demand_list, true);
		delete_node(demand_list, lnode);
	}
```
is problematic since it would apply to both a demand added in the `[JUNCTIONS] `section as well as to each demand added from the `[DEMANDS] `section. The result being that only the last demand category for a node in the `[DEMANDS]` section will appear on the list. I can run a test file to check but I thought I would ask first in case I'm missing something obvious.

**Comment by michaeltryby** [comment]
@LRossman Yes I agree this is definitely a bug. We could use `NodeDemand[]` and `MISSING` markers like was being done previously to fix it.
