### ISSUE TITLE
Thoughts while refactoring demand data and demand list 

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/EPANET#462]
If patterns were referenced internally by name instead of by index, all the references to all pattern indexes wouldn't require adjustment when a pattern gets deleted.

**Comment by michaeltryby** [comment]
A demand index is required to get/set demand category properties, but there is no API to determine it. The client application must keep track of demand indexes on its own. This is a failure to contain the demand list abstraction.

**Comment by michaeltryby** [comment]
Using setters a demand category can be created and appended to the list of demands, but how should a demand category be created and deleted?  Clear need for #460. I think it would be more simple to have methods for creation and deletion of demand categories and to deprecate the get/set methods for individual demand properties. If we searched for demand category by name than we could hide demand index.

**Comment by LRossman** [comment]
There are backward compatibility issues with using category names to identify specific demand categories. The original EPANET data model did not include demand category ID names -- they were allowed as end-of-line comments in the input file mainly as an aid in building the file, but were optional and did not have to be unique (several categories could have no name or the same name). Version 2.2 now includes the category name read from the comment, but does not enforce any checks on its uniqueness. Thus the category name cannot be used as a reliable search key unless the underlying demand data model is changed which will break backward compatibility. So this concept is best left to be pursued as a future enhancement.

**Comment by michaeltryby** [comment]
You make a good point. But I think it’s reasonable to view the historical use case of parsing an EPANET 2.0 input file as separate from using the EPANET 2.2 Toolkit API functions. When viewed that way there is more flexibility to make the API more user friendly.
