### ISSUE TITLE
Problems with setting tank parameters using EN_setnodevalue and EN_settankdata 

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#464]
There are several problems when applying `EN_setnodevalue` to tank nodes:

- If `EN_TANKDIAM` is being set it means that the tank will stop using any assigned volume curve and switch to being a constant area tank. However new values for the tank's volume levels are computed before the switch is made thus invalidating their values.
- When setting `EN_MINLEVEL` or `EN_MAXLEVEL`, nothing happens if the tank uses a volume curve. 
- When setting `EN_MINVOLUME` the code ignores the fact that if the tank uses a volume curve its `Vmin` is derived from the `EN_MINLEVEL` parameter, not from `EN_MINVOLUME`.
- When setting `EN_VOLCURVE` a curve index of 0 is allowed while valid curve indexes start from 1. 

Also the newly added `EN_settankdata` function fails to assign a value to the tank's `Vmin` property when a volume curve is not supplied.

**Comment by Mariosmsk** [comment]
Why we need the function `ENsettankdata`. So, also we need `ENgettankdata`? `ENsetjuncdata`? `ENgetpipedata`? Will be removed `ENsetnodevalue`? Thanks

**Comment by Mariosmsk** [comment]
> When setting EN_VOLCURVE a curve index of 0 is allowed while valid curve indexes start from 1.

The curve index of 0 can be used to reset the curve of the tank back to the default. Unless there is another way to do this which I may be missing.

**Comment by LRossman** [comment]
@Mariosmsk the `ENsettankdata` and `ENsetpipedata` were added as convenience functions for building a network from just function calls. They save having to make as many as seven calls to `ENsetnodedata` and four calls to `ENsetlinkdata` for each new Tank or Pipe added to a network. Having companion functions that get current values of the same parameter groups wouldn't be as useful.

Regarding the curve index, if one sets it to 0 then the tank will revert to using its surface area as a linear volume v. depth curve. However, this area will be the "average" area of the curve that is being replaced (= (Max. Volume - Min. Volume) / (Max. Depth - Min. Depth)) which might be meaningless (and users will probably not be aware this is happening). The correct way to replace a tank's custom volume curve with a constant area (e.g., cylindrical shape) curve is to set `EN_TANKDIAM`.

**Comment by LRossman** [comment]
I just wanted to review the logic to be used when setting tank parameters with `EN_setnodevalue` as the current code needs fixing in this regard (checks for consistent water levels have been omitted for brevity):

**EN_TANKDIAM**
- Update the tank's area based on the supplied diameter.
- If the tank uses a volume curve, set the min. volume to 0 and the curve index to 0.
- Keep all water level limits the same.
- Update the initial, max., and mixing zone volumes.

**EN_MINVOLUME**
If the tank uses a volume curve:
- Set the min. volume to the designated value.
- Find a new min. water level at the new min. volume.

If the tank doesn't use a volume curve:
- Set the min. volume to the designated value.
- Keep all water level limits the same.
- Update the initial, max., and mixing zone volumes.

**EN_VOLCURVE**

- Keep all water level limits the same.
- Assign the designated volume curve to the tank.
- Update all tank volumes.

**EN_MINLEVEL**
If the tank uses a volume curve:

- Set the min. water level to the designated value.
- Update the corresponding min. volume value.

If the tank doesn't use a volume curve:

- Set the min. water level to the designated value.
- Do not update the min. volume.

**EN_MAXLEVEL**

- Set the max. water level to the designated value.
- Update the max. and mixing zone volumes.

Recall that for a tank without a volume curve, its min. volume is set by the user and is supposed to represent the "dead" storage when the water level is at it's allowed minimum. It's not possible to adhere to this definition by re-setting just `EN_MINVOLUME `or `EN_MINLEVEL `alone - they both must be adjusted together. For this reason, in the logic presented above no change in a non-volume curve tank's min. water level is made when its min. volume is set and likewise, no change is made in its min. volume when its min. level is set.
