### ISSUE TITLE
Use adddemand and remove demand for demand property edits

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/EPANET#467]
The Toolkit API "design" approach seems to be to expose getters and setters for each individual property. This is a logical approach. One drawback however, is that many individual API functions are required to provide access to the data. 

Now that #460 has been closed there is the question of what to do with `EN_getbasedemand()`, `EN_setbasedemand()`, `EN_getdemandname()`, `EN_setdemandname()`, `EN_getdemandpattern()`, and `EN_setdemandpattern()`.  

The API could be simplified, if `EN_adddemand()` and `EN_removedemand()` where used instead. For example, if a pattern index for a demand needed to be changed the entire demand category could be deleted and then recreated with all the same data and an updated pattern index. 

So we could accomplish the same tasks with 6 fewer API functions. Although it is not as convenient, the upside is the client application developer will have an easier time learning the API functions and we will not have to maintain and support them. 

In my estimation, this is an acceptable trade off.

**Comment by michaeltryby** [comment]
Thinking about this more, the addition of `EN_adddemand()` and `EN_removedemand()` allows us to deprecate the "setters" but we still would need a way to access the data. We could add `EN_getdemand(project, node_id, demand_key, property)`. 

So we need 3 functions to do everything we were previously able to do. But the property value is tricky, cause we have three different data types to handle here `double`, `int`, and `char *`. 

I'm sure there is a clever way to handle this that I'm not aware of.

**Comment by LRossman** [comment]
Question: what is the `demand_key`? I see it assigned a random number and saved with the generic list node data. Are API clients supposed to use it to identify one demand from another, especially after indexes get shuffled around after one or more deletions.  How would a client use such a number to tell different demand categories apart. 

A better system is to enforce unique category names for each demand within a node (where the names can be shared between nodes) in the next future version of the toolkit.

**Comment by michaeltryby** [comment]
Yes, a key is a unique identifier for providing random access to list nodes in an editable list. Please recall that the design goal here was to provide reusable list functionality. Not just demand lists.

You said unique demand category identifiers were problematic citing a concern for backward compatibility. Hence the key idea. 

No they don’t provide access to demand categories in different lists. How could they? Besides that wasn’t the use case as I understood it. 

You know what would be nice? If you could open an issue and describe the changes you want to make. That’s what I did and you can too. Thanks.
