### ISSUE TITLE
Bug - Only the last demand category for a node is being read from an input file

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#468]
The attached file is a modified version of example1.inp (aka net1.inp) that assigns three demand categories to Node 22. The results from running it show that only the last category is being applied.
[example1_mdc.zip](https://github.com/OpenWaterAnalytics/EPANET/files/3117501/example1_mdc.zip)

**Comment by michaeltryby** [comment]
@LRossman Yes I agree this is definitely a bug. We could use NodeDemand[] and MISSING markers like was being done previously to fix it.

**Comment by LRossman** [comment]
@michaeltryby I agree. I will fix it as part of my refactoring of `demand.c`.
