### ISSUE TITLE
Parse the comments after element definitions, save as "description" field in network data

### ISSUE THREAD

**Issue by samhatchett** [OpenWaterAnalytics/EPANET#47]
This will be a short-term extension of the `inp` parser to replicate what the GUI does.

**Comment by samhatchett** [comment]
implemented in f7d214576a9106f9d3732dcdf7821a7ede62457d

**Comment by eladsal** [comment]
Great, thanks.
Maybe we should close issues when they are merged into the `dev` branch. At the moment this fix is part of a much larger commit into `feature-wrapper`.

**Comment by eladsal** [comment]
@samhatchett this is already in `dev`, right? Can we close?
