### ISSUE TITLE
EN_removedemand is difficult (perhaps impossible?) to use

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#471]
`EN_removedemand() `uses a key value (a random integer generated when a demand category is appended to a demand list) in its argument list to identify which demand in a list of demands is to be removed. This key value is stored as a member of the `list_node_s` struct for a particular demand and is accessed by calling `get_key()` with a list node struct pointer as an argument. It is not apparent (to me anyway) how an API client would use these numbers to identify a demand they wish to remove as, unlike a demand category name, the key numbers by themselves have no meaning.

As an alternative I propose that two additional functions be added to _demand.c_. One would return the list node in the n-th position in the list and the other would return the node with a specific category name. Then the key value argument to `EN_removedemand() `would be replaced by an integer index and a character string. If the index is 0 the function removes the demand with the specified name. Otherwise it removes the demand with the specified index.

If there are other ideas on how to make a more usable version of `EN_removedemand()` please let us know.

**Comment by LRossman** [comment]
In case I wasn't clear about the problem of having to use a key to tell `EN_removedemand()` which demand to remove, let me give a use case about it. Say that an API client creates an EPANET model by reading an INP file. The demands in that file get placed into demand lists and get assigned keys, but the client app has no way of knowing what those keys are. Since there is no API function to retrieve a demand's key how could a key ever be supplied by the client to `EN_removedemand()`?

There is another even simpler solution to this dilemma. That is to not provide a "remove demand" function to the API. Instead a demand can in effect be removed by setting its base value to 0 using the existing `EN_setbasedemand()` function.

**Comment by michaeltryby** [comment]
Indexes have the same exact problem as I pointed out in #462. I suppose the user could open the input file, count the demands assigned to a junction and estimate the index that way. But I don't really consider that a valid alternative. Indexes have the additional problem of becoming invalid as demand categories are added and removed. Keys on the other hand remain valid after list editing operations.

**Comment by LRossman** [comment]
@michaeltryby it might help if you could you provide a specific example of how keys would be used by a client of the current API to manage the editing of nodal demand categories.

**Comment by michaeltryby** [comment]
No problem Lew. https://github.com/OpenWaterAnalytics/EPANET/blob/dev/tests/util/test_list.cpp The last test case uses keys to remove list nodes.

**Comment by LRossman** [comment]
Thanks, but that example doesn't use the toolkit API nor the list interface provided in _demand.c_.

**Comment by michaeltryby** [comment]
Well one could refactor add demand and remove demand to return a key and take a key respectively and use the functionality from the test to perform the desired operations. So conceptually it would be easy to implement.

**Comment by LRossman** [comment]
But what about demands read from an input file. The API has no functions to access their keys. Even if keys were available from all demands the client would have to store their values in some type of container along with the demands (or their surrogate names) which would have to be updated as demands are added and deleted. So much work for a feature (multiple demand categories) that is rarely used. It might be easier for clients to manage demands outside of the toolkit and inject them into the network as a simulation unfolds.

**Comment by michaeltryby** [comment]
Yes Lew I know.

**Comment by michaeltryby** [comment]
Last test case shows adddemand removedemand functionality using keys. https://github.com/michaeltryby/EPANET/blob/dev/tests/test_demand.cpp

**Comment by LRossman** [comment]
Except that when `EN_adddemand()` is applied to a junction with a NULL demand list, `create_demand_list()` is used to append the new demand to a newly created empty list and its key doesn't get returned as an argument in `EN_adddemand()`.

**Comment by michaeltryby** [comment]
Easily fixed.

**Comment by LRossman** [comment]
Yes as shown below :
```
    // Node has no demand list: create one and add this new demand to it
    demand /= p->Ucf[FLOW];
    demand_list = Node[node_index].D;
    if (!demand_list)
    {
        demand_list = create_demand_list(demand, pattern_index, category_name);
        if (!demand_list) return 101;
        Node[node_index].D = demand_list;
        *demand_key = get_key(head_list(demand_list, false));
    }
```
