### ISSUE TITLE
Python wrapper has become un-synchronized with the dev toolkit API

### ISSUE THREAD

**Issue by samhatchett** [OpenWaterAnalytics/EPANET#474]
As discussed here:
https://github.com/OpenWaterAnalytics/EPANET/issues/432#issuecomment-488428399

... some options spring to mind (not all mutually exclusive):

1. remove the index-returning features in `epanet_py.c`
2. add the index-returning feature in swig wrapper `toolkit.i`
3. add the `EPANET` repo as a submodule to `epanet-python` (thus library repo commit will be frozen for a particular wrapper build)
4. something else?

returning an index in python seems very un-pythonic, but I suppose that's pretty subjective. I could convince myself that either is better.

Any thoughts? Thanks!

**Comment by samhatchett** [comment]
Another option is to move toward a "monorepo" - apparently[ Google does this with great zeal.](https://cacm.acm.org/magazines/2016/7/204032-why-google-stores-billions-of-lines-of-code-in-a-single-repository/fulltext)

**Comment by michaeltryby** [comment]
1 :+1:

"monorepo" :-1000:

**Comment by michaeltryby** [comment]
On point 3, once the epanet library release is finalized we can point the `before-build.bat` in the `epanet-python` repo at a tag on the epanet master branch and that should do the trick.

**Comment by samhatchett** [comment]
I think this issue has been adequately addressed in PR #511 - we can close this in favor of more concrete discussion there.
