### ISSUE TITLE
Tie up loose ends regarding multiple demand categories

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#477]
Here are some loose ends that remain with how the toolkit handles mutiple demand categories:
- [x] The bug from issue #468 still remains.
- [x] Checks need to be added to the toolkit functions that access demands to insure that the demand of interest actually exists.
- [x] A decision needs to be made on what happens when `EN_setnodevalue()` is asked to set a base demand or demand pattern for a node with no or an empty demand list. I propose in this case that `EN_adddemand()` be called for the node to create a single demand category with the required base demand or pattern.
- [x] A similar question applies to the `EN_setjuncdata()` function. I propose that if the junction already has a first (primary) demand category then that is the demand that gets updated. Otherwise `EN_adddemand()` gets called to create a demand list whose single demand uses the parameters supplied to `EN_setjuncdata()`.
- [x] The `remove_node()` function in _list.c_ should return a `NULL `value if the key value passed into it is not contained in the list (otherwise an access violation or seg fault will probably occur). 
- [x] The `size_list()` function in _list.c_ should return 0 if the list passed into it is `NULL`.
- [ ] In _demand.c_ there is no longer a need for the `convert_units()` function. It is only called once, from _input1.c_, and can be replaced with local code that does the necessary conversion. 
- [ ] Also, it seems simpler and safer for `get_category_name()` to just return the pointer to the name rather than use `strdup()` to create a duplicate copy whose memory must be freed by the caller.

I am in the process of modifying the code to address these items.

**Comment by michaeltryby** [comment]
@LRossman  I have a PR open and I am working on this, so I kindly request that you allow me to proceed.
