### ISSUE TITLE
Keep or remove the #ifdef _DEBUG statements

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#482]
All of the source code files have
```
#ifdef _DEBUG 
  #define _CRTDBG_MAP_ALLOC
  #include <stdlib.h>
  #include <crtdbg.h>
```
statements at the top of the file that were used for locating memory leaks using Visual Studio's memory checker when compiling in debug mode. Now that the v2.2 code is (almost) ready for release should these statements be removed or not? If they are kept, then an additional guard
`#ifdef _MSC_VER` should probably be added to avoid any issues if users of another compiler have defined a `_DEBUG` directive.

**Comment by samhatchett** [comment]
I agree with removing these lines. Although I'm not that familiar with VS debugging - I would defer to the windows devs.

**Comment by eladsal** [comment]
I don't think these line are effecting the win builds.

**Comment by LRossman** [comment]
Thanks for the responses. For the win builds the lines would apply only if you build in debug mode. Even then they are useless unless you place a call to `_CrtDumpMemoryLeaks()` right before the main calling program exits so that a memory leak report is generated. I'm going to remove them -- it will give the code a more finalized look.
