### ISSUE TITLE
Keep only one copy of the epanet.def file

### ISSUE THREAD

**Issue by eladsal** [OpenWaterAnalytics/EPANET#483]
The same `DEF` file is located both in win build and the include folders. They are just the same. I suggest to keep only the one in the `include` folder and link to it from the old win build script.

Thoughts? @eldemet @Mariosmsk @LRossman

**Comment by eldemet** [comment]
Yes @eladsal  you are right, we don't need it in 2 locations!

d

**Comment by LRossman** [comment]
I agree.
