### ISSUE TITLE
Updating of reference report files used for CI testing

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#490]
I recently made a commit that modified the format of the status report file so that a blank line is added at the end of the list of any warning messages that get written between successive time periods of an EPS. It makes the report easier to read and is what version 2.0 does. The extra blank line makes it fail the Appveyor CI test for two of the 51 regression test files that list warnings in their report file (the comparison of the binary output files is not affected). I was able to make it pass by disabling the comparison of status reports in the Python testing code (see PR #489). Does anyone know how to update the reference report files that are used for regression testing or is everyone OK with my disabling of these tests (just for the report files, not the binary output files)?

**Comment by eladsal** [comment]
@LRossman I think we already found issues with the report files comparison so I hope we can avoid removing these tests. I have never updated the reference test files but I think I have some clues:
- the test networks are hosted in the `epanet-example-networks` repo, the `dev-rolling` [branch](https://github.com/OpenWaterAnalytics/epanet-example-networks/tree/dev-rolling). There are some pointers there.
- the report and out files should be generated locally (maybe there is a script for that in the repo) and the branch should be released with the files attached. see the [latest](https://github.com/OpenWaterAnalytics/epanet-example-networks/releases) release. There is also a `manifest.json` files in the release zips.
- now, tests are run by appveyor (travis should be similar).  in the `appveyor.yml` [file](https://github.com/OpenWaterAnalytics/EPANET/blob/dev/appveyor.yml) there is a reference to the release files (see `REF_BUILD_ID` in more than one place).
- appveyor calles `before-test.cmd` which pulls the tests file from the latest release of `epanet-example-networks`.

This is what I know, hope it helps...

**Comment by LRossman** [comment]
Thanks @eladsal. I think I now know how to replace the reference benchmark files. However I can't make any changes to the `epanet-example-networks` repo since I don't have access permission. @samhatchett can you grant me access?

**Comment by samhatchett** [comment]
done @LRossman - you should have write access now.

**Comment by LRossman** [comment]
@samhatchett thanks.

**Comment by LRossman** [comment]
The reference benchmark report files causing the problem have been replaced in `epanet-example-networks` and CI testing of report files will continue as before so this issue can now be closed.

**Comment by eladsal** [comment]
One point to remember when we release 2.2 the build badges should point to some fixed test benchmarks and not the latest release there which will change in time.
