### ISSUE TITLE
Need ENsetcontrolid, ENgetcontrolid ?

### ISSUE THREAD

**Issue by Mariosmsk** [OpenWaterAnalytics/EPANET#497]

**Comment by LRossman** [comment]
Controls don't have ID names associated with them.

**Comment by Mariosmsk** [comment]
Yes, I know. Maybe with `;commentID` if we need to delete specific control with `commentID`

**Comment by LRossman** [comment]
That's a possible solution, however I think it should wait for the next version so as not to delay release of 2.2.

**Comment by samhatchett** [comment]
closing as stale - new feature requests can be revised and folded into the next major release
