### ISSUE TITLE
Error 200 when open some epanet input files

### ISSUE THREAD

**Issue by Mariosmsk** [OpenWaterAnalytics/EPANET#498]
Before the commit edcd4b69c7d1f6f849a276292f0c0f246b1ee6bb its ok.

**Comment by samhatchett** [comment]
Can you supply an `inp` file that reproduces the issue you are seeing?

**Comment by Mariosmsk** [comment]
[example_test.zip](https://github.com/OpenWaterAnalytics/EPANET/files/3213718/example_test.zip)

**Comment by samhatchett** [comment]
the error is caused by line 68019 of the `inp` file, where the global energy pattern is set to an empty string. It is correct for this to be an error, I believe, since the toolkit won't be able to find a pattern named "".

The problem I see here is that the CLI doesn't point out where the error occurs. It could do a much better job of illuminating the cause of the error.

```
[ENERGY]
GLOBAL PRICE   0.0000
GLOBAL PATTERN ""
GLOBAL EFFIC   75.0000
DEMAND CHARGE  0.0000
```

**Comment by Mariosmsk** [comment]
This error did not exist before. But ok, that's not right. So if we have many INPs like that, (the user) must change all these files to be compatible with the new version.  Maybe ignore this line if exists, anw thanks.

**Comment by samhatchett** [comment]
Paging @LRossman - my read of the manual is that this is an invalid input line. Was the commit in question intended to affect the old behavior?

**Comment by LRossman** [comment]
The commit in question eliminated the use of temporary lists to store patterns and curves as they were parsed from the input file and instead just expanded the arrays used to permanently store these objects.

I believe that all previous releases (v2.0 and v2.1) of the toolkit treated a blank pattern name as an error. I will verify this, and if true, then there should not be a compatibility issue with older INP files.

**Comment by LRossman** [comment]
There's an error in the `findpattern()` function of _project.c_, which was added in the commit in question. When it searches through pattern names looking for the name entered in the input file it starts at index 1, forgetting that each project has a "dummy" pattern 0 created for it with just a single multiplier of 1.0 and a name of "". Thus "" is a valid pattern name indicating that the object/option in question has no pattern. The older builds that used temporary lists to store patterns as they were read from an input file didn't have this problem. I will fix the code ASAP. And thanks to @Mariosmsk for discovering this bug.
