### ISSUE TITLE
Use more realistic defaults for pipes added with EN_addlink

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#500]
The current default length and roughness for a new pipe created with `EN_addlink()` is 1000 ft and 100, respectively. The roughness value is for the Hazen-Williams head loss equation and makes no sense if the Darcy-Weisbach formula is used instead. I suggest making the default roughness depend on the head loss formula used, with a value typical of new ductile iron pipe as shown below:

- H-W formula: 130
- D-W formula: 0.5 millfeet (0.15 mm)
- C-M formula: 0.01

I also suggest making the default pipe length be 330 ft (100 m) which is the length of an average city block. Since `EN_addlink() `is new to v.2.2 there won't be any backwards compatibility issue with this change.

**Comment by eladsal** [comment]
I agree.

BTW, 330 ft are about 100 m
