### ISSUE TITLE
Updated project documentation

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#502]
The doxygen documentation, both in the toolkit's include files and the additional dox files in the doc folder, has been edited for improved consistency and style. In addition, a full description of the EPANET input file format has been added, thus making the HTML and Windows Help versions of the documentation fully self-contained and equivalent to the old v2.0 Help file. You can preview the updated documentation in the attached zip file.
[epanet2_2_doc.zip](https://github.com/OpenWaterAnalytics/EPANET/files/3233144/epanet2_2_doc.zip)

One issue encountered was the inability to generate a PDF file from the Latex output produced by Doxygen for the updated doc files. I think this may be due to how I used tables to get items aligned correctly on some of the doc pages. I spent a lot of time trying to resolve the problem (e.g., trying different versions of Doxygen and Latex distros) but was not successful. I believe the improved appearance provided by tables makes them worth keeping (and I'm not 100% sure they are entirely the source of the problem).  In any event, this issue can be re-visited at a later time if someone is so inclined to do so.

**Comment by samhatchett** [comment]
I'm finally having a look - this is wonderful @LRossman ! I really like the full-color images. Is the Doxy all up-to-date here? https://github.com/OpenWaterAnalytics/EPANET/tree/dev/doc

**Comment by LRossman** [comment]
Thanks @samhatchett . I think the branch you cited has up-to-date doc files, but if not I'll make sure that the commit I make to fix issue #528 does.

**Comment by samhatchett** [comment]
I suggest we focus on the online (html) documentation for the engine - we can figure out the PDF situation later. Thanks again for doing the hard work, @LRossman
