### ISSUE TITLE
How to acess the hydraulic results in the report?

### ISSUE THREAD

**Issue by TCCampos** [OpenWaterAnalytics/EPANET#504]
I'm running a hydraulic simulation with the toolkit, but i have some issues to get the results. Even with all the options "YES" or "FULL", the program only generates the "status report" present in the graphic interface. I'm trying to get the full report, as the file of the report>full section. Can I get it only with de .inp file or do I need to ask it in the main file?

The .inp file:
[TITLE]

[JUNCTIONS]
;ID              	Elev        	Demand      	Pattern         
 3               	98          	5.16       	                	;

[RESERVOIRS]
;ID              	Head        	Pattern         
 1               	103         	                	;

[TANKS]
;ID              	Elevation   	InitLevel   	MinLevel    	MaxLevel    	Diameter    	MinVol      	VolCurve
 Tanque          	99          	1           	0           	2           	1           	0           	                	;

[PIPES]
;ID              	Node1           	Node2           	Length      	Diameter    	Roughness   	MinorLoss   	Status
 1               	1               	Tanque          	1000        	100         	.01         	0           	Open  	;
 2               	Tanque          	3               	10          	100         	.01         	0           	Open  	;

[PUMPS]
;ID              	Node1           	Node2           	Parameters

[VALVES]
;ID              	Node1           	Node2           	Diameter    	Type	Setting     	MinorLoss   

[TAGS]

[DEMANDS]
;Junction        	Demand      	Pattern         	Category

[STATUS]
;ID              	Status/Setting

[PATTERNS]
;ID              	Multipliers

[CURVES]
;ID              	X-Value     	Y-Value

[CONTROLS]

[RULES]

[ENERGY]
 Global Efficiency  	75
 Global Price       	0
 Demand Charge      	0

[EMITTERS]
;Junction        	Coefficient

[QUALITY]
;Node            	InitQual

[SOURCES]
;Node            	Type        	Quality     	Pattern

[REACTIONS]
;Type     	Pipe/Tank       	Coefficient

[REACTIONS]
 Order Bulk            	1
 Order Tank            	1
 Order Wall            	1
 Global Bulk           	0
 Global Wall           	0
 Limiting Potential    	0
 Roughness Correlation 	0

[MIXING]
;Tank            	Model

[TIMES]
 Duration           	2 HOURS
 Hydraulic Timestep 	5 MIN
 Quality Timestep   	5 MIN
 Pattern Timestep   	5 MIN
 Pattern Start      	0:00
 Report Timestep    	5 MIN
 Report Start       	0:00
 Start ClockTime    	0:00
 Statistic          	None

[REPORT]
 Pagesize   		0
 Status             	FULL
 Summary            	YES
 Messages  		YES
 Page               	0
 Links            	ALL
 FLOW			YES
 HEADLOSS     		YES
 STATE   		YES
 Nodes             	ALL
 ELEVATION 		YES
 DEMAND			YES
 HEAD			YES
 PRESSURE  		YES

[OPTIONS]
 Units              	LPS
 Headloss           	D-W
 Specific Gravity   	1
 Viscosity          	1
 Trials             	40
 Accuracy           	0.001
 CHECKFREQ          	2
 MAXCHECK           	10
 DAMPLIMIT          	0
 Unbalanced         	Continue 10
 Pattern            	1
 Demand Multiplier  	1.0
 Emitter Exponent   	0.5
 Quality            	None mg/L
 Diffusivity        	1
 Tolerance          	0.01

[COORDINATES]
;Node            	X-Coord         	Y-Coord
 3               	5604.68         	7067.62         
 1               	1430.43         	7665.80         
 Tanque          	3537.06         	7366.71         

[VERTICES]
;Link            	X-Coord         	Y-Coord

[LABELS]
;X-Coord           Y-Coord          Label & Anchor Node

[BACKDROP]
 DIMENSIONS     	0.00            	0.00            	10000.00        	10000.00        
 UNITS          	None
 FILE           	
 OFFSET         	0.00            	0.00            

[END]

**Comment by samhatchett** [comment]
@TCCampos - without going into too much thought about the specific question, can you advise what version / build / commit you are working from? Is this something that once worked but no longer works correctly? 

Also, you mention both the `inp` file and the main file - what do you mean by "main file"? 

thanks!

**Comment by samhatchett** [comment]
closing as stale. please re-open if this continues to be an issue.

**Comment by allenmlowe** [comment]
I think what he was requesting was to get a result in the status report which can be done with this modification in Epanet.c. This will only function if Status Report in Options is set to Full

`int DLLEXPORT EN_close(EN_Project p)
/*----------------------------------------------------------------
 **  Input:   none
 **  Output:  none
 **  Returns: error code
 **  Purpose: frees all memory & files used by a project
 **----------------------------------------------------------------
 */
{
    EN_report(p); // This is the addition

   // Free all project data
    if (p->Openflag) writetime(p, FMT105);
    freedata(p);

`
The only problem is if the result is too long, it may take a lot of space in the status report
