### ISSUE TITLE
Temporary files are in the wrong location and clutter the filesystem on non-windows systems

### ISSUE THREAD

**Issue by AbelHeinsbroek** [OpenWaterAnalytics/EPANET#512]
Creating a new EPANET project results in three calls to the [getTmpName](https://github.com/OpenWaterAnalytics/EPANET/blob/dev/src/project.c#L1068) function. Which, on non-windows systems, uses [mkstemp](https://github.com/OpenWaterAnalytics/EPANET/blob/dev/src/project.c#L1095) to create a new temporary file and return the filename. This temporary file is created in the current working directory.

When running a large amount of different models simultaneously this results in a huge amount of 0b files cluttering the working directory. I work a lot with 'real-time' models that are continuously updated with live information and are thus kept running, resulting in 0b scratch files everywhere on my filesystem, messing up my backup systems.

One possible solution is to place the temporary files in a location where they belong, /var/tmp, /tmp or a user-defined folder. This should lead to an increase in performance as well, with /tmp often being a tmpfs mount.

Another point of discussion is to forego using temporary files altogether and keep everything in memory instead. I don't know how large they can become, but maybe they are a relic from times when memory was scarce?

**Comment by LRossman** [comment]
@AbelHeinsbroek  before considering changing the EPANET code the obvious question to ask is why are you not calling `ENclose()` to delete your models when they are no longer needed. This will remove the temporary files from your file system. With the new re-entrant version of EPANET you would call `EN_deleteproject()` to delete the files. With this version you can also call `EN_close()` to begin work on a new model without having to create another set of temporary files.

**Comment by samhatchett** [comment]
The funny thing is that, while `EN_close()` will remove the file, a file descriptor remains open. PR #529 fixes this behavior. I mention it here in case @AbelHeinsbroek may have encountered the open-file phenomenon.

**Comment by samhatchett** [comment]
closing as stale, and possibly "intended behavior" given the EN_close caveat. Feel free to suggest re-opening this issue if it is truly a roadblock
