### ISSUE TITLE
CMake build requires users have MS Visual C++ Redistributable installed

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#517]
The `CMake `build script produces a Windows version of the toolkit DLL that requires that users have a copy of the MS Visual C++ Redistributable library (I think it has to be the 2017 version but I'm not sure) installed on their machine. The `Makefile.bat` script in the project's `win_build` directory builds a DLL that has the necessary library functions linked into it. (Hence the `CMake`-produced DLL is only 198 KB in size while the `Makefile.bat` DLL is 334 KB). The `CMake `script can be modified to produce a DLL that doesn't rely on the C++ Redistributable library by adding a definition `"-MT"` to it. Do people think this is an issue that's worth addressing?

**Comment by eladsal** [comment]
Sure, I think we want a stand alone DLL.
