### ISSUE TITLE
Problem with Makefile.bat for Windows builds

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#521]
The `Makefile.bat` file contains commands for building both 32-bit and 64-bit binaries for Windows. The requirement that it be run in a Visual Studio command prompt window means that in reality it is only able to build for whatever target the window is set up for. E.g., a Developer or x86 Native Tools command prompt will only build 32-bit binaries while a x64 Native Tools command prompt will only build 64-bit binaries. Thus instead of getting builds for two targets we get a duplicate set of builds (either 32- or 64-bit depending on which VS command prompt window is used). I've confirmed this through testing.

I've created a new version of `Makefile.bat` that can be run from a regular command prompt window and will correctly generate both 32-bit and 64-bit binaries placed in separate folders. The only catch is that because Microsoft changed the locations of files used to set up the build environments for 32 v. 64 bit compilation with VS 2017, the batch file will only work for that version of VS (or higher). 

Another option is to create two versions of the batch file: `Makefile32.bat` would be used for a 32-bit build (and includes the `.def` file mapping) and `Makefile64.bat` used for a 64-bit build. Each file would have to be launched in the proper VS command prompt window but would be compatible with older versions of Visual C++.

Which of these options is preferrable?

**Comment by dickinsonre** [comment]
One version of the makefile.bat would be preferable to two versions just for the sake of simplicity.

**Comment by eladsal** [comment]
@LRossman for me the `Makefile.bat` script builds the 32 and 64 bits versions (32 dll is 277kb and the 64 is 340kb) both work in their environment. I think this also works for @eldemet and @Mariosmsk

**Comment by LRossman** [comment]
@eladsal I think we went through this already from the recent PR involving `Building.md` where I noted that on my machine `Makefile.bat` wouldn't run from a simple command prompt window but instead had to be run from a Visual Studio prompt. Even so the following commands on lines 24 and 37 are problematic because my installation of the Windows SDK doesn't come with `SetEnv.cmd`:
```
CALL "%SDK_PATH%bin\"SetEnv.cmd /x64 /release
CALL "%SDK_PATH%bin\"SetEnv.cmd /x86 /release
```
That's the reason I don't get builds for the two targets but you do. It seems that `Makefile.bat` requires that the full SDK be installed, and I don't think this happens when someone just installs the Visual Studio Community Edition package.

So as not to make a federal case over this let's revise the options as follows:

1. Keep `Makefile.bat` as is but revise `Building.md` to note that it requires a full install of the Windows SDK.
2. Switch it out for my modified version that doesn't depend on the SDK but will only work with Visual Studio 2017 and higher.

**Comment by eladsal** [comment]
Sorry @LRossman, I didn't understand it was the same issue. As I said a few times I'd rather keep the current script for v2.2. However, this does not imply that we can't have a different script (`Makefile2017.bat`) for people who want to install VS 2017+.

**Comment by LRossman** [comment]
I apologize for wasting time on this issue. The description of `Makefile.bat` in the original version of `Building.md` clearly states "**_This script requires the installation of Microsoft Windows SDK 7.1_**" which goes back to the days of Windows 7. So if you have a later version on your machine (like I do) you can't expect the script to work.

I will change the description in `Building.md` to read:
2. `Makefile.bat`: this is the legacy build script compatible with Visual Studio 2010 which conforms with the C89 Standard which was the standard EPANET supported from earlier versions. This script requires the installation of Microsoft Windows SDK 7.1 ([https://www.microsoft.com/en-us/download/details.aspx?id=8279](https://www.microsoft.com/en-us/download/details.aspx?id=8279)) and will not work properly with later versions of the SDK.

**Comment by eladsal** [comment]
Fine by me, thanks.

BTW, I never used the SDK 7 on Windows 7. Previously on Windows 8 and now on 10.
