### ISSUE TITLE
API suggestion: get array of node/link values

### ISSUE THREAD

**Issue by samhatchett** [OpenWaterAnalytics/EPANET#526]
This sort of API call could be useful for result-harvesting, for instance if one wanted to bypass the binary file and reduce API calls for common access patterns. The API function I have in mind would look like: 

```
double *flows = malloc( sizeof(double) * n_links);
EN_getlinkvalues(project, EN_FLOW, flows);
// do something useful with flows[]
```

... this pattern would tend to mirror what is in the outfile API (i.e., ability to wide-query an attribute for all elements for a single frame of the simulation). 

This would also ease development of (and interaction with) a results-writing API, a multi-species engine, and other client tools that simply need all the data at once rather than using a pick-and-choose convention.

Any other use cases out there?

**Comment by LRossman** [comment]
Wouldn't this do the same without the need for another API function:
```
    double *flows = (double *)calloc(n_links, sizeof(double);
    for (int i = 1; i <= n_links; i++) EN_getlinkvalue(ph, EN_FLOW, &flows[i]);
```
Maybe you're thinking of more complex queries, like returning flows in sorted order or executing an SQL-type request seeking a count or a subset of elements that meet a specific set of criteria. If so then I would suggest that a separate API, akin to the outfile one, be used for these types of convenience functions.

**Comment by samhatchett** [comment]
sure - it's equivalent, but the single-link fetch goes through some case evaluation and casting which is just extra overhead. I have not profiled, so this may be premature optimization!

**Comment by samhatchett** [comment]
ok - no other feedback means it's a cold issue. Closing in favor of keeping the API small-ish.
