### ISSUE TITLE
CI and build/test/dist tooling

### ISSUE THREAD

**Issue by samhatchett** [OpenWaterAnalytics/EPANET#531]
So it appears we've been added to The GitHub Actions Beta program. This has the potential to better serve multi-arch CI than current travis/appveyor integrations. Any thoughts? I've set up a demo action that simply runs cmake/make with defaults.

**Comment by LRossman** [comment]
Sounds promising. I'm in favor of anything that can make the CI process simpler and more transparent. Perhaps the next step is to extend the demo action to run one or more of the API tests in the `tests ` folder to see how the process works before moving on to running the regression tests which seem to have more moving parts to it.
