### ISSUE TITLE
UI support for the new features in version 2.2

### ISSUE THREAD

**Issue by shenh** [OpenWaterAnalytics/EPANET#545]
I see the development focus here is on the EPANET engine. Will the UI support for the new features 
 (e.g. pressure dependent demand options) be through the legacy EPANET GUI or the re-engineered python GUI (https://github.com/USEPA/SWMM-EPANET_User_Interface) or both?

Hailiang

**Comment by LRossman** [comment]
US EPA sent out a beta test version of the legacy UI with support added for the new v2.2 features to an invited group of reviewers about two months ago. I'm not sure when an official release will be made on EPA's EPANET web site but assume it will be shortly after this OWA project promotes the v2.2 engine code to the master branch of this repo. I don't know what their plans are for the new PyQt GUI.

**Comment by samhatchett** [comment]
I'm not sure anyone here can say definitively. Perhaps post the question to the forum at [community.wateranalytics.org](http://community.wateranalytics.org) 

I imagine EPA representatives would be happy to bring some clarity ;)
