### ISSUE TITLE
Allow toolkit to provide access to link vertices

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#548]
Issues #46 and #48 raised the question if the toolkit should read and store link vertices or not. As noted in issue #547, one use case where this capability is needed is when the toolkit serves as the underlying network database behind a GUI (like the legacy one) where interactive addition/deletion/editing of objects is occurring. Another would be to support models of incomplete mixing at 4-way junctions where one needs to know the orientation of the 4 links joined at the junction.

I have recently added this capability to my local copy of v2.2's `dev` branch in the form of three new API functions (that mirror those used for `Curves`):
`EN_getvertexcount` - retrieves the number of vertex points contained in a link
`EN_getvertex` - retrieves the X,Y coordinates of a particular vertex point for a link
`EN_setvertices` - replaces a link's set of vertex points with a new set
These have been tested with my toolkit-driven version of the GUI and appear to do the job nicely. 

My implementation only allocates memory for vertices if needed and reads them in by default with the `EN_open` function. As noted in issue #46, it may be more desireable to have `EN_open` not read network coordinate data if they are not needed and use a separate function (like `EN_openall` to read all data or `EN_openmap` to read just map-related data) for this purpose.

Do people agree that we should add this feature now to v2.2 and if so, should we use a separate function to read map-related data from an INP file or not?

**Comment by samhatchett** [comment]
Great - if you've got the code ready, I would vote to include the extra parsing. I just wonder if we can separate parsing the network file into two steps? For very large networks, reading coordinate data can take a noticeably longer time, might be nice to background it.

**Comment by LRossman** [comment]
FYI: I just compared times to load a file using the current version of `EN_open` (which skips over lines of vertex data) with my updated one (which parses the coordinates and saves them) for a network with 543,081 vertices using my "work-in-progress" toolkit-driven GUI. Using the highly accurate "Mississippi" method of timing 😉, skipping the vertices took 1 Mississippi while including them took 2.5 Mississippis, and that includes the time to draw a network map with 113,173 links and 100,294 nodes (AMD-A8 3.0 GHz processor). That breaks down to 3 millionths of  a Mississippi per vertex.
