### ISSUE TITLE
Setlinkstatus function defaults pump speed setting to 1 when set to open

### ISSUE THREAD

**Issue by allenmlowe** [OpenWaterAnalytics/EPANET#558]
When a pump has a speed setting other than 1.0, when a control rule set opens a pump, it does not use the speed specified but a speed of 1.0.

Proposed change to address this. A correction in hydraul.c
    // Status set to open
    if (value == 1)
    {
        // Adjust link setting for pumps & valves
        if (t == PUMP) *k = link->Kc;  // line 472 of hydraul.c 

  // instead of 
      if (t == PUMP) *k = 1.0; 
[curved_pump_rule-based_with_speed_setting.zip](https://github.com/OpenWaterAnalytics/EPANET/files/3828275/curved_pump_rule-based_with_speed_setting.zip)

**Comment by LRossman** [comment]
The behavior described above is not a bug but rather a convention that has been in effect for almost 30 years. As long as a modeler understands this when controlling a pump's Status as opposed to its speed Setting then there's nothing inherently wrong with the existing code. Unfortunately the Users Manual is pretty vague (or maybe silent) on explaining this. Making the proposed change would cause some existing network models to have significantly different results under v2.2 than were previously obtained. I thought one of the ground rules for making changes to a minor (e.g. 2.x) version of the code is that it not break existing models unless the change was a bug fix. Therefore I suggest that this re-definition of what it means to set a pump's Status to `OPEN `be postponed for future discussions about EPANET 3.0 (should they ever happen).

**Comment by dickinsonre** [comment]
Couldn't you have or EPANET have a new flag to allow the Speed Setting to exceed 1 but have the default being the Speed Setting behavior for the last 30 years?  That way you will not break existing models.

**Comment by LRossman** [comment]
A new flag/option isn't necessary. All one has to remember is the following convention:
If one uses `STATUS = OPEN` for a pump control then its speed setting becomes `1`.
If one uses `SETTING = N` for the control statement, where `N `is some number, then its speed setting becomes whetever value `N `has.

**Comment by allenmlowe** [comment]
Thank you for the explanation. That is an elegant solution to the problem. However, We are using a VFD and we don't know the time the pump will open since it depends on the tank height behavior. All we know is the speed pattern. When the pump opens we should then guess the speed setting.
