### ISSUE TITLE
Propose some changes to Status Report Flag

### ISSUE THREAD

**Issue by allenmlowe** [OpenWaterAnalytics/EPANET#563]
If status report flag is set to Full make it automatic to also set the following 

Summary  Yes
Energy      Yes
Nodes       All
Links         All

The GUI has no option to set these parameters so if the Status Report is set to Full you get these additional reports

**Comment by LRossman** [comment]
Please do not change the current meaning of the Status Report flag to include these other types of reports. If you want to have some simple way to include all available output information in the Report file then I suggest defining a new parameter, say `FULL_REPORT`, whose values can be `YES `or `NO `(the default).

If one recognizes that the current report format is simply one (fixed) way of presenting the contents of the program's binary output file in a readable fashion, then a more flexible option would be to allow its contents to be written to a file formatted to work with database software (SQLite seems to be a popular choice these days). That would give users many more options in how they could prepare "hard copy" reports.

**Comment by eladsal** [comment]
I think you can produce a full report in the GUI from the Report->Full... menu.

**Comment by allenmlowe** [comment]
Yes, the GUI can produce a full report from Report->Full.. menu but it can only produce a more detailed report but not the full available reports as shown in the attached file. The full report can only be accessed if you modify directly the inp files via text editor and add 

[REPORT]
 Status             	Full
 Summary            	Yes
 Page               	0
 Energy               Yes
 Nodes                All
 Links                All


[FullReport.zip](https://github.com/OpenWaterAnalytics/EPANET/files/3860800/FullReport.zip)

**Comment by allenmlowe** [comment]
To get the full status report epanet.c will need some modification

int DLLEXPORT EN_close(EN_Project p)
/*----------------------------------------------------------------
 **  Input:   none
 **  Output:  none
 **  Returns: error code
 **  Purpose: frees all memory & files used by a project
 **----------------------------------------------------------------
 */
{
	EN_report(p);

    // Free all project data
    if (p->Openflag) writetime(p, FMT105);
    freedata(p);
