### ISSUE TITLE
contributor code of conduct

### ISSUE THREAD

**Issue by samhatchett** [OpenWaterAnalytics/EPANET#57]
In an effort to establish a good and healthy environment for collaboration, I'd like to suggest that the project adopt the well-written Contributor code of conduct available at http://contributor-covenant.org and reproduced below. In the best of circumstances, we would just say that we agree with the message and we post the file into the root directory. In non-ideal circumstances, we have a document to point to which outlines a policy for handling unfortunate situations. 

Feedback on this issue is encouraged!

---
# Contributor Code of Conduct

As contributors and maintainers of this project, and in the interest of
fostering an open and welcoming community, we pledge to respect all people who
contribute through reporting issues, posting feature requests, updating
documentation, submitting pull requests or patches, and other activities.

We are committed to making participation in this project a harassment-free
experience for everyone, regardless of level of experience, gender, gender
identity and expression, sexual orientation, disability, personal appearance,
body size, race, ethnicity, age, religion, or nationality.

Examples of unacceptable behavior by participants include:
- The use of sexualized language or imagery
- Personal attacks
- Trolling or insulting/derogatory comments
- Public or private harassment
- Publishing other's private information, such as physical or electronic
  addresses, without explicit permission
- Other unethical or unprofessional conduct

Project maintainers have the right and responsibility to remove, edit, or
reject comments, commits, code, wiki edits, issues, and other contributions
that are not aligned to this Code of Conduct, or to ban temporarily or
permanently any contributor for other behaviors that they deem inappropriate,
threatening, offensive, or harmful.

By adopting this Code of Conduct, project maintainers commit themselves to
fairly and consistently applying these principles to every aspect of managing
this project. Project maintainers who do not follow or enforce the Code of
Conduct may be permanently removed from the project team.

This Code of Conduct applies both within project spaces and in public spaces
when an individual is representing the project or its community.

Instances of abusive, harassing, or otherwise unacceptable behavior may be
reported by contacting a project maintainer at [INSERT EMAIL ADDRESS]. All
complaints will be reviewed and investigated and will result in a response that
is deemed necessary and appropriate to the circumstances. Maintainers are
obligated to maintain confidentiality with regard to the reporter of an
incident.

This Code of Conduct is adapted from the [Contributor Covenant](http://contributor-covenant.org),
version 1.3.0, available at
[http://contributor-covenant.org/version/1/3/0/](http://contributor-covenant.org/version/1/3/0/)

**Comment by eladsal** [comment]
Thanks @samhatchett for putting this together.

I'm for this version but also like the [guidlines](http://community.wateranalytics.org/t/faq-guidelines/80) version we have on the forum. Maybe we should have a one version for both places?

**Comment by kobusvanzyl** [comment]
Looks good to me. Thanks Sam.

**Comment by eldemet** [comment]
It''s good, and I also agree with @eladsal to have the same one for the forum as well as for Github

**Comment by jart** [comment]
Code of conduct? Hahaha. I can't believe people take those things seriously. It's just childish rubbish promoted by people with a political agenda. Keep that nonsense out of engineering.

We don't need a code of conduct. FOSS is the first culture, in the history of mankind, that's truly international, post-monetary, and discrimination on the basis of race, sex, age, etc. is impossible. Welcome to the Internet. It unites the human race. And hackers invented it.

So we already know what we're doing. We did nothing wrong. So no one really takes the entryists who tell us otherwise seriously. I'm sure a small subset of engineers are dim enough to be fooled by the political agitators. But they shouldn't be the ones driving policy.

**Comment by samhatchett** [comment]
agitators? https://github.com/jart?tab=activity
