### ISSUE TITLE
Introduction of model reduction algorithm to EPANET

### ISSUE THREAD

**Issue by ooojoj** [OpenWaterAnalytics/EPANET#574]
This issue is a suggestion from the De Monfort University team led by Prof. Bogumil Ulanicki. Over the years we have developed many in-house algorithms associated with EPANET. One of them is a very useful tool able to simplify large water networks. The reduced model can be subsequently employed for example in optimisation studies. More details on the algorithm can be found in the following papers:

- Ulanicki, B., Zehnpfund, A., and Martinez, F. (1996). Simplification of water network models. In Muller, A., editor, Hydroinformatics 1996: Proceedings of the 2nd International Conference on Hydroinformatics, volume 2, pages 493-500, Zurich, Switzerland. ETH, International Association for Hydraulic Research.

- F. Alzamora, B. Ulanicki, E. Salomons, A fast and practical method for model reduction of large-scale water distribution networks, Journal of Water Resources Planning and Management, 140 (2014), pp. 444-456 https://doi.org/10.1061/(ASCE)WR.1943-5452.0000333

- D. Paluszczyszyn, P. Skworcow, B. Ulanicki Online simplification of water distribution network models for optimal scheduling Journal of Hydroinformatics, 15 (3) (2013), pp. 652-665, https://doi.org/10.2166/hydro.2013.029

- D. Paluszczyszyn, P. Skworcow, B. Ulanicki, A Tool for Practical Simplification of Water Networks Models, Procedia Engineering Vol. 119, 2015, Pages 486-495, https://doi.org/10.1016/j.proeng.2015.08.871

We believe that this algorithm would greatly benefit the water community and could be a valuable enhancement of the new EPANET engine.

**Comment by eladsal** [comment]
Thank you @ooojoj for the suggestion.

I have also been using these simplification algorithms (I'm the co-author of the second reference you gave) and agree that they should be made accessible. However, I don't think they should be included in the core code of the EPANET engine. Other tools, like a simplification program can use the engine from outside. One option is for these tools to be plugins to the EPANET GUI. Please have a look at a [presentation](https://www.slideshare.net/elad/open-source-epanet-project-epanet-plugins) I gave on the subject - around slide 71 there is a simplification example.

**Comment by shenh** [comment]
My two cents here - I agree the network simplification should not be part of the engine. Such simplification algorithms may be more helpful in SWMM modeling, which could run a few days or months.
I personally have not seen municipalities asking to simplify their water distribution models but just the opposite in order to provide detailed output (e.g. pressures at hydrants). With the advancement of computational resources, a water distribution system model run can normally be completed within a reasonable amount of time (a few minutes).
