### ISSUE TITLE
Cleaning up the Wiki

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#578]
I would like to clean up the project's Wiki by removing the 134 topics that duplicate the API function and input file descriptions that already appear (in a more readable and up-to-date format) in the [gh-pages](http://wateranalytics.org/EPANET/). But before embarking on such an extensive removal effort I want to check if everyone is OK with it.

**Comment by eladsal** [comment]
Yes, this is what we previously agreed on. I just hope that the wiki, like the rest of GH, saves the history of all files.

**Comment by LRossman** [comment]
The wiki has been cleaned.
