### ISSUE TITLE
Error Checking in EN_open is too strcit for network building by code

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#579]
Consider the use case where the toolkit functions are being used in some app to build a network directly by function calls. Suppose a user has created a partial network with lots of nodes of which only some have been connected by links and with no tanks/reservoirs. They then call `EN_saveinpfile` to save their work so they can complete their analysis at some later time. When they try to use `EN_open` to re-open their project again the function fails because it detects unlinked nodes and no tanks/reservoirs thus making all of their previous editing work lost to the app.

Checks on these conditions should have been made after a network is completely built and is ready to be analyzed. Other error conditions that `EN_open `checks for that should be postponed until a network is analyzed are invalid tank levels, invalid pump curve parameters, and an inability to open a Hydraulics file.

**Comment by eladsal** [comment]
@LRossman I think this was discussed somewhere before. Basically you need a `Load` function and then a `Check` function, right?

**Comment by LRossman** [comment]
@eladsal I think just a `Check `function is needed, to be called in `EN_openH` (or `EN_openQ` if no hydraulics are analyzed).` EN_open` can still serve as a `Load `function once its validity checks are removed.

**Comment by LRossman** [comment]
This issue has been successfully addressed in PR #580.
