### ISSUE TITLE
API access to incontrols()

### ISSUE THREAD

**Issue by jamesuber** [OpenWaterAnalytics/EPANET#595]
There is a use case (or several?) for wanting to know if a link or node participates in a simple or rule-based control. The one I have in mind is network simplification, where you want to preserve elements that do participate. This is possible using the current API functions, but I believe it's cumbersome and requires a fair amount of knowledge about the control/rule structures. 

On the other hand, incontrols() in project.c does exactly this. It would be simple to expose that, for example as another case in getlinkvalue/getnodevalue.

**Comment by samhatchett** [comment]
this is a great addition, in the category of convenience functions. Plus we have the benefit of the implementation already existing in the engine code. I will create a branch `dev_feature_in_control` to receive a PR. Thanks @jamesuber !

**Comment by samhatchett** [comment]
further conversation on this issue will be directed to #596
