### ISSUE TITLE
segmentation fault - unprotected access to unallocated en_defaultModel

### ISSUE THREAD

**Issue by mauriziocingi** [OpenWaterAnalytics/EPANET#6]
calling ENepanet (from owa_obj branch) with a non existing inpfile name gives a segmentation fault error

**Comment by mauriziocingi** [comment]
Line 240 of epanet.c checks en_defaultModel->Hydflag but en_defaultModel is NULL if ENopen exits with error 305.

Solutions

    if (en_defaultModel) {
          if (en_defaultModel->Hydflag != USE) {
              ERRCODE(ENsolveH());
          }
         ERRCODE(ENsolveQ());
         ERRCODE(ENreport());
        ENclose();
    }

or eliminate en_defaultModel->Hydflag != USE check (It seems en_defaultModel->Hydflag is always SCRATCH in ENepanet calls)

    ERRCODE(ENopen(f1, f2, f3));
    ERRCODE(ENsolveH());
    ERRCODE(ENsolveQ());
    ERRCODE(ENreport());
    ENclose();
    return(errcode);

**Comment by samhatchett** [comment]
Good suggestions. I suppose all of the old api functions that use en_defaultModel should have a similar guard on them.

**Comment by samhatchett** [comment]
partially addressed in 5504be9e467ed09cbcddc5b79a04c657e762c098

**Comment by samhatchett** [comment]
i'm closing this issue on this particular repo since all these obj-wrapped commits were shuffled off to my own repo pending full discussion about the need and implementation for this enhancement.
