### ISSUE TITLE
EN_geterror() in Usage documentation.

### ISSUE THREAD

**Issue by santisis** [OpenWaterAnalytics/EPANET#602]
From the "Detecting Error Conditions" section, "Usage" chapter of the "OWA-EPANET Toolkit" documentation:

```c
    int errcode = 0;
    char errmsg[EN_MAXMSG + 1];
...
    EN_geterror(ph, errcode, errmsg);
```

but the prototipe in `epanet2_2.h` is:
```c
int  DLLEXPORT EN_geterror(int errcode, char *out_errmsg, int maxLen);
```

so the line in the example must be:
```c
EN_geterror(errcode, errmsg, EN_MAXMSG + 1);
```

Also, the `.h` documentation says:
-  _"@param maxLen maximum number of characters that errmsg can hold"_
-  _"Error message strings should be at least @ref EN_SizeLimits "EN_MAXMSG" characters in length."_

but internally it uses `strncpy` and `snprintf`. It's unclear by the example if `EN_MAXMSG` includes the space to store the `'\0'` or it doesn't. If it includes that space the example must be fixed to `char errmsg[EN_MAXMSG];`, if it doesn't the documentation must say that "strings should be at least "EN_MAXMSG + 1" characters in length".**

** And that's consistent with epanet.c:955: `char msg1[MAXMSG+1] = "";`.

Edit: I'm newby to the library, but I can provide a PR with the fixes (if it applies).

**Comment by LRossman** [comment]
This issue was addressed in PR #704 and can therefore be closed.
