### ISSUE TITLE
What happened to the Travis CI tests

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#606]
I've noticed that over the past month (or more) the Travis CI tests are no longer being run on pull requests. Just curious as to why.

**Comment by eladsal** [comment]
I see some recent builds here:
https://travis-ci.org/github/OpenWaterAnalytics/EPANET/builds
![image](https://user-images.githubusercontent.com/1942312/87217815-1713d180-c356-11ea-9c8f-0b3c23ed76ab.png)

@LRossman are you referring to something else?

**Comment by LRossman** [comment]
So they are evidently being run but they don't show up on the PR page. Look at the recent PR #580. It says there were 3 successful checks, which are the github actions and the two Appveyor tests (32 and 64 bit). In the past it would show that there were 5 tests completed that included the Travis tests (or 4 before the actions test was recently added). For example, look at the closed PR #519 from July 2019.  It says that 4 checks passed. The `.travis.yml` file hasn't been touched since April 2019.
