### ISSUE TITLE
Unconnected nodes error message is garbled and confusing

### ISSUE THREAD

**Issue by lxsinske** [OpenWaterAnalytics/EPANET#608]
If you have a network with unconnected nodes, see attached, then the EPANET status report file produces a garbled and unclear responses in EPANET 2.2, whereas in EPANET 2.1 it was correct.

The garbled response is similar to:

>   Error 233: Error 233: Error 233: Error  3
>   Error 200: one or more errors in input file

I have identified the issue and want to push a branch with minor corrections for review. The improved error message after bugfix

 reads:

>   Error 2331: network has an unconnected node with ID:  3
>   Error 233: network has unconnected nodes

Can you provide permission that I can push the branch and create a pull request, or how best can I submit the improvement for review?

Thanks
Alex Sinske (**_lxsinske_**)
[test.zip](https://github.com/OpenWaterAnalytics/EPANET/files/5027392/test.zip)

**Comment by eladsal** [comment]
Thank you @lxsinske. You can open a pull request to the `dev` branch.

**Comment by eladsal** [comment]
Closed by #609
