### ISSUE TITLE
Inconsistent results from the .exe and .dll

### ISSUE THREAD

**Issue by Tiehong** [OpenWaterAnalytics/EPANET#627]
We discovered an interesting issue in the EPANET2.2 GUI. With the attached model, it generates pressure at junction J6 as follow:

![image](https://user-images.githubusercontent.com/3177723/106656251-717db500-6568-11eb-816e-9a57eb8225d5.png)

However, ran the same model with runepanet.exe, we got a different results:

![image](https://user-images.githubusercontent.com/3177723/106656309-86f2df00-6568-11eb-9191-6a6333ad77b2.png)

I am not sure what causes the differences. I attached the model here for you to debug:

[WWN.zip](https://github.com/OpenWaterAnalytics/EPANET/files/5914193/WWN.zip)

**Comment by LRossman** [comment]
The differences could have something to do with the spaces embedded in the object names of your file, as in:
`Structure - (28)`. The space seems to be encoded as the unicode hex character xA0 which represents a non-breaking space. It could be that the GUI is reading this character differently than the command line executable. Or it could be something else in the character encoding in the file. All I know is that if you open the file in the GUI, then export it from there to another INP file, the results from the GUI will match those obtained by running the exported file in the command line executable.

P.S. Both the GUI and engine input file parsers treat a true space character (ASCII code 32) as a token delimiter when reading a line of input, and so spaces are not allowed in object ID names (the GUI Property Editor won't accept a space in an ID name if you try to type one in).

**Comment by Tiehong** [comment]
It does not look like the names are causing the issue. I renamed all nodes/links, but the issue remained. Here is the model:

[WWNrenamed.zip](https://github.com/OpenWaterAnalytics/EPANET/files/5918619/WWNrenamed.zip)

**Comment by LRossman** [comment]
I could not reproduce the issue with the renamed file. The full status report for the GUI run matched that of the command line run as did the time series of pressure at Node 001001 (formerly J6) with -126.94 m for hours 0 to 5, 11.28 m for hours 6 to 16, and -126.94 m for hours 17 to 24.

These results were obtained with the EPANET v2.2 downloaded from the US EPA web site. Identical results were obtained if I substituted the `epanet2.dll` built from this repo's `master `branch as well as from its `dev `branch.

**Comment by Tiehong** [comment]
You are right. I just downloaded EPANET v2.2 from the US EPA web site, and I got consistent results now. However, this version has a different size of epanet2.dll (360 kb) than my previous version (287 kb). I believed that were updates in the dll since my last installation.
