### ISSUE TITLE
Bug/feature when call the function ENsettankdata

### ISSUE THREAD

**Issue by Mariosmsk** [OpenWaterAnalytics/EPANET#647]
If you call the function ENsettankdata with diameter=zero 

`ENsettankdata(tankIndex, elev, intlvl, minlvl, maxlvl, 0, minvol, volcurve)
`
you can change the node type from tank to reservoir!

**Comment by LRossman** [comment]
I'd call it a feature 😁 . I'd vote to leave it as is and not break backward compatibility for such an uncommon action.
