### ISSUE TITLE
Automating EPANET Compile on Windows --- Help wanted for testing

### ISSUE THREAD

**Issue by eldemet** [OpenWaterAnalytics/EPANET#65]
If you are a Windows user, and you have a few minutes, I would like your assistance in testing the automated script we prepared with @eladsal  for compiling `EPANET` for Windows.

**No programming skills are needed, you just need to run a `.bat` script.** 

You should have installed the [Microsoft Windows SDK 7.1](https://www.microsoft.com/en-us/download/details.aspx?id=8279) (You can check if you have this if you have this folder `C:\Program Files\Microsoft SDKs\Windows\v7.1\` or if you have a `Microsoft Windows SDK 7.1` folder in your Programs/Apps list.
- Download https://github.com/OpenWaterAnalytics/EPANET/archive/dev-2.1-win-makefile.zip
- Unzip anywhere
- Go to \build\WinSDK\
- Execute `Makefile.bat`

Executing `Makefile.bat` will call the `Microsoft Windows SDK 7.1 Command Line`, and  execute the compilation script of the DLL and the EXE. 
Then it will copy the .dll, .exe and .h files in folders `\64bit`, `\32bit` and `\32bitVB`.
The last folder builds the DLL by using the .def file (included in the `\WinSDK` folder), which seems to necessary in VB applications.

In case something does not work as it should, please let us know of your Windows configuration (Windows version, Intel/AMD, Windows SDK installation problems) as well as any error messages which could appear. 

Thanks, and wishes for a great new year!

**Comment by dweintrob** [comment]
Hi,
1. Thank you for this important project.
2. This not realy an EPANET problem, but while installing windows sdk I got this error. I don't seek for a solution here, just letting you know.

Danny

![image](https://cloud.githubusercontent.com/assets/12900068/12181676/61572e68-b58c-11e5-9c93-24de92d2fe74.png)

**Comment by eladsal** [comment]
@dweintrob thanks for helping with this :)

Sometimes uninstalling "Microsoft Visual C++ 2010 Redistributable" (both x86 and x64) solves this problem. The SDK will reinstall it or you can reinstall it later.

**Comment by eldemet** [comment]
This is a good point. Unfortunately this problem is quite common:

According to Microsoft: https://support.microsoft.com/en-us/kb/2717426

>RESOLUTION
>To resolve this issue, you must uninstall all versions of the Visual C++ 2010 Redistributable before installing the Windows 7 SDK.  You may have one or more of the following products installed:
>
>   Microsoft Visual C++ 2010 x86 Redistributable
>    Microsoft Visual C++ 2010 x64 Redistributable
>
>After uninstalling the Microsoft Visual C++ 2010 Redistributable products, you may install the Windows 7 SDK.  After installing the Windows 7 SDK, you may then reinstall the newer version of the Visual C++ 2010 Redistributable products, in order to restore the Visual C++ 2010 Redistributable products to their original state.

**Comment by eldemet** [comment]
@eladsal how about we automate the creation of the DEF file instead of doing it manually? e.g. using [expdef.exe](http://purefractalsolutions.com/show.php?a=utils/expdef)

**Comment by eladsal** [comment]
Sure thing. _expdef_ is not open source, right?

**Comment by eldemet** [comment]
Well, i don't know its license, but the source code is available: http://purefractalsolutions.com/show.php?a=src/expdefsrc

**Comment by eladsal** [comment]
O, we can try it, seems simple.

**Comment by goanpeca** [comment]
I will try to create [conda packages](http://conda.pydata.org/docs/intro.html) for EPANET, working on it this week :-)

**Comment by eladsal** [comment]
Thank you @bouziot , for V2.1 we have the compiled DLLs also for 64bits:
https://github.com/OpenWaterAnalytics/EPANET/releases/tag/v2.1

**Comment by eladsal** [comment]
@eldemet can we close this issue?
