### ISSUE TITLE
Simultaneous hydraulic and water quality analysis

### ISSUE THREAD

**Issue by dbhart** [OpenWaterAnalytics/EPANET#653]
I remember hearing that the new version of EPANET would allow for hydraulic and water quality to be calculated simultaneously (or near simultaneously) instead of having to step through the entire hydraulics and then the entire water quality. Has this occurred, or is that for a different version (epanet-dev) of the code completely?

Thank you,

**Comment by LRossman** [comment]
Yes, the v2.2 toolkit gives developers the option of solving hydraulics and water quality either sequentially (as before) or concurrently. Please see the **Computing Water Quality** topic on the [Usage page](http://wateranalytics.org/EPANET/toolkit-usage.html) of the toolkit users guide. The distributed v2.2 command line executable as well as EPA's release of the graphical user interface for v2.2 still solves hydraulics and water quality sequentially.

**Comment by dbhart** [comment]
Thank you Lew!

I was apparently doing things in the wrong order, which is why it was crashing. This is a huge help, and I hadn’t found the new toolkit docs previously, so thank you!
