### ISSUE TITLE
Can node1 and node2 (in [PIPES]) be swapped safely without changing the semantics?

### ISSUE THREAD

**Issue by aferust** [OpenWaterAnalytics/EPANET#656]
Dear maintainers,

I would like to ask a question related to node numbering in inp files. I am trying to generate an inp file programmatically. I wonder if node1 and node2 (in [PIPES]) can be swapped safely without changing the semantics of the algorithm? Or does each one represent a particular thing like the start and end node?

Thank you in advance

**Comment by LRossman** [comment]
Yes, the nodes of a pipe can be switched without any effect on the solution except to change the sign of the computed flow value. The one exception would be if the pipe contains a check valve. Other types of directional links, such as pumps, PRVs and PSVs  will also result in a different solution if you switch their start and end nodes.

**Comment by aferust** [comment]
Thank you for the information. Then I assume that the EPANET determines and re-assign node1 and node2 to be start node or end node implicitly. Please confirm and close the issue.
