### ISSUE TITLE
Emitter flows can be negative if node pressure is negative

### ISSUE THREAD

**Issue by allenmlowe** [OpenWaterAnalytics/EPANET#659]
![Emitter](https://user-images.githubusercontent.com/39788972/141751764-4bb57283-9b23-4c6d-976a-1bfda126cf8f.jpg)
[net1_Emitter.inp.txt](https://github.com/OpenWaterAnalytics/EPANET/files/7537240/net1_Emitter.inp.txt)

**Comment by samhatchett** [comment]
I think the only thing that is unexpected (or possibly a bug) is that the engine does not produce the usual warning message described in the user's manual:

> EPANET will issue a warning message when it encounters negative pressures at junctions that have positive demands. This usually indicates that there is some problem with the way the network has been designed or operated. Negative pressures can occur when portions of the network can only receive water through links that have been closed off. In such cases an additional warning message about the network being disconnected is also issued.

Under normal circumstances, negative pressures would be considered a modeling error. There may be reasons to ignore negative pressures for junctions without demand where elevation is not known or irrelevant. However EPANET's position toward negative demands created in emitters is ambiguous. 

Any other perspectives on this @LRossman @jamesuber @eladsal ?

**Comment by allenmlowe** [comment]
There was no negative pressure warning because the emitter node has negative demand and acted as a source. Can the emitter be limited to 0 when the emitter flow becomes negative?

**Comment by allenmlowe** [comment]
Thank you @LRossman. The submitted example was simplified so as to see right away the problem with negative emitter flows. Originally the nodes with emitter have also demands on them but since Epanet GUI's actual demand only has the combined water demand, instead of actual node demand and emitter flow, I removed the base demand so that actual demands were only by emitters. I first noticed that actual demands were reduced when the node pressure was negative. Node 3 should not have a demand below 100, but for all the times it has negative pressures, actual demand were all reduced to below 100 because of the negative emitter flows.

I would be nice if the actual demand in the report can be also be separated into the actual demands and emitter flows.
![Emitter2](https://user-images.githubusercontent.com/39788972/141884279-cd7b5ed0-5e19-4824-978c-2852f5bfeb02.jpg)

[net1_Emitter2.inp.txt](https://github.com/OpenWaterAnalytics/EPANET/files/7542857/net1_Emitter2.inp.txt)

**Comment by LRossman** [comment]
PR #706 has been submitted that adds a new global hydraulic option, EN_EMITBACKFLOW, that allows back flow (negative flow) through emitters if equal to 1 (the default) and prevents back flow if equal to 0. The attached file, based on @allenmlowe 's example, provides a test of this feature. 
[EmitterTest.inp.txt](https://github.com/OpenWaterAnalytics/EPANET/files/10612087/EmitterTest.inp.txt)

With back flow allowed, the flow through the emitter at node W-1 is:
![Backflow](https://user-images.githubusercontent.com/12769926/216843184-f0a44d96-ff1e-4f1c-bec4-62f20e4df7a7.png)
while with back flow not allowed we get:
![NoBackflow](https://user-images.githubusercontent.com/12769926/216843229-08c2b9e1-8ef9-4e13-8ffc-804ba2984bb1.png)
