### ISSUE TITLE
Error While trying to load NodeCoordinates in Epanet/Matlab

### ISSUE THREAD

**Issue by Alexandroz** [OpenWaterAnalytics/EPANET#68]
Hi,
I am using the latest version of Epanet-Matlab Class Master and Matlab R2015a. When i am trying to load the d.getNodeCoordinates command i get this error:

Error using fopen
File identifier must be an integer-valued scalar of type
double.

Error in epanet>readAllFile (line 8194)
    fid = fopen(inpname, 'rt');%or msxname

Error in epanet/readInpFile (line 5683)
                [info,tline,allines] =
                readAllFile(obj.Bintempfile);

Error in epanet/getNodeCoordinates (line 6041)
            [~,info] = obj.readInpFile;

I am not sure but a relevant error is generated while i am trying to use the d.plot commands.Which is the following:
 
Error using fopen
File identifier must be an integer-valued scalar of type
double.

Error in epanet>readAllFile (line 8194)
    fid = fopen(inpname, 'rt');%or msxname

Error in epanet/readInpFile (line 5683)
                [info,tline,allines] =
                readAllFile(obj.Bintempfile);

Error in epanet/getNodeCoordinates (line 6041)
            [~,info] = obj.readInpFile;

Error in epanet>ENplot (line 7922)
        v.nodecoords=obj.getNodeCoordinates;

Error in epanet/plot (line 721)
            [value] = ENplot(obj,'bin',0,varargin{:});
 

Thank you.

**Comment by Mariosmsk** [comment]
Hi @Alexandroz, 
Please, because this is not an EPANET issue, you can create an issue here [EPANET-Matlab-Class](https://github.com/KIOS-Research/EPANET-Matlab-Class/issues). 

Thanks,
Marios
