### ISSUE TITLE
Add support for Conan dependency manager

### ISSUE THREAD

**Issue by samhatchett** [OpenWaterAnalytics/EPANET#680]
Conan is a widely used C/C++ package manager. It allows calling projects to pull in deps based on a repo url, and will automatically build epanet as a part of a larger project.

The addition would be a single python file at the top level that specifies some basic build configuration info. I have an example ready to go into a PR if interested.

https://conan.io/

**Comment by LRossman** [comment]
I have no objections - go for it.

**Comment by Mariosmsk** [comment]
looks good addition!
