### ISSUE TITLE
Strange water age results across pumps operated by simple control.

### ISSUE THREAD

**Issue by jamesuber** [OpenWaterAnalytics/EPANET#686]
[WestMeadePark.inp.zip](https://github.com/OpenWaterAnalytics/EPANET/files/9005752/WestMeadePark.inp.zip)

The attached is a small section of a larger network where a pumping station operated by simple controls delivers water to a small pressure zone containing a tank. Running this for 168:00 duration, the age at the suction of the pump station (junction 113-027) is a little weird - the 50 hours from the upstream reservoir connected by a short pipe, but I can't explain the fluctuation observed. The water in the pipe from the reservoir is stagnant much of the time, punctuated by short duration pumping periods of 1-3 hours.

But it's the discharge water age from the pump station (PS32) that has me scratching my head. It starts from zero and increases one hour for every simulation hour, as though water were stagnant with nothing coming out of the pump station. Yet there are the periodic flows through the station as described above - driven by simple control statements.

Has anyone seen odd water age behavior before, perhaps in conjunction with a pump station controlled in a similar manner? I can investigate but wanted the benefit of your experience before doing that.

**Comment by eladsal** [comment]
Hi Jim,

For the first issue, you have an initial quality value of 50 at the reservoir, which explains the jump to 50 hours at the first junction once "fresh" water reaches it.

As for the water age at PS32, fresh water from the reservoir did not reach it after one week. The pumps' flow is low but the main thing is that the suction and discharge pipes are huge 99". The main pipe coming out of the station is only 8" so try similar values.

**Comment by jamesuber** [comment]
Thanks Elad! Internally, I knew it had to be user error.
