### ISSUE TITLE
Travis CI tests not working for over a year

### ISSUE THREAD

**Issue by eladsal** [OpenWaterAnalytics/EPANET#693]
Following some discussion of failing tests, @LRossman pointed out that although the Travis-CI badge shows that it is passing, the tests are not really working. It seems that `travis-ci.org` is not supported anymore by GH and should be moved to `travis-ci.com`, see message [here](https://travis-ci.org/github/OpenWaterAnalytics/EPANET).

We are also using the `appveyor` tests, which work nicely. I don't have the knowledge to make the changes to the Travis tests, so if there is anyone here who can help, that would be great. If not, I can remove the Travis badge from the readme file.

**Comment by Mariosmsk** [comment]
Hi Elad, I think you can try to select your GitHub account from https://app.travis-ci.com/signup and select the EPANET repo.

**Comment by eladsal** [comment]
Thank you @Mariosmsk , I see the repo and the badge image there, but I don't see any test results. Even if I'm logged in.
https://app.travis-ci.com/OpenWaterAnalytics/EPANET

Do you have access to the test results?

**Comment by Mariosmsk** [comment]
No, I can't see the results!
Maybe you need to add a new commit to start the Travis? 

![image](https://user-images.githubusercontent.com/2945956/183043879-be1e097e-6a72-4848-8f18-60a22341582d.png)

**Comment by eladsal** [comment]
I see that the `free` plan is bound by some credits, which are relatively high. However, even this plan requires a credit card. I think we shouldn't use this service. Thoughts?
https://docs.travis-ci.com/user/billing-overview/

**Comment by lbutler** [comment]
@eladsal have you considered switching the tests to use Github Actions? I'm not familiar with how they work with a project in C but I use it in my epanet-js library and it was relatively simple to set up.

**Comment by eladsal** [comment]
@lbutler, are you referring to what is partially discussed here?

**Comment by eladsal** [comment]
@lbutler, are you referring to what is partially discussed here?
