### ISSUE TITLE
Energy Calculations for Variable Speed Pumps

### ISSUE THREAD

**Issue by sarptas** [OpenWaterAnalytics/EPANET#71]
As reported by [Marchi, A. and Simpson, A. (2013)](http://dx.doi.org/10.1061/%28ASCE%29WR.1943-5452.0000273) and [Georgeous et al. (2014)](https://www.researchgate.net/publication/269707128_Estimation_of_the_Efficiency_for_Variable_Speed_Pumps_in_EPANET_Compared_with_Experimental_Data), EPANET 2 does not properly take into account the affinity laws in the efficiency computation when the speed changes for variable speed pump (VSP) operations.

These researchers concluded that:

> EPANET transposes correctly the head versus flow rate curve according to the affinity laws, but does not alter the efficiency curve of a pump that operates at a rotational speed different than the nominal speed. In this respect, energy consumption studies that imply variable speed pumps, performed with EPANET are unreliable.

I've checked and distinguished that **the problem still exist in EPANET 2.1 release.!** (In a test network with a VSP pump and demand pattern, daily energy consumptions and associated costs are the same for both EPANET 2.0 (of USEPA) and EPANET 2.1.

**Solution**

[Marchi, A. and Simpson, A. (2013)](http://dx.doi.org/10.1061/%28ASCE%29WR.1943-5452.0000273) proposed a correction in EPANET 2 source code for energy calculations for VSP operations.

> **Appendix I. How to Correct EPANET 2 Source Code to Compute the Efficiency of VSPs with the Affinity Laws** To take into account the affinity laws for efficiency computation in the source code of EPANET 2 (Rossman 2000), **it is sufficient to modify the hydraulic.c file** of the source code and, in particular, the input to the function interp() called by getenergy(). The original function interp() computes the efficiency by interpolating the efficiency curve inserted in input. As it uses the flow computed for the specific time step at the reduced pump speed, q, and the efficiency curve at the nominal speed, it is necessary to modify one of these two inputs to retrieve the correct efficiency. The most efficient way to do this is converting the reduced speed flow q to the nominal speed flow, q4eff. In this way, the flow is rated to the nominal speed and can be used with the efficiency curve at the nominal pump speed. As in EPANET 2, the speed reduction is inserted as a speed rate (i.e., the nominal pump speed corresponds to the speed rate equal to 1), the reduced flow q is divided by the pump speed rate of the current time step. The modifications in the function getenergy() are shown in italics.

![corr1](https://cloud.githubusercontent.com/assets/3170160/17198511/683adbb2-547e-11e6-8919-c911eae10f3a.PNG)

> **Appendix II. How to Modify EPANET 2 Source Code to Retrieve Pump Efficiency Directly** To retrieve pump efficiency as an output of EPANET toolkit (Rossman 2000), three files of the source code need to be modified:toolkit.h, epanet.h, and epanet.c.As in the toolkit.h and epanet.h, different parameter codes are defined to refer to properties of the model components (e.g., the value 0 corresponds to the pipe diameter, the value 8 corresponds to the pipe flow), a new parameter code, 14, has been added to the list of link properties that can be retrieved using the function ENgetlinkvalue(). This function has been modified by consideringthe additional query for efficiency that is added at the end of the function. In the following, the modification of files and the function are highlighted in bold.

![corr2](https://cloud.githubusercontent.com/assets/3170160/17198656/c278124c-547f-11e6-96e6-fb4560be166c.png)

I hope this helps developers to correct the code for energy calculations in VSPs.

**Comment by samhatchett** [comment]
Thanks for the detailed writeup. Pull requests are welcome and encouraged!

**Comment by samhatchett** [comment]
I think this is literally a 1-line change. We have this correction in a development branch but neglected to incorporate here. If anyone wants to open the PR and get eternal fame, be my guest. Please PR into the dev branch. 

https://github.com/samhatchett/EPANET/commit/716b440716e608c3f4eb3017723c7a77af6480b1

**Comment by eladsal** [comment]
I have talked with Angela and once she gets into GH she will contribute this and other code she has.

**Comment by samhatchett** [comment]
#81 is merged so closing. Thanks all!
