### ISSUE TITLE
#EPANET user-friendly improvements.

### ISSUE THREAD

**Issue by PaulOdendaal** [OpenWaterAnalytics/EPANET#711]
I wish to recommend the following easy to implement user-friendly improvements. It is quite frustrating for me to reset these every time I open the program.

There are things which a user may select like:

File>Preferences>Formats. Setting decimals for various parameters. The choice of the user can be saved in the Windows Registry. I use SaveSettings in VB6 , but C will have a different statement. Each time the user opens the program, these setting can be read from the Registry  and applied to the Preferences (I use GetSettings in VB6). It now jumps back to the hard coded settings.

View>Options>Map Options>Notation. The font size the user works with can also be saved and read from the registry, as presently, when the program is opened,  it jumps back to the hard coded settings. 

Project>Defaults>Hydraulics. In flow units the most basic unit of the metric system is m³/s (kg/m/s) as CMS or Cumec, is not listed and for large schemes CMD gets into the millions or billions. CMS is about 10^5 smaller and m³/s is normally significant to 3 decimals (Litre/Second) which you have.

On the Browser, the selection a user makes, can also be saved and read again. I am referring to what is normally selected by the user. In my case it is pressure at nodes and flow in pipes, Presently it jumps back to no selection when the program is opened. 

The options a user has, are all over the menus. One single main menu item could be 'Options' which can include the following in submenus or one large frame with all the settings will be even better.

File>Preferences
View>Dimensions
View>Legends>Modify
Project>Defaults
Project>Analysis options

Thanks

PK

**Comment by LRossman** [comment]
These are useful comments but, with one exception, they all refer to the EPANET's graphical user interface (GUI). This GitHub project deals only with EPANET's numerical solver so there is no way it can implement your suggestions. Since the GUI is still under the control of U.S. EPA I suggest that you post your comments on their [GitHub site](https://github.com/USEPA/EPANET2.2).

The one suggestion that can be implemented under this project is adding CMS as a flow units option. You might want to submit this as a separate issue with an "Enhancement" label so someone can volunteer to implement it.

**Comment by PaulOdendaal** [comment]
Thanks LRossman. I will do.

PK

**Comment by PaulOdendaal** [comment]
Mr. Lew Rossman,

 

May I ask two questions in Epanet?

 

1.	On page 189 of the User Manual, you have a formula for f. It seems to me that the Ln in the formula should be replaced with Log. Is that correct?
2.	On page 188, why do you use the inverse whilst on page 187 under D1, you do not use the inverse.
3.	On page 31 table 3.1, you have formulae for Hazen Williams and Darcy Weisbach in imperial units. What are the formulae in metric units.

 

Kind regards

PK

 

P.K. Odendaal - B.Sc.Eng. Hons., Pr.Eng., Pr.S.Arch.T, Pr.CPM (ret.), Com. pilot.

Cell: +27 83 255 9898 Email: ***@***.*** ; 

Odendaal & Associates Consulting (Pty) Ltd. www.odendaal.com

Pro Housing Group www.prohousing.co.za ; 

CivilsForAfrica (Pty.) Ltd. (Botswana) www.civilsforafrica.com

AfrikaGroep  www.afrikagroep.com ; 

My blog https://pkodendaal.blogspot.com

**Comment by LRossman** [comment]
To answer your questions:


  1.  The Ln in the formula has been replaced with Log in the latest on-line user’s manual for version 2.2<https://epanet22.readthedocs.io/en/latest/12_analysis_algorithms.html>.
  2.  I assume you are referring to the expression for pij which is the inverse of the derivative of the head loss equation D.1 with respect to flow. You would have to look at the derivation of the Global Gradient solution method to see where this expression came from. But conceptually, if equation D.3, AH = F, is solved to find new nodal heads H and F contains flow terms for each node (basically inflow – outflow plus a correction term), then the coefficients contained in A must consist of a flow value divided by a head value. These coefficients are built from the pij values for each pipe (= 1/(dHij/dQij)) with units of flow divided by head.
  3.  For metric  units the constant in the Hazen-Williams formula is 10.68. For Darcy-Weisbach it is 1/12.1.

**Comment by PaulOdendaal** [comment]
Lew, thank you so much for an elaborate reply. I appreciate.
Pk

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by PaulOdendaal** [comment]
Hi Lew,

 

I have been working with Epanet for the past month or so. Although I have the greatest respect for you and Epanet, I find it too cumbersome for my purposes.

I now want to do my own abridged version of the Water Network Analysis for my own purposes. 

I am a consulting civil engineer specializing in small and massive bulk water schemes. 

I have 55 years programming experience in programming and presently program in VB6, and I can translate from other languages like Fortran and C into VB6.

In view of your comment that there are certain license issues with Epanet, I cannot really ask or pursue changes for that, apart from the units which you so kindly attended to.

I am quite conversant with all that goes into the program, but from the literature, I struggle to bring the nomenclature to actual values in the matrices.

I know you are very busy, but I take the boldness to ask you to guide me along the way. 

In fact, you may participate with me in doing a commercial product for the average small user.

Presently I am trying to interpret the second term in the formula:

 

gij=nr|qij|n-1 + δr/δqij |qij|n + 2m|qij|

Kind regards

PK

 

P.K. Odendaal - B.Sc.Eng. Hons., Pr.Eng., Pr.S.Arch.T, Pr.CPM (ret.), Com. pilot.

Cell: +27 83 255 9898 Email: ***@***.*** ; 

Odendaal & Associates Consulting (Pty) Ltd. www.odendaal.com

Pro Housing Group www.prohousing.co.za ; 

CivilsForAfrica (Pty.) Ltd. (Botswana) www.civilsforafrica.com

AfrikaGroep  www.afrikagroep.com ; 

My blog https://pkodendaal.blogspot.com

**Comment by PaulOdendaal** [comment]
Sorry, it was an oversight. I found the answer.

PK

 

 

From: ***@***.*** 
Sent: 02 May 2023 07:24
To: 'OpenWaterAnalytics/EPANET' ***@***.***>
Subject: RE: [OpenWaterAnalytics/EPANET] #EPANET user-friendly improvements. (Issue #711)

 

Hi Lew,

 

I have been working with Epanet for the past month or so. Although I have the greatest respect for you and Epanet, I find it too cumbersome for my purposes.

I now want to do my own abridged version of the Water Network Analysis for my own purposes. 

I am a consulting civil engineer specializing in small and massive bulk water schemes. 

I have 55 years programming experience in programming and presently program in VB6, and I can translate from other languages like Fortran and C into VB6.

In view of your comment that there are certain license issues with Epanet, I cannot really ask or pursue changes for that, apart from the units which you so kindly attended to.

I am quite conversant with all that goes into the program, but from the literature, I struggle to bring the nomenclature to actual values in the matrices.

I know you are very busy, but I take the boldness to ask you to guide me along the way. 

In fact, you may participate with me in doing a commercial product for the average small user.

Presently I am trying to interpret the second term in the formula:

 

gij=nr|qij|n-1 + δr/δqij |qij|n + 2m|qij|

 

Kind regards

PK

 

P.K. Odendaal - B.Sc.Eng. Hons., Pr.Eng., Pr.S.Arch.T, Pr.CPM (ret.), Com. pilot.

Cell: +27 83 255 9898 Email: ***@***.*** ***@***.***>  ; 

Odendaal & Associates Consulting (Pty) Ltd. www.odendaal.com <http://www.odendaal.com> 

Pro Housing Group www.prohousing.co.za <http://www.prohousing.co.za>  ; 

CivilsForAfrica (Pty.) Ltd. (Botswana) www.civilsforafrica.com <http://www.civilsforafrica.com> 

AfrikaGroep  www.afrikagroep.com <http://www.afrikagroep.com>  ; 

My blog https://pkodendaal.blogspot.com

**Comment by PaulOdendaal** [comment]
Hi Lew,

 

Sorry to trouble,

I need an example I can work on, to test my results. Do you perhaps have an example with its matrix values that I can use.

 

Kind regards

PK  

 

 

 

From: ***@***.*** 
Sent: 02 May 2023 12:10
To: 'OpenWaterAnalytics/EPANET' ***@***.***>
Subject: FW: [OpenWaterAnalytics/EPANET] #EPANET user-friendly improvements. (Issue #711)

 

Sorry, it was an oversight. I found the answer.

PK

 

 

From: ***@***.*** ***@***.***>  
Sent: 02 May 2023 07:24
To: 'OpenWaterAnalytics/EPANET' ***@***.*** ***@***.***> >
Subject: RE: [OpenWaterAnalytics/EPANET] #EPANET user-friendly improvements. (Issue #711)

 

Hi Lew,

 

I have been working with Epanet for the past month or so. Although I have the greatest respect for you and Epanet, I find it too cumbersome for my purposes.

I now want to do my own abridged version of the Water Network Analysis for my own purposes. 

I am a consulting civil engineer specializing in small and massive bulk water schemes. 

I have 55 years programming experience in programming and presently program in VB6, and I can translate from other languages like Fortran and C into VB6.

In view of your comment that there are certain license issues with Epanet, I cannot really ask or pursue changes for that, apart from the units which you so kindly attended to.

I am quite conversant with all that goes into the program, but from the literature, I struggle to bring the nomenclature to actual values in the matrices.

I know you are very busy, but I take the boldness to ask you to guide me along the way. 

In fact, you may participate with me in doing a commercial product for the average small user.

Presently I am trying to interpret the second term in the formula:

 

gij=nr|qij|n-1 + δr/δqij |qij|n + 2m|qij|

 

Kind regards

PK

 

P.K. Odendaal - B.Sc.Eng. Hons., Pr.Eng., Pr.S.Arch.T, Pr.CPM (ret.), Com. pilot.

Cell: +27 83 255 9898 Email: ***@***.*** ***@***.***>  ; 

Odendaal & Associates Consulting (Pty) Ltd. www.odendaal.com <http://www.odendaal.com> 

Pro Housing Group www.prohousing.co.za <http://www.prohousing.co.za>  ; 

CivilsForAfrica (Pty.) Ltd. (Botswana) www.civilsforafrica.com <http://www.civilsforafrica.com> 

AfrikaGroep  www.afrikagroep.com <http://www.afrikagroep.com>  ; 

My blog https://pkodendaal.blogspot.com
