### ISSUE TITLE
EN_setflowunits doesn't adjust other network data when flow units change

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#720]
I thought this issue  might have been raised before but I couldn't find it in the open issue list.

Currently when `EN_setflowunits()` is used to switch flow units it only updates the units of Curve data. Other flow data, such as demands, are not changed. It also doesn't change other non-flow data, such as pipe diameters and distances, node elevations, tank dimensions, etc., when the flow units change causes a change between US and metric units.

What about adding a new function, `EN_convertunits()`, that takes the desired flow units as an argument (and possibly the desired pressure units as well) and does a global conversion of all network data, including the values used in controls, rules, and analysis options.

**Comment by Mariosmsk** [comment]
Hi @LRossman,  I think that by utilizing the EN_setflowunits(units) function, the network data changes (including basedemands, elevations, etc.). However, maybe it is better with adding a new function like EN_convertunits(), as it's more clear!

https://github.com/OpenWaterAnalytics/EPANET/issues/125

https://github.com/OpenWaterAnalytics/EPANET/commit/d2503bc0355029cb8aff87577aa5d739ff4585fe

**Comment by LRossman** [comment]
This issue has been resolved by PR #719 and can be closed.
