### ISSUE TITLE
Constraints for geometric data in Epanet 

### ISSUE THREAD

**Issue by cdzuwa** [OpenWaterAnalytics/EPANET#724]
I haven't gone through all the major revisions made so far but i would like to know if there is a robust mechanism for checking geometric data in Epanet? I described an issue in this [document](https://docs.google.com/document/d/1ykMX7iT7fS2s2PJicVGrmVRvho9qRCjJ/edit?usp=sharing&ouid=109172339687048260912&rtpof=true&sd=true) that might be of interest to the community. This issue was identified while working on the C-TOWN Network.

**Comment by LRossman** [comment]
The elevations assigned to junction nodes in a water network model do not necessarily represent the elevations of the end points of the pipes. Other options include ground elevations, hydrant elevations, and service connection elevations. Which ones are chosen depends on where accurate pressure readings are needed. (See pages 89 - 90 in [Advanced Water Distribution Modeling and Management).](https://www.amazon.com/Advanced-Water-Distribution-Modeling-Management/dp/0971414122). Therefore I don't think it's possible to apply a general geometry check (such as pipe length > elevation drop) within Epanet without knowing what each junction elevation was based on.
