### ISSUE TITLE
How to go to \build\WinSDK\ for running v2.1 latest release

### ISSUE THREAD

**Issue by DevJigna** [OpenWaterAnalytics/EPANET#73]
Dear Sir,

Delighted to listen this news, i am using EPANET AND WATERNETGEN for my doctoral research.

I have downloaded the v2.1 but it is not running as an application.

How to use this code?

Do i require to have matlab platform?

Please guide how to use these binaries? This newly developed version of EPANET?

I have read the instructions and got windows sdk7.1 but--

Download https://github.com/OpenWaterAnalytics/EPANET/archive/dev-2.1-win-makefile.zip9
Unzip anywhere
Go to \build\WinSDK\
Execute Makefile.bat

how to go to \build\WinSDK\?

Please explain.

Thanking you,

D.A. Shah

**Comment by DevJigna** [comment]
Ok got it now i can go there to 

\build\WinSDK\

but 'Access is denied' after the call to each DLL.

**Comment by samhatchett** [comment]
Unless you really need to build on your platform, you can download pre-compiled binaries here: https://github.com/OpenWaterAnalytics/EPANET/releases/tag/v2.1 -- look for epanet-2.1-win.tar.gz

However, I'm not sure that using WaterNetGen is going to work here since it's not going to call the DLL - am I right in this @eladsal ? Or am I mis-remembering?

**Comment by DevJigna** [comment]
Thanks for prompt reply. I download pre compiled binaries, but i am new to this and do not know how to run these binaries?

**Comment by eladsal** [comment]
@DevJigna the DLL binaries are not standalone applications. They are called (used) by other applications. I'm not sure about WaterNetGen but you may try and contact the [developers](http://www.dec.uc.pt/~WaterNetGen/).

**Comment by eldemet** [comment]
@DevJigna you don't need Matlab to use EPANET; in fact you can use any programming language which reads libraries such as DLLs (most do). However, you *do* need to use a programming language to write the program (e.g. Matlab, Python, R, C/C++, Visual Basic), and understanding on how to code is required. For more specific assistance, you are welcome to join our community forum at http://community.wateranalytics.org/.

**Comment by samhatchett** [comment]
closing stale issue.
