### ISSUE TITLE
Use Percentages Instead of Fractions for PCV Curves

### ISSUE THREAD

**Issue by LRossman** [OpenWaterAnalytics/EPANET#745]
PR #699 added a Positional Control Valve to EPANET's valve types that requires a user supply a valve characteristic curve showing relative flow coefficient Kv/Kvo as a function of the amount the valve is opened. Both of these variables were expressed as fractions. However it appears that most published data represent these curves using percentages rather than fractions, so I propose that we do the same (just like we use percentages for a pump's efficiency curve). We would also need to change the PCV setting to be a percent open rather than a fraction open. If there is agreement on this I will submit a PR to implement it.

**Comment by lbutler** [comment]
In my experience, commercial vendors that have implemented valves similar to the new PCV type utilize percentages in their software. 

Also as you mentioned, percentage is already used with pumps so there would be further constancy.

I would be supportive of the switch and I reacted with a thumbs up in support.

**Comment by LRossman** [comment]
This issue has been addressed by PR #747 and can be closed.
