### ISSUE TITLE
Issue with Volume Curve in Tanks in latest code. Works successfully in version 2.2

### ISSUE THREAD

**Issue by allenmlowe** [OpenWaterAnalytics/EPANET#767]
Error 225: invalid lower/upper levels for tank node 2

[Net1-VolumeCurve.inp.txt](https://github.com/OpenWaterAnalytics/EPANET/files/14047878/Net1-VolumeCurve.inp.txt)

**Comment by LRossman** [comment]
Thanks @allenmlowe . There was a bug in the newly added validation check on tank min/max levels being within the limits of the tank's volume curve. A fix has just been added to the `dev `branch.

**Comment by allenmlowe** [comment]
Thank you @LRossman for the prompt response.
