### ISSUE TITLE
Water Age is wrong for zero-demand junctions adjacent to closed valves

### ISSUE THREAD

**Issue by samhatchett** [OpenWaterAnalytics/EPANET#77]
Only for closed "valve" elements; not pipes and not for zero-demand dead-end junctions - upstream/downstream junctions report incorrect water age during an age simulation, if those junctions have zero (0) demand. The reported age seems to bump around in the 0.1 range, with temporary excursions into a normal 1-hr-per-hour (45-degree slope).

**Comment by eladsal** [comment]
Can you please check what happens if there is an initial quality value at these junctions. Also, do you see the same behavior with a water quality run (say Chlorine)?

**Comment by michaeltryby** [comment]
https://github.com/OpenWaterAnalytics/EPANET/issues/245#issuecomment-483489056

https://github.com/OpenWaterAnalytics/EPANET/issues/245#issuecomment-483734365
