### ISSUE TITLE
Create conda packages

### ISSUE THREAD

**Issue by goanpeca** [OpenWaterAnalytics/EPANET#78]
I think creating conda packages for this different products would definitely allow a bigger audience working on engineering and scientific applications. I would like to create conda packages for the different projects hosted at open water analytics.

Are you familiar with [conda](http://conda.pydata.org/docs/intro.html)? and [Anaconda](https://www.continuum.io/downloads)?

Any thoughts?

Cheers :-)

**Comment by goanpeca** [comment]
Since this is an open source and community maintained version of the epanet engine, I am thinking of naming this (conda) package as **openepanet** or **open-epanet**. Once the packages are ready one could cross platform install epanet as

`conda install open-epanet`  (or whatever name we think is best)

What do you guys think?

**Comment by goanpeca** [comment]
Anyone?

**Comment by michaeltryby** [comment]
@goanpeca I've read up on conda and been playing with it some. What I have learned so far has been very useful. I think developing conda packages would be a productive experiment.

**Comment by goanpeca** [comment]
:+1:

**Comment by samhatchett** [comment]
What would conda require of this project? Help us understand what needs to be added or modified in the repo. Conda seems useful so I'd say go for it - however it appears that you could set up a conda recipe repo and manage it separately from EPANET. If that's the case, we can give you an empty repo here on OWA for that purpose.

**Comment by goanpeca** [comment]
Hi @samhatchett,

> What would conda require of this project? 

I think I have all I need in the build folder... the cmake is enough actually

> Help us understand what needs to be added or modified in the repo.

A standard procedure for projects that use conda is to have a **conda.recipe** folder, so I would make a PR that would create that folder and add the recipe to it.

>Conda seems useful so I'd say go for it 

It is, you wont regret it ;-)

>however it appears that you could set up a conda recipe repo and manage it separately from EPANET.

Yes, recipes can be maintained outside of the actual projects, but a cleaner convention is to include it with the project.

>If that's the case, we can give you an empty repo here on OWA for that purpose.

I don't think is needed, let me have the recipes working and I can explain better what we can do with it. (I made a linux pacakge just for a quick test already)

----

Next steps

With the conda packages available other CI services can be hooked to always make sure that the changes work on all platforms.

----

I see that the current builds fails due to a failing test, is that recent?

**Comment by michaeltryby** [comment]
I am in favor of this. My only hesitation is that while the dlls compile and run on Mac and Linux platforms we haven't audited the results to insure they are accurate. Same for compiling 64 bit. I suppose this is the first step in the process.

**Comment by goanpeca** [comment]
>My only hesitation is that while the dlls compile and run on Mac and Linux platforms we haven't audited the results to insure they are accurate. Same for compiling 64 bit. I suppose this is the first step in the process.

Having the infrastructure I just outlined would make the testing process much much simpler. I don't plan to release this officially or point the users in that direction (yet), while we check what you outlined.

* Is there a plan to do unit testing for the Epanet code?
* Is the idea was to run simulations and compare output only?
* I don't know how unit testing works on C, but we could test the python bindings of epanet with pytest (I have used this...), so the actual unit testing is made there (which will be simpler I assume..)

**Comment by samhatchett** [comment]
I like the packaging discussion and this is all pretty exciting, but for really forward-thinking items like unit testing and CI, those conversations might be better in epanet-dev since that's where continued engine development will be focused.

**Comment by goanpeca** [comment]
:+1:

**Comment by samhatchett** [comment]
closing due to staleness
