### ISSUE TITLE
New community forum using GitHub Discussions tab

### ISSUE THREAD

**Issue by Mariosmsk** [OpenWaterAnalytics/EPANET#819]
I’d like to suggest creating a new repository, such as **OpenWaterAnalyticsCommunity**, dedicated solely to discussions and community engagement, with the Discussions feature enabled. This would provide a focused space for the community to ask questions, share insights, and collaborate on ideas.

What do you think? 

#764
`The link to the Forums (http://community.wateranalytics.org/) no longer works. This loss of the forum is unfortunate since it was a useful resource for practitioners.`

**Comment by LRossman** [comment]
I like it. One of the repository owners, whose main page has a "Settings" button on it, will have to set it up.

**Comment by samhatchett** [comment]
good call! https://github.com/orgs/OpenWaterAnalytics/discussions
