### ISSUE TITLE
ENgetcurve and ENgetpattern (and family) should use similar patterns

### ISSUE THREAD

**Issue by samhatchett** [OpenWaterAnalytics/EPANET#9]
@eladsal can fill in some details here. apparently returning a pointer to an array is a no-no in VB.

**Comment by eladsal** [comment]
Pointers are not totally a no-no in VB but they do make things very difficult especially retrieving an array from the DLL. By Vb i'm referring to Visual Basic 6 and Visual Basic for Application, VBA, which is the official macro language of the Microsoft Office suite and is used by many. One example would be the [EPANET Excel Addin](http://www.water-simulation.com/wsp/2014/04/11/epanet-excel-add-in/).

The current EPANET base code does not allow retrial of curves, which is very needed, but allows reading, writing and adding patterns which are in similar structure. Currently the way to retrieve patterns is by first getting their index using `ENgetpatternindex` then getting their length using `ENgetpatternlen` and finally reading the values one by on using `ENgetpatternvalue`. Updating patterns is done in two ways. One is updating a single value using `ENsetpatternvalue` and the second is by writing an entire pattern as an array using `ENsetpattern` (this is the only function which uses an array).

We can adopt the same strategy for curves: `ENgetcurveindex`, `ENgetcurvelen`, `ENgetcurvevalue`, `ENsetcurvevalue` and `ENsetcurve`. We can also add `ENaddcurve` like the `ENaddpattern` function.

This does not mean that we can't have it both ways and keep also the current function which uses the array pointer.

**Comment by samhatchett** [comment]
cool - so we don't have to eliminate the function that returns the array of pattern values? that seems like a good situation. we just have to offer the couple of supportive API functions to extract single values out of it.

**Comment by eldemet** [comment]
+1 :-)
