### ISSUE TITLE
should we auto-format code ?

### ISSUE THREAD

**Issue by samhatchett** [OpenWaterAnalytics/EPANET#99]
example generator here: http://cf.monofraps.net

There are handy utilities like this (`clang-format`) which will auto-format the code in any number of styling conventions. I think this sort of tool is super-useful and goes a long way to democratize the contribution process so that the style is a non-issue. 

If part of the contribution process were to auto-format your code prior to committing, then we wouldn't have to spend any time at all on discussing the subject. Now deciding on the style convention is another matter entirely. The fact that `clang-format` has a handful of built-in templates (mozilla,google,chromium,llvm,webkit) means that even those teams don't agree on style - so how will we ever settle? 😉

**Comment by michaeltryby** [comment]
@samhatchett I like the idea of automatic code formatting. We experimented with clang-format over in the swmm repo but it didn't work all that well. The formatter isn't integrated in the the GitHub workflow and  needs to be run before you commit the code. As a result, a lot of improperly formatted code was getting flagged and kicked back in the PR process. This became a nuisance for new developers and we ended up shutting code formatting off. 

The whole experience left me wondering if there is a better way to integrate formatting into the submission process. Have you heard of one?

**Comment by samhatchett** [comment]
no, i spent some time looking for a Robot that would auto-format and commit automatically, but no dice.

I would just say also that this auto-formatting need *not* be an enforced requirement for passing CI. I'm not in favor of a robot rejecting contributions on the basis of formatting - it's just that a clang-format config file is a fairly unambiguous style guide for many aspects of code appearance. If we can settle on one predefined style, then the "pro" developers can use clang-format in their workflow and everyone else can just manually follow the style and make modifications based on more personal feedback.

So, for example, instead of having a "style guide" per-se, we just say "ok, team, use the `.clang-format` specs or reference the [google guide](https://google.github.io/styleguide/cppguide.html) and preferCamelCase, and we're off to the races"

**Comment by bemcdonnell** [comment]
@michaeltryby, it is common to format code with before committing. I don’t know of any that will format for you after committing. The swmm one was good except that it was setup to fail CI if the code wasnt formatted. I agree with @samhatchett that unformatted code shouldn’t trigger a CI fail.

**Comment by michaeltryby** [comment]
@bemcdonnell Actually I think the Kitware guys have a robot setup on their repos to automatically run a formatter on submissions.

**Comment by bemcdonnell** [comment]
@michaeltryby, do you trust robots? :-)

I think formatting before committing is a good strategy.

**Comment by michaeltryby** [comment]
@bemcdonnell In theory its a good practice. In reality, it kicked back peoples PRs and you ended up shutting it off. So what was learned in that experience? 

We need to post instructions for developers on how to setup and run a formatter prior to a commit. I'm open to doing it, I just don't know how.

**Comment by bemcdonnell** [comment]
@michaeltryby, in practice, we should just make it clear that the formatting doesn’t meet but not fail the PR.

**Comment by LRossman** [comment]
I don't think using an auto-formatter is a complete solution. I'd prefer posting a scaled-down version of something like the [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html), suitably customized to our particular needs (which is more extensive but in line with the suggestion made by @samhatchett above). I can work on a draft if you all think it's worthwhile.

**Comment by samhatchett** [comment]
so I think the answer to the issue title is "no" - which is fine with me. thanks!
